import { authFetch } from "./http";
import type { CategoryApi, CategoryImage, ManagedCategory } from "./category-contract";

type Raw = Record<string, unknown>;
const apiBase = () => process.env.NEXT_PUBLIC_SUPERX_API_BASE_URL?.replace(/\/$/, "");
export const categoryImageUrl = (url: string | null | undefined) => url ? `${apiBase() ?? ""}${url.startsWith("/") ? url : `/${url}`}` : "";
const image = (raw: Raw): CategoryImage => ({ id: String(raw.id ?? ""), url: String(raw.url ?? ""), altText: typeof raw.altText === "string" ? raw.altText : null, sortOrder: Number(raw.sortOrder ?? 0), isPrimary: raw.isPrimary === true });
const category = (raw: Raw): ManagedCategory => ({ id: String(raw.id ?? ""), name: String(raw.name ?? ""), slug: String(raw.slug ?? ""), parentId: raw.parentId == null ? null : String(raw.parentId), sortOrder: Number(raw.sortOrder ?? 0), isActive: raw.isActive !== false, images: Array.isArray(raw.images) ? raw.images.map((item) => image(item as Raw)).sort((a, b) => a.sortOrder - b.sortOrder) : [], imageUrl: typeof raw.imageUrl === "string" ? raw.imageUrl : null, ...(typeof raw.productCount === "number" ? { productCount: raw.productCount } : {}) });
const message = (payload: unknown) => { const raw = payload && typeof payload === "object" ? (payload as { message?: unknown }).message : undefined; return typeof raw === "string" ? raw : Array.isArray(raw) ? raw.filter((part): part is string => typeof part === "string").join(" ") : "No pudimos completar la operación."; };
async function json(path: string, init: RequestInit = {}) { const base = apiBase(); if (!base) throw new Error("La gestión de categorías requiere conexión con la API."); const response = await authFetch(`${base}${path}`, { ...init, headers: { Accept: "application/json", ...(init.body ? { "Content-Type": "application/json" } : {}), ...init.headers } }); const payload: unknown = await response.json().catch(() => undefined); if (!response.ok) throw Object.assign(new Error(response.status === 401 || response.status === 403 ? "No tenés permiso para gestionar categorías." : message(payload)), { status: response.status }); return payload; }
async function upload(path: string, data: FormData, onProgress?: (percent: number) => void): Promise<unknown> { const base = apiBase(); if (!base) throw new Error("La carga de imágenes requiere conexión con la API."); onProgress?.(0); const response = await authFetch(`${base}${path}`, { method: "POST", body: data, headers: { Accept: "application/json" } }); const payload: unknown = await response.json().catch(() => undefined); if (!response.ok) throw Object.assign(new Error(response.status === 401 || response.status === 403 ? "No tenés permiso para subir imágenes." : message(payload)), { status: response.status }); onProgress?.(100); return payload; }
const numberId = (value: string | null | undefined) => value ? Number(value) : undefined;

export const categoryApi: CategoryApi = {
  async list() { const payload = await json("/categories?includeInactive=true"); return (Array.isArray(payload) ? payload : []).map((item) => category(item as Raw)); },
  async get(id) { return category(await json(`/categories/${encodeURIComponent(id)}`) as Raw); },
  async create(input) { return category(await json("/categories", { method: "POST", body: JSON.stringify({ name: input.name.trim(), ...(input.slug?.trim() ? { slug: input.slug.trim() } : {}), ...(input.parentId ? { parentId: numberId(input.parentId) } : {}), sortOrder: Number(input.sortOrder ?? 0) }) }) as Raw); },
  async update(id, input) { return category(await json(`/categories/${encodeURIComponent(id)}`, { method: "PATCH", body: JSON.stringify({ ...input, ...(input.name === undefined ? {} : { name: input.name.trim() }), ...(input.parentId === undefined ? {} : { parentId: numberId(input.parentId) }), ...(input.sortOrder === undefined ? {} : { sortOrder: Number(input.sortOrder) }) }) }) as Raw); },
  async uploadImage(id, file, altText, onProgress) { const form = new FormData(); form.append("file", file); if (altText?.trim()) form.append("altText", altText.trim()); return image(await upload(`/categories/${encodeURIComponent(id)}/images`, form, onProgress) as Raw); },
  async updateImage(categoryId, imageId, input) { return image(await json(`/categories/${encodeURIComponent(categoryId)}/images/${encodeURIComponent(imageId)}`, { method: "PATCH", body: JSON.stringify(input) }) as Raw); },
  async deleteImage(categoryId, imageId) { await json(`/categories/${encodeURIComponent(categoryId)}/images/${encodeURIComponent(imageId)}`, { method: "DELETE" }); },
  async orderImages(categoryId, imageIds) { await json(`/categories/${encodeURIComponent(categoryId)}/images/order`, { method: "PUT", body: JSON.stringify({ imageIds: imageIds.map(Number) }) }); },
};
