import { authFetch } from "@/app/lib/http";
import type { DashboardApi, DashboardDueItem, DashboardFilters, DashboardKpis, DashboardTreasury } from "./dashboard-contract";

const baseUrl = () => process.env.NEXT_PUBLIC_SUPERX_API_BASE_URL;
const wait = () => new Promise<void>((resolve) => setTimeout(resolve, 180));
const text = (value: unknown, fallback = "—") => value == null ? fallback : String(value);
const amount = (value: unknown) => value == null ? "0.00" : String(value);
const number = (value: unknown) => Number(value ?? 0);
function params(filters: DashboardFilters) { const search = new URLSearchParams(); for (const [key, value] of Object.entries(filters)) if (value !== undefined && value !== "") search.set(key, String(value)); return search.toString(); }
/** kpis, expenses-by-category and treasury reject `limit` (strict whitelist on the backend). */
function rangeParams(filters: DashboardFilters) { return params({ ...filters, limit: undefined }); }
async function fetchJson(path: string): Promise<unknown> { const response = await authFetch(`${baseUrl()!.replace(/\/$/, "")}${path}`, { headers: { Accept: "application/json" } }); const payload: unknown = await response.json().catch(() => undefined); if (!response.ok) { const message = payload && typeof payload === "object" && typeof (payload as { message?: unknown }).message === "string" ? (payload as { message: string }).message : "No pudimos cargar el bloque administrativo."; throw Object.assign(new Error(response.status === 401 || response.status === 403 ? "No tenés permiso para ver Administración." : response.status === 400 ? `Revisá los filtros: ${message}` : response.status === 404 ? "El recurso solicitado ya no está disponible." : message), { status: response.status }); } return payload; }
const emptyKpis = (filters: DashboardFilters): DashboardKpis => ({ from: filters.from ?? "", to: filters.to ?? "", currency: filters.currency ?? "ARS", generatedAt: new Date().toISOString(), purchases: { total: "0.00" }, pendingReceipt: { orders: 0, units: 0, value: "0.00" }, invoiced: "0.00", paidSuppliers: "0.00", paidExpenses: "0.00", paidInvestments: "0.00", advances: "0.00", payablesOpen: { count: 0, amount: "0.00" }, payablesOverdue: { count: 0, amount: "0.00" }, expenses: { total: "0.00", paid: "0.00", pending: "0.00", overdue: "0.00" }, investments: { total: "0.00", paid: "0.00", pending: "0.00" }, dueSoon: { next7: [], next30: [] } });
function due(raw: Record<string, unknown>): DashboardDueItem { const link = raw.link as Record<string, unknown> | undefined; return { id: text(raw.id, ""), type: text(raw.type, "SUPPLIER_INVOICE") as DashboardDueItem["type"], label: text(raw.label), supplier: raw.supplier == null ? undefined : text(raw.supplier), dueDate: text(raw.dueDate), total: amount(raw.total), paid: amount(raw.paid), balance: amount(raw.balance), status: raw.status == null ? undefined : text(raw.status), link: { type: text(link?.type ?? raw.type, "SUPPLIER_INVOICE") as DashboardDueItem["type"], id: text(link?.id ?? raw.id, "") } }; }

export const dashboardApi: DashboardApi = {
  async kpis(filters) { if (!baseUrl()) { await wait(); return emptyKpis(filters); } const raw = await fetchJson(`/admin-dashboard/kpis?${rangeParams(filters)}`) as Record<string, unknown>; const purchases = raw.purchases as Record<string, unknown> | undefined, pending = raw.pendingReceipt as Record<string, unknown> | undefined, open = raw.payablesOpen as Record<string, unknown> | undefined, overdue = raw.payablesOverdue as Record<string, unknown> | undefined, expenses = raw.expenses as Record<string, unknown> | undefined, investments = raw.investments as Record<string, unknown> | undefined, dueSoon = raw.dueSoon as Record<string, unknown> | undefined; return { from: text(raw.from, filters.from ?? ""), to: text(raw.to, filters.to ?? ""), currency: text(raw.currency, filters.currency ?? "ARS"), generatedAt: text(raw.generatedAt, new Date().toISOString()), purchases: { total: amount(purchases?.total) }, pendingReceipt: { orders: number(pending?.orders), units: number(pending?.units), value: amount(pending?.value) }, invoiced: amount(raw.invoiced), paidSuppliers: amount(raw.paidSuppliers), paidExpenses: amount(raw.paidExpenses), paidInvestments: amount(raw.paidInvestments), advances: amount(raw.advances), payablesOpen: { count: number(open?.count), amount: amount(open?.amount) }, payablesOverdue: { count: number(overdue?.count), amount: amount(overdue?.amount) }, expenses: { total: amount(expenses?.total), paid: amount(expenses?.paid), pending: amount(expenses?.pending), overdue: amount(expenses?.overdue) }, investments: { total: amount(investments?.total), paid: amount(investments?.paid), pending: amount(investments?.pending) }, dueSoon: { next7: Array.isArray(dueSoon?.next7) ? dueSoon.next7.map((item) => due(item as Record<string, unknown>)) : [], next30: Array.isArray(dueSoon?.next30) ? dueSoon.next30.map((item) => due(item as Record<string, unknown>)) : [] } }; },
  async payablesDue(filters) { if (!baseUrl()) { await wait(); return []; } const payload = await fetchJson(`/admin-dashboard/payables-due?${params(filters)}`) as { items?: Record<string, unknown>[] }; return (payload.items ?? []).map(due); },
  async pendingReceipts(filters) { if (!baseUrl()) { await wait(); return []; } const payload = await fetchJson(`/admin-dashboard/pending-receipts?${params(filters)}`) as { items?: Record<string, unknown>[] }; return (payload.items ?? []).map((raw) => ({ id: text(raw.id, ""), number: text(raw.number), supplier: text(raw.supplier), warehouse: text(raw.warehouse), expectedDate: raw.expectedDate == null ? null : text(raw.expectedDate), packsOrdered: number(raw.packsOrdered), packsReceived: number(raw.packsReceived), packsPending: number(raw.packsPending), unitsOrdered: number(raw.unitsOrdered), unitsReceived: number(raw.unitsReceived), unitsPending: number(raw.unitsPending), value: amount(raw.value), receiptStatus: text(raw.receiptStatus) })); },
  async topSuppliers(filters) { if (!baseUrl()) { await wait(); return []; } const payload = await fetchJson(`/admin-dashboard/top-suppliers?${params(filters)}`) as { items?: Record<string, unknown>[] }; return (payload.items ?? []).map((raw) => ({ id: text(raw.id, ""), name: text(raw.name), count: number(raw.count), balance: amount(raw.balance), overdue: amount(raw.overdue) })); },
  async expensesByCategory(filters) { if (!baseUrl()) { await wait(); return []; } const payload = await fetchJson(`/admin-dashboard/expenses-by-category?${rangeParams(filters)}`) as { items?: Record<string, unknown>[] }; return (payload.items ?? []).map((raw) => ({ id: text(raw.id, ""), name: text(raw.name), total: amount(raw.total), paid: amount(raw.paid), pending: amount(raw.pending) })); },
  async investments(filters) { if (!baseUrl()) { await wait(); return []; } const payload = await fetchJson(`/admin-dashboard/investments?${params(filters)}`) as { items?: Record<string, unknown>[] }; return (payload.items ?? []).map((raw) => ({ id: text(raw.id, ""), name: text(raw.name), category: raw.category == null ? null : text(raw.category), cost: amount(raw.cost), acquisitionDate: text(raw.acquisitionDate), status: text(raw.status), paid: amount(raw.paid), balance: amount(raw.balance), link: { type: "ASSET", id: text(raw.id, "") } })); },
  async treasury(filters) { if (!baseUrl()) { await wait(); return { from: filters.from ?? "", to: filters.to ?? "", currency: filters.currency ?? "ARS", accounts: [], total: "0.00", netMovement: "0.00", cashFlow: [] }; } const raw = await fetchJson(`/admin-dashboard/treasury?${rangeParams(filters)}`) as Record<string, unknown>; return { from: text(raw.from, filters.from ?? ""), to: text(raw.to, filters.to ?? ""), currency: text(raw.currency, filters.currency ?? "ARS"), total: amount(raw.total), netMovement: amount(raw.netMovement), accounts: Array.isArray(raw.accounts) ? raw.accounts.map((item) => { const account = item as Record<string, unknown>; return { id: text(account.id, ""), name: text(account.name), type: text(account.type), currency: text(account.currency), balance: amount(account.balance) }; }) : [], cashFlow: Array.isArray(raw.cashFlow) ? raw.cashFlow.map((item) => { const flow = item as Record<string, unknown>; return { date: text(flow.date), in: amount(flow.in), out: amount(flow.out), net: amount(flow.net) }; }) : [] } satisfies DashboardTreasury; },
};
