import { apiBaseUrl, fixturesEnabled } from "./api-mode";
import { getStoredUser } from "./auth-api";
import { canStartOrder } from "./dispatch-rules";
import { authFetch } from "@/app/lib/http";
import type { DispatchApi, DispatchBoard, DispatchHistory, DispatchOrder, IncidentReason, LatLng, RouteEstimate } from "./dispatch-contract";

const wait = (ms = 120) => new Promise<void>((resolve) => setTimeout(resolve, ms));
const base = () => apiBaseUrl();
export class DispatchApiError extends Error { constructor(message: string, readonly status?: number, readonly code?: string) { super(message); this.name = "DispatchApiError"; } }
const today = () => new Intl.DateTimeFormat("en-CA", { timeZone: "America/Argentina/Buenos_Aires" }).format(new Date());
const delivery = (name: string, phone: string, address: string, start: string, end: string) => ({ recipientName: name, phone, addressLine: address, neighborhood: "Centro", postalCode: "2741", cityName: "Salto", addressNotes: "Tocar timbre", customerNotes: null, zoneName: "Centro", slotDate: today(), slotStart: start, slotEnd: end });
const order = (id: string, number: string, status: DispatchOrder["status"], position: number, name: string, address: string, location: LatLng | null): DispatchOrder => ({ id, orderNumber: number, status, position, paymentMethod: "CASH", paymentStatus: "PENDING", delivery: delivery(name, `+54 9 2474 40${id.padStart(4, "0")}`, address, "17:00:00", "20:00:00"), location, dispatchedBy: status === "READY" ? null : { id: "fixture-admin", name: "Administración" }, dispatchedAt: status === "READY" ? null : new Date().toISOString(), deliveredAt: status === "DELIVERED" ? new Date().toISOString() : null, incident: null, items: [{ productName: "Yerba mate tradicional 500 g", quantity: 2, unitCode: "UN", imageUrl: null }, { productName: "Agua mineral sin gas 1,5 L", quantity: 3, unitCode: "UN", imageUrl: null }] });
let fixtureOrders = [order("1", "SX-1048", "READY", 1, "Ana Gómez", "Av. España 620", { lat: -34.2921, lng: -60.2546 }), order("2", "SX-1049", "READY", 2, "Marcos Ruiz", "San Pablo 481", { lat: -34.2982, lng: -60.2493 }), order("3", "SX-1050", "READY", 3, "Lucía Fernández", "Buenos Aires 1024", null)];
const cloneOrder = (o: DispatchOrder): DispatchOrder => structuredClone(o);
const board = (date = today()): DispatchBoard => { const ready = fixtureOrders.filter((o) => o.status === "READY").map(cloneOrder); const dispatched = fixtureOrders.filter((o) => o.status === "DISPATCHED").map(cloneOrder); const outForDelivery = fixtureOrders.filter((o) => o.status === "OUT_FOR_DELIVERY").map(cloneOrder); const delivered = fixtureOrders.filter((o) => o.status === "DELIVERED").map(cloneOrder); const all = [...ready, ...dispatched, ...outForDelivery, ...delivered]; return { date, ready, dispatched, outForDelivery, delivered, summary: { total: all.length, pending: ready.length + dispatched.length + outForDelivery.length, delivered: delivered.length, incidents: all.filter((o) => o.incident).length } }; };
async function request(path: string, init?: RequestInit): Promise<unknown> { const response = await authFetch(`${base()!.replace(/\/$/, "")}${path}`, { ...init, headers: { Accept: "application/json", ...(init?.body ? { "Content-Type": "application/json" } : {}) } }); const payload: unknown = await response.json().catch(() => undefined); if (response.status === 401) throw new DispatchApiError("Iniciá sesión para trabajar en reparto.", 401, "unauthenticated"); if (!response.ok) { const raw = payload && typeof payload === "object" ? (payload as { message?: unknown }).message : undefined; throw new DispatchApiError(typeof raw === "string" ? raw : "No pudimos completar la acción.", response.status); } return payload; }
const numericIds = (ids: string[]) => ids.map(Number);
export const dispatchApi: DispatchApi = {
  async getOrderItems(id) {
    if (fixturesEnabled()) { await wait(); return structuredClone(fixtureOrders.find((item) => item.id === id)?.items ?? []); }
    // /dispatch currently omits saleMode/pickedQuantity. /orders/:id admits staff;
    // whitelist only operational fields so no money enters the driver UI.
    const raw = await request(`/orders/${encodeURIComponent(id)}`) as { items: Array<{ productName: string; quantity: number; pickedQuantity?: number | null; saleMode?: "UNIT" | "WEIGHT"; unitCode: string }> };
    return raw.items.map((item) => ({ productName: item.productName, quantity: item.quantity, pickedQuantity: item.pickedQuantity, saleMode: item.saleMode ?? "UNIT", unitCode: item.unitCode, imageUrl: null }));
  },
  async getBoard(date) { if (fixturesEnabled()) { await wait(); return board(date); } return request(`/dispatch${date ? `?date=${encodeURIComponent(date)}` : ""}`) as Promise<DispatchBoard>; },
  async saveSequence(ids) { if (fixturesEnabled()) { await wait(); const positions = new Map(ids.map((id, i) => [id, i + 1])); fixtureOrders = fixtureOrders.map((o) => positions.has(o.id) ? { ...o, position: positions.get(o.id)! } : o); return board(); } return request("/dispatch/sequence", { method: "PUT", body: JSON.stringify({ orderIds: numericIds(ids) }) }) as Promise<DispatchBoard>; },
  async assign(ids) { if (fixturesEnabled()) { await wait(); const selected = new Set(ids); if (ids.some((id) => fixtureOrders.find((o) => o.id === id)?.status !== "READY")) throw new DispatchApiError("Los pedidos deben estar listos para cargar.", 409); const user = getStoredUser(); fixtureOrders = fixtureOrders.map((o) => selected.has(o.id) ? { ...o, status: "DISPATCHED", dispatchedBy: user ? { id: user.id, name: user.name } : null } : o); return board(); } return request("/dispatch/assign", { method: "POST", body: JSON.stringify({ orderIds: numericIds(ids) }) }) as Promise<DispatchBoard>; },
  async start(ids) { if (fixturesEnabled()) { await wait(); const selected = new Set(ids); if (ids.some((id) => fixtureOrders.find((o) => o.id === id)?.status !== "DISPATCHED")) throw new DispatchApiError("Los pedidos deben estar cargados para iniciar.", 409); if (fixtureOrders.some((o) => selected.has(o.id) && !canStartOrder(o, getStoredUser()))) throw new DispatchApiError("Solo podés iniciar los pedidos que cargaste vos.", 403); fixtureOrders = fixtureOrders.map((o) => selected.has(o.id) ? { ...o, status: "OUT_FOR_DELIVERY", dispatchedAt: new Date().toISOString() } : o); return board(); } return request("/dispatch/start", { method: "POST", body: JSON.stringify({ orderIds: numericIds(ids) }) }) as Promise<DispatchBoard>; },
  async route(ids, origin) { if (fixturesEnabled()) { await wait(); const located = ids.map((id) => fixtureOrders.find((o) => o.id === id)).filter((o): o is DispatchOrder => Boolean(o)).filter((o) => o.location); if (located.length < 1 || (located.length < 2 && !origin)) return { available: false, reason: "No hay suficientes paradas ubicadas para estimar la ruta." }; return { available: false, reason: "La estimación vial no está disponible en el modo de prueba." }; } return request("/dispatch/route", { method: "POST", body: JSON.stringify({ orderIds: numericIds(ids), ...(origin ? { origin } : {}) }) }) as Promise<RouteEstimate>; },
  async optimize(ids, origin) { if (fixturesEnabled()) { await wait(); const located = ids.filter((id) => fixtureOrders.find((o) => o.id === id)?.location); const missing = ids.filter((id) => !located.includes(id)); return this.saveSequence([...located, ...missing]); } return request("/dispatch/optimize", { method: "POST", body: JSON.stringify({ orderIds: numericIds(ids), ...(origin ? { origin } : {}) }) }) as Promise<DispatchBoard>; },
  async markDelivered(id, note) { if (fixturesEnabled()) { await wait(); fixtureOrders = fixtureOrders.map((o) => o.id === id ? { ...o, status: "DELIVERED", deliveredAt: new Date().toISOString() } : o); return board(); } return request(`/dispatch/${encodeURIComponent(id)}/delivered`, { method: "POST", body: JSON.stringify(note ? { note } : {}) }) as Promise<DispatchBoard>; },
  async reportIncident(id, reason: IncidentReason, note) { if (fixturesEnabled()) { await wait(); fixtureOrders = fixtureOrders.map((o) => o.id === id ? { ...o, incident: { id: `incident-${id}`, reason, note: note || null, createdAt: new Date().toISOString(), reportedBy: { id: "fixture-admin", name: "Administración" } } } : o); return board(); } return request(`/dispatch/${encodeURIComponent(id)}/incident`, { method: "POST", body: JSON.stringify({ reason, ...(note ? { note } : {}) }) }) as Promise<DispatchBoard>; },
  async history(from, to) { if (fixturesEnabled()) { await wait(); const b = board(); return { days: [{ date: b.date, delivered: b.delivered.length, incidents: b.summary.incidents, orders: [...b.delivered, ...b.outForDelivery.filter((o) => o.incident)] }] }; } const params = new URLSearchParams(); if (from) params.set("from", from); if (to) params.set("to", to); return request(`/dispatch/history${params.size ? `?${params}` : ""}`) as Promise<DispatchHistory>; },
};
