import type { DispatchBoard, DispatchDelivery, DispatchOrder, LatLng } from "./dispatch-contract";
export function moveItem<T>(list: T[], from: number, to: number): T[];
export function slotLabel(delivery: Pick<DispatchDelivery, "slotDate" | "slotStart" | "slotEnd"> | null | undefined, now?: Date): string;
export function timeRange(delivery: Pick<DispatchDelivery, "slotStart" | "slotEnd"> | null | undefined): string;
export function mapsUrl(delivery: Pick<DispatchDelivery, "addressLine" | "cityName" | "postalCode"> | null | undefined, location?: LatLng | null): string | null;
export function paymentHint(order: Pick<DispatchOrder, "paymentMethod" | "paymentStatus">): string;
export function routeOrders(board: Pick<DispatchBoard, "dispatched" | "outForDelivery">): DispatchOrder[];
export function filterOrders(board: DispatchBoard, filter: "route" | "pending" | "delivered"): DispatchOrder[];
export function nextStop(board: DispatchBoard, afterId?: string): DispatchOrder | null;
export function progressLabel(board: DispatchBoard, orderId: string): string;
export function formatDistance(meters: number): string;
export function formatDuration(seconds: number): string;
