import type { InventoryApi, InventoryFilters, InventoryItem, InventoryMovementInput, Warehouse } from "./inventory-contract";
import { getInventoryStatus } from "./inventory-rules";

const wait = () => new Promise<void>((resolve) => setTimeout(resolve, 250));
const warehouses: Warehouse[] = [{ id: "wh-central", name: "Depósito central", code: "CENTRAL" }, { id: "wh-norte", name: "Sucursal Norte", code: "NORTE" }, { id: "wh-sur", name: "Sucursal Sur", code: "SUR" }];
let inventory: InventoryItem[] = [
  { id: "inv-001", productId: "prd-001", productName: "Agua mineral sin gas 1,5 L", sku: "SUP-0001", warehouseId: "wh-central", onHand: 48, minimum: 18, updatedAt: "2026-09-04T12:00:00.000Z", movements: [{ id: "mov-001", inventoryItemId: "inv-001", type: "receipt", quantity: 60, reason: "Recepción OC-1842", occurredAt: "2026-09-03T10:15:00.000Z", createdBy: "María González" }, { id: "mov-002", inventoryItemId: "inv-001", type: "sale", quantity: -12, reason: "Ventas del turno", occurredAt: "2026-09-04T11:40:00.000Z", createdBy: "Integración ventas" }] },
  { id: "inv-002", productId: "prd-002", productName: "Yerba mate tradicional 500 g", sku: "CAM-0002", warehouseId: "wh-central", onHand: 8, minimum: 12, updatedAt: "2026-09-04T09:30:00.000Z", movements: [{ id: "mov-003", inventoryItemId: "inv-002", type: "receipt", quantity: 20, reason: "Recepción OC-1838", occurredAt: "2026-09-01T14:00:00.000Z", createdBy: "Juan Fernández" }, { id: "mov-004", inventoryItemId: "inv-002", type: "sale", quantity: -12, reason: "Ventas del turno", occurredAt: "2026-09-04T09:30:00.000Z", createdBy: "Integración ventas" }] },
  { id: "inv-003", productId: "prd-003", productName: "Jugo de naranja 1 L", sku: "NAT-0003", warehouseId: "wh-norte", onHand: 0, minimum: 8, updatedAt: "2026-09-04T08:10:00.000Z", movements: [{ id: "mov-005", inventoryItemId: "inv-003", type: "sale", quantity: -6, reason: "Ventas del turno", occurredAt: "2026-09-04T08:10:00.000Z", createdBy: "Integración ventas" }] },
  { id: "inv-004", productId: "prd-001", productName: "Agua mineral sin gas 1,5 L", sku: "SUP-0001", warehouseId: "wh-sur", onHand: 25, minimum: 10, updatedAt: "2026-09-03T16:00:00.000Z", movements: [{ id: "mov-006", inventoryItemId: "inv-004", type: "transfer", quantity: 25, reason: "Transferencia desde central", occurredAt: "2026-09-03T16:00:00.000Z", createdBy: "María González" }] },
];
const unavailable = () => new Error("La posición de stock ya no está disponible. Actualizá el listado e intentá nuevamente.");

/** Mock TEMPORAL bloqueado por BE-008. Conserva el contrato de GET /api/inventory y POST /api/inventory/movements; reemplazar por cliente HTTP cuando el backend esté disponible. */
export const inventoryApi: InventoryApi = {
  async listInventory(filters: InventoryFilters = {}) { await wait(); const query = filters.query?.trim().toLocaleLowerCase("es-AR") ?? ""; return inventory.filter((item) => (!query || [item.productName, item.sku].some((value) => value.toLocaleLowerCase("es-AR").includes(query))) && (!filters.warehouseId || item.warehouseId === filters.warehouseId) && (!filters.status || filters.status === "all" || getInventoryStatus(item) === filters.status)); },
  async listWarehouses() { await wait(); return warehouses; },
  async createMovement(input: InventoryMovementInput) { await wait(); const item = inventory.find((candidate) => candidate.id === input.inventoryItemId); if (!item) throw unavailable(); if (!Number.isInteger(input.quantity) || input.quantity === 0 || !input.reason.trim()) throw new Error("El movimiento informado no es válido."); if (item.onHand + input.quantity < 0) throw new Error("El movimiento no puede dejar el stock por debajo de cero."); const movement = { id: `mov-${crypto.randomUUID()}`, inventoryItemId: item.id, type: "adjustment" as const, quantity: input.quantity, reason: input.reason.trim(), occurredAt: new Date().toISOString(), createdBy: input.createdBy }; const updated: InventoryItem = { ...item, onHand: item.onHand + input.quantity, updatedAt: movement.occurredAt, movements: [movement, ...item.movements] }; inventory = inventory.map((candidate) => candidate.id === item.id ? updated : candidate); return updated; },
};
