import { authHeaders } from "@/app/lib/auth-api";
import type { InvoiceApi, InvoiceEvent, InvoiceFilters, PayablesSummary, SupplierInvoice, SupplierInvoiceSummary } from "./invoice-contract";
type Raw = Record<string, unknown>;
const baseUrl = () => process.env.NEXT_PUBLIC_SUPERX_API_BASE_URL;
const str = (value: unknown) => String(value ?? "");
const nullable = (value: unknown) => value == null ? null : str(value);
const errorMessage = (status: number, payload: unknown) => { const raw = payload as { message?: unknown; code?: unknown }; if (status === 409 && raw?.code === "VARIANCE_REQUIRES_CONFIRMATION") return "VARIANCE_REQUIRES_CONFIRMATION"; if (status === 409) return typeof raw?.message === "string" ? raw.message : "La operación entra en conflicto con el estado actual."; if (status === 404) return "No encontramos el documento solicitado."; if (status === 400) return typeof raw?.message === "string" ? raw.message : "Revisá los datos de la factura."; return typeof raw?.message === "string" ? raw.message : "No pudimos completar la operación."; };
async function fetchJson(path: string, init: RequestInit = {}) { const response = await fetch(`${baseUrl()!.replace(/\/$/, "")}${path}`, { ...init, headers: { Accept: "application/json", ...(init.body ? { "Content-Type": "application/json" } : {}), ...authHeaders(), ...init.headers } }); const payload: unknown = response.status === 204 ? undefined : await response.json().catch(() => undefined); if (!response.ok) throw Object.assign(new Error(errorMessage(response.status, payload)), { status: response.status, payload }); return payload; }
const summary = (raw: Raw): SupplierInvoiceSummary => ({ id: str(raw.id), supplierId: str(raw.supplierId), purchaseOrderId: nullable(raw.purchaseOrderId), voucherType: (raw.voucherType as SupplierInvoiceSummary["voucherType"]) ?? "OTHER", pointOfSale: str(raw.pointOfSale), number: str(raw.number), issueDate: str(raw.issueDate), dueDate: str(raw.dueDate), currency: str(raw.currency || "ARS"), subtotal: str(raw.subtotal), discountTotal: str(raw.discountTotal), taxTotal: str(raw.taxTotal), total: str(raw.total), attachmentUrl: nullable(raw.attachmentUrl), notes: nullable(raw.notes), status: (raw.status as SupplierInvoiceSummary["status"]) ?? "ACTIVE", varianceAmount: nullable(raw.varianceAmount), varianceReason: nullable(raw.varianceReason), createdAt: str(raw.createdAt), updatedAt: str(raw.updatedAt), supplier: { id: str((raw.supplier as Raw | undefined)?.id ?? raw.supplierId), name: str((raw.supplier as Raw | undefined)?.name) }, paidAmount: str(raw.paidAmount), balance: str(raw.balance), paymentStatus: (raw.paymentStatus as SupplierInvoiceSummary["paymentStatus"]) ?? "UNPAID" });
const event = (raw: Raw): InvoiceEvent => ({ id: str(raw.id), type: raw.type as InvoiceEvent["type"], actorUserId: str(raw.actorUserId), note: nullable(raw.note), data: raw.data && typeof raw.data === "object" ? raw.data as Record<string, unknown> : null, createdAt: str(raw.createdAt) });
const detail = (raw: Raw): SupplierInvoice => ({ ...summary(raw), purchaseOrder: raw.purchaseOrder && typeof raw.purchaseOrder === "object" ? { id: str((raw.purchaseOrder as Raw).id), number: nullable((raw.purchaseOrder as Raw).number) } : null, payments: Array.isArray(raw.payments) ? raw.payments.map((p) => ({ id: str((p as Raw).id), paymentId: str((p as Raw).paymentId), targetType: "SUPPLIER_INVOICE", targetId: str((p as Raw).targetId), amount: str((p as Raw).amount), paidAt: nullable((p as Raw).paid_at ?? (p as Raw).paidAt) ?? undefined, method: nullable((p as Raw).method) ?? undefined, status: nullable((p as Raw).status) ?? undefined })) : [], events: Array.isArray(raw.events) ? raw.events.map((p) => event(p as Raw)) : [] });
const empty = { items: [], total: 0, page: 1, pageSize: 25 };
export const invoiceApi: InvoiceApi = { async list(filters: InvoiceFilters = {}) { if (!baseUrl()) return empty; const params = new URLSearchParams(); Object.entries(filters).forEach(([key, value]) => { if (value) params.set(key, String(value)); }); const raw = await fetchJson(`/supplier-invoices?${params}`) as Raw; return { items: Array.isArray(raw.items) ? raw.items.map((item) => summary(item as Raw)) : [], total: Number(raw.total ?? 0), page: Number(raw.page ?? 1), pageSize: Number(raw.pageSize ?? 25) }; }, async get(id) { if (!baseUrl()) throw new Error("La factura no está disponible en modo fixture."); return detail(await fetchJson(`/supplier-invoices/${encodeURIComponent(id)}`) as Raw); }, async create(input) { return detail(await fetchJson("/supplier-invoices", { method: "POST", body: JSON.stringify(input) }) as Raw); }, async update(id, input) { return summary(await fetchJson(`/supplier-invoices/${encodeURIComponent(id)}`, { method: "PATCH", body: JSON.stringify(input) }) as Raw); }, async void(id, reason) { return summary(await fetchJson(`/supplier-invoices/${encodeURIComponent(id)}/void`, { method: "POST", body: JSON.stringify({ reason }) }) as Raw); }, async events(id) { if (!baseUrl()) return []; const raw = await fetchJson(`/supplier-invoices/${encodeURIComponent(id)}/events`); return Array.isArray(raw) ? raw.map((item) => event(item as Raw)) : []; }, async orderInvoices(id) { if (!baseUrl()) return empty; const raw = await fetchJson(`/purchase-orders/${encodeURIComponent(id)}/invoices`) as Raw; return { items: Array.isArray(raw.items) ? raw.items.map((item) => summary(item as Raw)) : [], total: Number(raw.total ?? 0), page: Number(raw.page ?? 1), pageSize: Number(raw.pageSize ?? 25) }; }, async summary(supplierId) { if (!baseUrl()) return { byCurrency: [], topSuppliers: [] }; const raw = await fetchJson(`/payables/summary${supplierId ? `?supplierId=${encodeURIComponent(supplierId)}` : ""}`) as Raw; return { byCurrency: Array.isArray(raw.byCurrency) ? raw.byCurrency as PayablesSummary["byCurrency"] : [], topSuppliers: Array.isArray(raw.topSuppliers) ? raw.topSuppliers as PayablesSummary["topSuppliers"] : [] }; } };
