import { authFetch } from "@/app/lib/http";
import type { LocationApi, LocationCity, LocationInput, LocationProduct, LocationWarehouse, ProductLocation, WarehouseInput, WarehouseLocation, WarehouseLocationWithProducts, WarehouseStats, LocationDetailData, LocationStockItem, LocationStockMovement, Paginated, WarehouseStockItem } from "./location-contract";

const wait = () => new Promise<void>((resolve) => setTimeout(resolve, 250));
const baseUrl = () => process.env.NEXT_PUBLIC_SUPERX_API_BASE_URL;

let fixtureLocations: WarehouseLocation[] = [
  { id: "loc-001", warehouseId: "wh-central", code: "A-01-01", aisle: "A", rack: "01", level: "01", sortOrder: 10, isActive: true, status: "ACTIVE", capacity: 120, capacityUnit: "unidades", createdAt: "2026-09-01T10:00:00.000Z", updatedAt: "2026-09-01T10:00:00.000Z" },
  { id: "loc-002", warehouseId: "wh-central", code: "A-01-02", aisle: "A", rack: "01", level: "02", sortOrder: 20, isActive: true, status: "ACTIVE", capacity: 80, capacityUnit: "unidades", createdAt: "2026-09-01T10:00:00.000Z", updatedAt: "2026-09-01T10:00:00.000Z" },
  { id: "loc-003", warehouseId: "wh-norte", code: "B-02-01", aisle: "B", rack: "02", level: "01", sortOrder: 10, isActive: false, status: "INACTIVE", capacity: null, capacityUnit: null, createdAt: "2026-09-02T10:00:00.000Z", updatedAt: "2026-09-02T10:00:00.000Z" },
];
let fixtureWarehouses: LocationWarehouse[] = [{ id: "wh-central", name: "Depósito central", status: "ACTIVE", cityId: "city-1", city: { name: "Buenos Aires" }, isPrimary: true, isActive: true }, { id: "wh-norte", name: "Sucursal Norte", status: "MAINTENANCE", cityId: "city-1", city: { name: "Buenos Aires" }, isPrimary: false, isActive: true }, { id: "wh-sur", name: "Sucursal Sur", status: "INACTIVE", cityId: "city-2", city: { name: "La Plata" }, isPrimary: false, isActive: false }];
const fixtureCities: LocationCity[] = [{ id: "city-1", name: "Buenos Aires" }, { id: "city-2", name: "La Plata" }];
const fixtureProducts: LocationProduct[] = [{ id: "prd-001", name: "Agua mineral sin gas 1,5 L", slug: "agua-mineral-sin-gas-1-5-l", sku: "SUP-0001", barcode: "7791234567890", availableStock: 48 }, { id: "prd-002", name: "Yerba mate tradicional 500 g", slug: "yerba-mate-tradicional-500-g", sku: "CAM-0002", barcode: "7791234567891", availableStock: 8 }, { id: "prd-003", name: "Jugo de naranja 1 L", slug: "jugo-de-naranja-1-l", sku: "NAT-0003", barcode: "7791234567892", availableStock: 0 }];
let fixtureAssignments: ProductLocation[] = [{ productId: "prd-001", warehouseId: "wh-central", location: fixtureLocations[0] }];
let fixtureStock: Array<{ warehouseId: string; locationId: string; productId: string; quantity: number; reservedQuantity: number }> = [{ warehouseId: "wh-central", locationId: "loc-001", productId: "prd-001", quantity: 72, reservedQuantity: 12 }, { warehouseId: "wh-central", locationId: "loc-001", productId: "prd-002", quantity: 18, reservedQuantity: 0 }, { warehouseId: "wh-central", locationId: "loc-002", productId: "prd-001", quantity: 24, reservedQuantity: 4 }];
let fixtureMovements: LocationStockMovement[] = [];

type RawLocationProduct = { id: string | number; name: string; slug?: string; sku?: string; barcode?: string; availableStock?: number };
type RawLocationStock = { productCount?: number; totalQuantity?: number; reservedQuantity?: number; availableQuantity?: number; occupancyPercentage?: number | null; primaryProduct?: { id: string | number; name: string; slug?: string } | null };
type RawLocation = { id: string | number; warehouseId: string | number; code: string; aisle: string; rack: string; level: string; sortOrder: number; isActive: boolean; status?: "ACTIVE" | "BLOCKED" | "INACTIVE"; capacity?: number | null; capacityUnit?: string | null; createdAt: string; updatedAt: string; products?: RawLocationProduct[]; stock?: RawLocationStock };
type RawWarehouse = { id: string | number; name: string; status?: "ACTIVE" | "INACTIVE" | "MAINTENANCE"; cityId?: string | number; city?: { id?: string | number; name?: string } | null; isPrimary?: boolean; isActive?: boolean };
type RawWarehouseStats = { warehouseId: string | number; locationsCount: number; racksCount: number; productsCount: number; totalQuantity: number; totalCapacity: number; occupancyPercentage: number | null; locationsFullCount: number; locationsEmptyCount: number; lastUpdatedAt: string | null };
type RawProductLocation = { productId: string | number; warehouseId: string | number; location: RawLocation };
type RawWarehouseStockItem = { product: RawLocationProduct; location: Pick<RawLocation, "id" | "code" | "aisle" | "rack" | "level">; quantity: number; reservedQuantity: number; availableQuantity: number };

const adaptProduct = (raw: RawLocationProduct): LocationProduct => ({ id: String(raw.id), name: raw.name, slug: raw.slug, sku: raw.sku, barcode: raw.barcode, availableStock: raw.availableStock });
const adaptLocation = (raw: RawLocation): WarehouseLocation => ({ ...raw, id: String(raw.id), warehouseId: String(raw.warehouseId), status: raw.status ?? (raw.isActive ? "ACTIVE" : "INACTIVE"), capacity: raw.capacity ?? null, capacityUnit: raw.capacityUnit ?? null });
const adaptLocationWithProducts = (raw: RawLocation): WarehouseLocationWithProducts => ({ ...adaptLocation(raw), products: (raw.products ?? []).map(adaptProduct), stock: { productCount: Number(raw.stock?.productCount ?? 0), totalQuantity: Number(raw.stock?.totalQuantity ?? 0), reservedQuantity: Number(raw.stock?.reservedQuantity ?? 0), availableQuantity: Number(raw.stock?.availableQuantity ?? 0), occupancyPercentage: raw.stock?.occupancyPercentage == null ? null : Number(raw.stock.occupancyPercentage), primaryProduct: raw.stock?.primaryProduct ? { id: String(raw.stock.primaryProduct.id), name: raw.stock.primaryProduct.name, slug: raw.stock.primaryProduct.slug ?? "" } : null } });
const adaptAssignment = (raw: RawProductLocation): ProductLocation => ({ productId: String(raw.productId), warehouseId: String(raw.warehouseId), location: adaptLocation(raw.location) });
const adaptWarehouse = (raw: RawWarehouse): LocationWarehouse => ({ id: String(raw.id), name: raw.name, status: raw.status ?? (raw.isActive === false ? "INACTIVE" : "ACTIVE"), cityId: raw.cityId === undefined ? undefined : String(raw.cityId), city: raw.city ? { id: raw.city.id === undefined ? undefined : String(raw.city.id), name: raw.city.name } : null, isPrimary: raw.isPrimary, isActive: raw.isActive });
const adaptWarehouseStats = (raw: RawWarehouseStats): WarehouseStats => ({ ...raw, warehouseId: String(raw.warehouseId), locationsCount: Number(raw.locationsCount ?? 0), racksCount: Number(raw.racksCount ?? 0), productsCount: Number(raw.productsCount ?? 0), totalQuantity: Number(raw.totalQuantity ?? 0), totalCapacity: Number(raw.totalCapacity ?? 0), occupancyPercentage: raw.occupancyPercentage === null ? null : Number(raw.occupancyPercentage), locationsFullCount: Number(raw.locationsFullCount ?? 0), locationsEmptyCount: Number(raw.locationsEmptyCount ?? 0), lastUpdatedAt: raw.lastUpdatedAt ?? null });
const warehouseInputBody = (input: WarehouseInput, includeCity = false) => ({ ...(includeCity && input.cityId ? { cityId: Number(input.cityId) } : {}), name: input.name.trim(), ...(input.isPrimary === undefined ? {} : { isPrimary: input.isPrimary }), ...(input.status === undefined ? {} : { status: input.status }) });
const fixtureWarehouseStats = (warehouseId: string): WarehouseStats => { const locations = fixtureLocations.filter((location) => location.warehouseId === warehouseId); const capacity = locations.reduce((sum, location) => sum + (location.capacity ?? 0), 0); const quantity = warehouseId === "wh-central" ? 90 : warehouseId === "wh-norte" ? 40 : 0; return { warehouseId, locationsCount: locations.length, racksCount: new Set(locations.map((location) => location.rack)).size, productsCount: fixtureAssignments.filter((assignment) => assignment.warehouseId === warehouseId).length, totalQuantity: quantity, totalCapacity: capacity, occupancyPercentage: capacity ? quantity / capacity * 100 : null, locationsFullCount: capacity && quantity >= capacity ? locations.length : 0, locationsEmptyCount: locations.filter((location) => location.capacity && quantity === 0).length, lastUpdatedAt: locations.reduce<string | null>((latest, location) => !latest || location.updatedAt > latest ? location.updatedAt : latest, null) }; };

async function fetchJson(path: string, init: RequestInit = {}): Promise<unknown> {
  const response = await authFetch(`${baseUrl()!.replace(/\/$/, "")}${path}`, { ...init, headers: { Accept: "application/json", ...(init.body ? { "Content-Type": "application/json" } : {}), ...init.headers } });
  const payload: unknown = response.status === 204 ? undefined : await response.json().catch(() => undefined);
  if (!response.ok) {
    const message = payload && typeof payload === "object" && typeof (payload as { message?: unknown }).message === "string" ? (payload as { message: string }).message : "No pudimos completar la operación.";
    throw Object.assign(new Error(response.status === 401 || response.status === 403 ? "No tenés permiso para hacer esto. Iniciá sesión con una cuenta autorizada." : message), { status: response.status });
  }
  return payload;
}

const inputBody = (input: LocationInput) => ({ ...input, code: input.code.trim(), aisle: input.aisle.trim(), rack: input.rack.trim(), level: input.level.trim() });
const fixtureItem = (warehouseId: string, locationId: string, productId: string): LocationStockItem => { const row = fixtureStock.find((item) => item.warehouseId === warehouseId && item.locationId === locationId && item.productId === productId); const product = fixtureProducts.find((item) => item.id === productId); if (!row || !product) throw new Error("El stock ya no está disponible."); return { product, quantity: row.quantity, reservedQuantity: row.reservedQuantity, availableQuantity: row.quantity - row.reservedQuantity }; };
const fixtureWarehouseStockItem = (warehouseId: string, locationId: string, productId: string): WarehouseStockItem => { const item = fixtureItem(warehouseId, locationId, productId); const location = fixtureLocations.find((candidate) => candidate.id === locationId && candidate.warehouseId === warehouseId); if (!location) throw new Error("La ubicación ya no está disponible."); return { ...item, location: { id: location.id, code: location.code, aisle: location.aisle, rack: location.rack, level: location.level } }; };
const fixtureLocationStock = (warehouseId: string, location: WarehouseLocation) => { const rows = fixtureStock.filter((item) => item.warehouseId === warehouseId && item.locationId === location.id); const totalQuantity = rows.reduce((sum, item) => sum + item.quantity, 0); const reservedQuantity = rows.reduce((sum, item) => sum + item.reservedQuantity, 0); const primary = rows[0] ? fixtureProducts.find((product) => product.id === rows[0].productId) : undefined; return { productCount: new Set(rows.map((item) => item.productId)).size, totalQuantity, reservedQuantity, availableQuantity: totalQuantity - reservedQuantity, occupancyPercentage: location.capacity ? totalQuantity / location.capacity * 100 : null, primaryProduct: primary ? { id: primary.id, name: primary.name, slug: primary.slug ?? "" } : null }; };
const fixtureMovement = (movement: Omit<LocationStockMovement, "id" | "createdAt" | "actorUserId">) => { fixtureMovements = [{ ...movement, id: crypto.randomUUID(), actorUserId: "Sistema", createdAt: new Date().toISOString() }, ...fixtureMovements]; };

export const locationApi: LocationApi = {
  async listWarehouses() {
    if (!baseUrl()) { await wait(); return fixtureWarehouses; }
    const payload = await fetchJson("/warehouses");
    return Array.isArray(payload) ? (payload as RawWarehouse[]).map(adaptWarehouse) : [];
  },
  async listWarehouseStats(ids) {
    if (!baseUrl()) { await wait(); return fixtureWarehouses.filter((warehouse) => !ids || ids.includes(warehouse.id)).map((warehouse) => fixtureWarehouseStats(warehouse.id)); }
    const query = ids?.length ? `?warehouseIds=${ids.map(encodeURIComponent).join(",")}` : "";
    const payload = await fetchJson(`/warehouses/stats${query}`);
    return Array.isArray(payload) ? (payload as RawWarehouseStats[]).map(adaptWarehouseStats) : [];
  },
  async getWarehouseStats(id) {
    if (!baseUrl()) { await wait(); const warehouse = fixtureWarehouses.find((item) => item.id === id); if (!warehouse) throw new Error("El depósito ya no está disponible."); return fixtureWarehouseStats(id); }
    return adaptWarehouseStats((await fetchJson(`/warehouses/${encodeURIComponent(id)}/stats`)) as RawWarehouseStats);
  },
  async createWarehouse(input) {
    if (!baseUrl()) { await wait(); if (!input.name.trim() || !input.cityId) throw new Error("Completá el nombre y la ciudad del depósito."); const city = fixtureCities.find((item) => item.id === input.cityId); const warehouse: LocationWarehouse = { id: `wh-${crypto.randomUUID()}`, name: input.name.trim(), status: "ACTIVE", cityId: input.cityId, city: city ? { name: city.name } : null, isPrimary: input.isPrimary ?? false, isActive: true }; fixtureWarehouses = [...fixtureWarehouses, warehouse]; return warehouse; }
    return adaptWarehouse((await fetchJson("/warehouses", { method: "POST", body: JSON.stringify(warehouseInputBody(input, true)) })) as RawWarehouse);
  },
  async updateWarehouse(id, input) {
    if (!baseUrl()) { await wait(); const current = fixtureWarehouses.find((item) => item.id === id); if (!current) throw new Error("El depósito ya no está disponible."); const next = { ...current, name: input.name.trim(), isPrimary: input.isPrimary ?? current.isPrimary, status: input.status ?? current.status, isActive: (input.status ?? current.status) !== "INACTIVE" }; fixtureWarehouses = fixtureWarehouses.map((item) => item.id === id ? next : item); return next; }
    return adaptWarehouse((await fetchJson(`/warehouses/${encodeURIComponent(id)}`, { method: "PATCH", body: JSON.stringify(warehouseInputBody(input)) })) as RawWarehouse);
  },
  async listCities() { if (!baseUrl()) { await wait(); return fixtureCities; } const payload = await fetchJson("/cities"); return Array.isArray(payload) ? (payload as LocationCity[]).map((city) => ({ id: String(city.id), name: city.name })) : []; },
  async listLocations(warehouseId) {
    if (!baseUrl()) {
      await wait();
      return fixtureLocations
        .filter((location) => location.warehouseId === warehouseId)
        .sort((a, b) => a.sortOrder - b.sortOrder)
        .map((location) => ({ ...location, products: fixtureAssignments.filter((assignment) => assignment.warehouseId === warehouseId && assignment.location.id === location.id).map((assignment) => fixtureProducts.find((product) => product.id === assignment.productId) ?? { id: assignment.productId, name: assignment.productId }), stock: fixtureLocationStock(warehouseId, location) }));
    }
    const payload = await fetchJson(`/warehouses/${encodeURIComponent(warehouseId)}/locations`);
    return Array.isArray(payload) ? (payload as RawLocation[]).map(adaptLocationWithProducts) : [];
  },
  async createLocation(warehouseId, input) {
    if (!baseUrl()) { await wait(); const next = { ...inputBody(input), id: `loc-${crypto.randomUUID()}`, warehouseId, sortOrder: input.sortOrder ?? 0, isActive: input.isActive ?? true, status: input.status ?? "ACTIVE", capacity: input.capacity ?? null, capacityUnit: input.capacityUnit ?? null, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() }; fixtureLocations = [...fixtureLocations, next]; return next; }
    return adaptLocation((await fetchJson(`/warehouses/${encodeURIComponent(warehouseId)}/locations`, { method: "POST", body: JSON.stringify(inputBody(input)) })) as RawLocation);
  },
  async updateLocation(id, input) {
    if (!baseUrl()) { await wait(); const current = fixtureLocations.find((location) => location.id === id); if (!current) throw new Error("La ubicación ya no está disponible."); const next = { ...current, ...inputBody(input), sortOrder: input.sortOrder ?? current.sortOrder, isActive: input.isActive ?? current.isActive, status: input.status ?? current.status, capacity: input.capacity ?? current.capacity, capacityUnit: input.capacityUnit ?? current.capacityUnit, updatedAt: new Date().toISOString() }; fixtureLocations = fixtureLocations.map((location) => location.id === id ? next : location); fixtureAssignments = fixtureAssignments.map((assignment) => assignment.location.id === id ? { ...assignment, location: next } : assignment); return next; }
    return adaptLocation((await fetchJson(`/picking/locations/${encodeURIComponent(id)}`, { method: "PATCH", body: JSON.stringify(inputBody(input)) })) as RawLocation);
  },
  async searchProducts(query) {
    if (!baseUrl()) { await wait(); const normalized = query.trim().toLocaleLowerCase("es-AR"); return fixtureProducts.filter((product) => [product.name, product.slug, product.sku, product.barcode].some((value) => value?.toLocaleLowerCase("es-AR").includes(normalized))); }
    const payload = await fetchJson(`/products?q=${encodeURIComponent(query)}&pageSize=10`);
    const items = payload && typeof payload === "object" && Array.isArray((payload as { items?: unknown }).items) ? (payload as { items: RawLocationProduct[] }).items : [];
    return items.map(adaptProduct);
  },
  async getProductLocation(warehouseId, productId) {
    if (!baseUrl()) { await wait(); return fixtureAssignments.find((assignment) => assignment.productId === productId && assignment.warehouseId === warehouseId) ?? null; }
    try { return adaptAssignment((await fetchJson(`/warehouses/${encodeURIComponent(warehouseId)}/products/${encodeURIComponent(productId)}/location`)) as RawProductLocation); } catch (error) { if (typeof error === "object" && error && (error as { status?: number }).status === 404) return null; throw error; }
  },
  async assignProductLocation(productId, warehouseId, locationId) {
    if (!baseUrl()) { await wait(); const location = fixtureLocations.find((item) => item.id === locationId && item.warehouseId === warehouseId); if (!location) throw new Error("La ubicación ya no está disponible."); const next = { productId, warehouseId, location }; fixtureAssignments = [...fixtureAssignments.filter((assignment) => assignment.productId !== productId || assignment.warehouseId !== warehouseId), next]; return next; }
    return adaptAssignment((await fetchJson(`/products/${encodeURIComponent(productId)}/location`, { method: "PUT", body: JSON.stringify({ warehouseId: Number(warehouseId), locationId: Number(locationId) }) })) as RawProductLocation);
  },
  async clearProductLocation(productId, warehouseId) {
    if (!baseUrl()) { await wait(); fixtureAssignments = fixtureAssignments.filter((assignment) => assignment.productId !== productId || assignment.warehouseId !== warehouseId); return; }
    await fetchJson(`/products/${encodeURIComponent(productId)}/location?warehouseId=${encodeURIComponent(warehouseId)}`, { method: "DELETE" });
  },
  async getLocation(warehouseId, locationId) {
    if (!baseUrl()) { await wait(); const location = fixtureLocations.find((item) => item.id === locationId && item.warehouseId === warehouseId); if (!location) throw new Error("La ubicación no está disponible."); const rows = fixtureStock.filter((item) => item.warehouseId === warehouseId && item.locationId === locationId); const totalQuantity = rows.reduce((sum, item) => sum + item.quantity, 0), reservedQuantity = rows.reduce((sum, item) => sum + item.reservedQuantity, 0); return { location, stats: { productsCount: rows.length, totalQuantity, reservedQuantity, availableQuantity: totalQuantity - reservedQuantity, capacity: location.capacity, capacityUnit: location.capacityUnit, occupancyPercentage: location.capacity ? totalQuantity / location.capacity * 100 : null } }; }
    return (await fetchJson(`/warehouses/${encodeURIComponent(warehouseId)}/locations/${encodeURIComponent(locationId)}`)) as LocationDetailData;
  },
  async getLocationStock(warehouseId, locationId, query = "", page = 1, pageSize = 20) {
    if (!baseUrl()) { await wait(); const normalized = query.toLocaleLowerCase("es-AR"); const all = fixtureStock.filter((row) => row.warehouseId === warehouseId && row.locationId === locationId).map((row) => fixtureItem(warehouseId, locationId, row.productId)).filter((item) => [item.product.name, item.product.slug, item.product.sku, item.product.barcode].some((value) => value?.toLocaleLowerCase("es-AR").includes(normalized))); return { items: all.slice((page - 1) * pageSize, page * pageSize), total: all.length, page, pageSize }; }
    const payload = await fetchJson(`/warehouses/${encodeURIComponent(warehouseId)}/locations/${encodeURIComponent(locationId)}/stock?q=${encodeURIComponent(query)}&page=${page}&pageSize=${pageSize}`) as { items?: Array<{ product: RawLocationProduct & { slug?: string }; quantity: number; reservedQuantity: number; availableQuantity: number }>; total: number; page: number; pageSize: number };
    return { items: (payload.items ?? []).map((item) => ({ product: { id: String(item.product.id), name: item.product.name, slug: item.product.slug }, quantity: item.quantity, reservedQuantity: item.reservedQuantity, availableQuantity: item.availableQuantity })), total: payload.total, page: payload.page, pageSize: payload.pageSize };
  },
  async getWarehouseStock(warehouseId, query = "", page = 1, pageSize = 20) {
    if (!baseUrl()) { await wait(); const normalized = query.trim().toLocaleLowerCase("es-AR"); const all = fixtureStock.filter((row) => row.warehouseId === warehouseId).map((row) => fixtureWarehouseStockItem(warehouseId, row.locationId, row.productId)).filter((item) => [item.product.name, item.product.slug, item.product.sku, item.product.barcode].some((value) => value?.toLocaleLowerCase("es-AR").includes(normalized))).sort((a, b) => a.product.name.localeCompare(b.product.name, "es-AR") || a.location.code.localeCompare(b.location.code, "es-AR")); return { items: all.slice((page - 1) * pageSize, page * pageSize), total: all.length, page, pageSize }; }
    const payload = await fetchJson(`/warehouses/${encodeURIComponent(warehouseId)}/stock?q=${encodeURIComponent(query)}&page=${page}&pageSize=${pageSize}`) as { items?: RawWarehouseStockItem[]; total: number; page: number; pageSize: number };
    return { items: (payload.items ?? []).map((item) => ({ product: adaptProduct(item.product), location: { id: String(item.location.id), code: item.location.code, aisle: item.location.aisle, rack: item.location.rack, level: item.location.level }, quantity: Number(item.quantity), reservedQuantity: Number(item.reservedQuantity), availableQuantity: Number(item.availableQuantity) })), total: payload.total, page: payload.page, pageSize: payload.pageSize };
  },
  async getLocationMovements(warehouseId, locationId, filters = {}) {
    const params = new URLSearchParams(); Object.entries(filters).forEach(([key, value]) => { if (value !== undefined && value !== "") params.set(key, String(value)); });
    if (!baseUrl()) { await wait(); const items = fixtureMovements.filter((item) => item.fromLocationId === locationId || item.toLocationId === locationId); return { items, total: items.length, page: 1, pageSize: 20 } as Paginated<LocationStockMovement>; }
    const payload = await fetchJson(`/warehouses/${encodeURIComponent(warehouseId)}/locations/${encodeURIComponent(locationId)}/movements?${params}`) as { items?: LocationStockMovement[]; total: number; page: number; pageSize: number }; return { items: payload.items ?? [], total: payload.total, page: payload.page, pageSize: payload.pageSize };
  },
  async addLocationStock(warehouseId, locationId, input) { if (!baseUrl()) { await wait(); const row = fixtureStock.find((item) => item.warehouseId === warehouseId && item.locationId === locationId && item.productId === input.productId); if (row) row.quantity += input.quantity; else fixtureStock = [...fixtureStock, { warehouseId, locationId, productId: input.productId, quantity: input.quantity, reservedQuantity: 0 }]; fixtureMovement({ type: "IN", productId: input.productId, fromLocationId: null, toLocationId: locationId, quantity: input.quantity, reference: input.reference ?? null, notes: input.notes ?? null }); return fixtureItem(warehouseId, locationId, input.productId); } return (await fetchJson(`/warehouses/${encodeURIComponent(warehouseId)}/locations/${encodeURIComponent(locationId)}/stock`, { method: "POST", body: JSON.stringify(input) })) as LocationStockItem; },
  async transferLocationStock(warehouseId, locationId, input) { if (!baseUrl()) { await wait(); const source = fixtureStock.find((item) => item.warehouseId === warehouseId && item.locationId === locationId && item.productId === input.productId); if (!source || input.quantity > source.quantity - source.reservedQuantity) throw new Error("La cantidad supera el disponible en origen."); source.quantity -= input.quantity; const target = fixtureStock.find((item) => item.warehouseId === warehouseId && item.locationId === input.toLocationId && item.productId === input.productId); if (target) target.quantity += input.quantity; else fixtureStock = [...fixtureStock, { warehouseId, locationId: input.toLocationId, productId: input.productId, quantity: input.quantity, reservedQuantity: 0 }]; fixtureMovement({ type: "TRANSFER", productId: input.productId, fromLocationId: locationId, toLocationId: input.toLocationId, quantity: input.quantity, reference: input.reference ?? null, notes: input.notes ?? null }); return; } return fetchJson(`/warehouses/${encodeURIComponent(warehouseId)}/locations/${encodeURIComponent(locationId)}/stock/transfer`, { method: "POST", body: JSON.stringify(input) }); },
  async adjustLocationStock(warehouseId, locationId, input) { if (!baseUrl()) { await wait(); const row = fixtureStock.find((item) => item.warehouseId === warehouseId && item.locationId === locationId && item.productId === input.productId); if (!row) throw new Error("El stock ya no está disponible."); const next = input.mode === "set" ? input.quantity : row.quantity + input.quantity; if (next < row.reservedQuantity) throw new Error("El ajuste no puede dejar menos unidades que las reservadas."); const difference = next - row.quantity; row.quantity = next; fixtureMovement({ type: "ADJUSTMENT", productId: input.productId, fromLocationId: locationId, toLocationId: locationId, quantity: difference, reference: input.reference ?? null, reason: input.reason, notes: input.notes ?? null }); return fixtureItem(warehouseId, locationId, input.productId); } return (await fetchJson(`/warehouses/${encodeURIComponent(warehouseId)}/locations/${encodeURIComponent(locationId)}/stock/adjust`, { method: "POST", body: JSON.stringify(input) })) as LocationStockItem; },
  async removeLocationStock(warehouseId, locationId, productId) { if (!baseUrl()) { await wait(); const row = fixtureStock.find((item) => item.warehouseId === warehouseId && item.locationId === locationId && item.productId === productId); if (!row) return; if (row.quantity > 0 || row.reservedQuantity > 0) throw new Error("No se puede quitar un producto con stock o reservas. Movelo o ajustalo a cero primero."); fixtureStock = fixtureStock.filter((item) => item !== row); return; } await fetchJson(`/warehouses/${encodeURIComponent(warehouseId)}/locations/${encodeURIComponent(locationId)}/stock/${encodeURIComponent(productId)}`, { method: "DELETE" }); },
};
