import type { Price, PriceApi, PriceFilters, PriceUpdateInput } from "./price-contract";
const wait = () => new Promise<void>((resolve) => setTimeout(resolve, 250));
let prices: Price[] = [
  { productId: "prd-001", productName: "Agua mineral sin gas 1,5 L", sku: "SUP-0001", category: "Bebidas", active: true, amount: 1250, currency: "ARS", updatedAt: "2026-09-04T12:00:00.000Z", updatedBy: "María González", history: [{ id: "pch-003", previousAmount: 1100, amount: 1250, changedAt: "2026-09-04T12:00:00.000Z", changedBy: "María González", reason: "Ajuste de lista septiembre" }, { id: "pch-001", previousAmount: null, amount: 1100, changedAt: "2026-08-01T09:00:00.000Z", changedBy: "Juan Fernández" }] },
  { productId: "prd-002", productName: "Yerba mate tradicional 500 g", sku: "CAM-0002", category: "Almacén", active: true, amount: 3400, currency: "ARS", updatedAt: "2026-09-03T15:30:00.000Z", updatedBy: "María González", history: [{ id: "pch-004", previousAmount: 3100, amount: 3400, changedAt: "2026-09-03T15:30:00.000Z", changedBy: "María González", reason: "Actualización proveedor" }] },
  { productId: "prd-003", productName: "Jugo de naranja 1 L", sku: "NAT-0003", category: "Bebidas", active: false, amount: 2150, currency: "ARS", updatedAt: "2026-08-30T09:10:00.000Z", updatedBy: "Juan Fernández", history: [{ id: "pch-005", previousAmount: 2000, amount: 2150, changedAt: "2026-08-30T09:10:00.000Z", changedBy: "Juan Fernández" }] },
];
function missing() { return new Error("Uno de los productos ya no está disponible. Actualizá el listado e intentá nuevamente."); }
/** Mock temporal hasta BE-007. Reemplazar por GET /api/prices y PUT /api/prices; no tiene persistencia real. */
export const priceApi: PriceApi = {
  async listPrices(filters: PriceFilters = {}) { await wait(); const query = filters.query?.trim().toLocaleLowerCase("es-AR") ?? ""; return prices.filter((price) => (!query || [price.productName, price.sku].some((value) => value.toLocaleLowerCase("es-AR").includes(query))) && (!filters.category || price.category === filters.category) && (!filters.status || filters.status === "all" || (filters.status === "active" ? price.active : !price.active))); },
  async updatePrices(input: PriceUpdateInput) { await wait(); if (!input.productIds.length || !Number.isFinite(input.amount) || input.amount < 0) throw new Error("El precio informado no es válido."); if (input.productIds.some((id) => !prices.some((price) => price.productId === id))) throw missing(); const changedAt = new Date().toISOString(); const changed = new Map<string, Price>(); prices = prices.map((price) => { if (!input.productIds.includes(price.productId)) return price; const next: Price = { ...price, amount: input.amount, updatedAt: changedAt, updatedBy: input.changedBy, history: [{ id: `pch-${crypto.randomUUID()}`, previousAmount: price.amount, amount: input.amount, changedAt, changedBy: input.changedBy, ...(input.reason?.trim() ? { reason: input.reason.trim() } : {}) }, ...price.history] }; changed.set(next.productId, next); return next; }); return input.productIds.map((id) => changed.get(id) as Price); },
};
