import { authHeaders } from "@/app/lib/auth-api";
import type { CreatePurchaseOrderDto, PaginatedPurchaseOrders, PurchaseOrder, PurchaseOrderApi, PurchaseOrderEvent, PurchaseOrderItem, PurchaseOrderProduct, PurchaseOrderSummary, UpdatePurchaseOrderDto } from "./purchase-order-contract";
import { previewPurchaseOrderLine } from "./purchase-order-rules";

const wait = () => new Promise<void>((resolve) => setTimeout(resolve, 250));
const baseUrl = () => process.env.NEXT_PUBLIC_SUPERX_API_BASE_URL;
const products: PurchaseOrderProduct[] = [{ id: "prd-001", name: "Agua mineral sin gas 1,5 L", slug: "agua-mineral-sin-gas-1-5-l" }, { id: "prd-002", name: "Yerba mate tradicional 500 g", slug: "yerba-mate-tradicional-500-g" }, { id: "prd-003", name: "Jugo de naranja 1 L", slug: "jugo-de-naranja-1-l" }];
const suppliers = [{ id: "sup-001", name: "Distribuidora Río Plata" }, { id: "sup-002", name: "Alimentos del Sur" }];
const warehouses = [{ id: "wh-central", name: "Depósito central" }, { id: "wh-norte", name: "Sucursal Norte" }];
const packagings = [{ id: "pack-001", productId: "prd-001", supplierId: "sup-001", name: "Fardo x 6", unitsPerPack: 6, isActive: true }, { id: "pack-002", productId: "prd-002", supplierId: "sup-001", name: "Caja x 12", unitsPerPack: 12, isActive: true }];
let orders: PurchaseOrder[] = [];

type RawOrder = Record<string, unknown>;
const asString = (value: unknown) => String(value ?? "");
const asNumber = (value: unknown) => Number(value ?? 0);
const adaptProduct = (raw: unknown): PurchaseOrderProduct => { const item = (raw ?? {}) as Record<string, unknown>; return { id: asString(item.id), name: asString(item.name), slug: asString(item.slug) }; };
const adaptSummary = (raw: RawOrder): PurchaseOrderSummary => ({ id: asString(raw.id), supplierId: asString(raw.supplierId), warehouseId: asString(raw.warehouseId), status: (raw.status as PurchaseOrderSummary["status"]) ?? "DRAFT", receiptStatus: (raw.receiptStatus as PurchaseOrderSummary["receiptStatus"]) ?? "NOT_RECEIVED", expectedDate: raw.expectedDate == null ? null : asString(raw.expectedDate), reference: raw.reference == null ? null : asString(raw.reference), notes: raw.notes == null ? null : asString(raw.notes), createdAt: asString(raw.createdAt), updatedAt: asString(raw.updatedAt), total: asNumber(raw.total), itemCount: asNumber(raw.itemCount), supplier: { id: asString((raw.supplier as RawOrder | undefined)?.id ?? raw.supplierId), name: asString((raw.supplier as RawOrder | undefined)?.name) }, warehouse: { id: asString((raw.warehouse as RawOrder | undefined)?.id ?? raw.warehouseId), name: asString((raw.warehouse as RawOrder | undefined)?.name) } });
const adaptItem = (raw: RawOrder): PurchaseOrderItem => ({ id: asString(raw.id), productId: asString(raw.productId), packagingId: raw.packagingId == null ? null : asString(raw.packagingId), product: adaptProduct(raw.product), packagingName: asString(raw.packagingName), unitsPerPack: asNumber(raw.unitsPerPack), packageQuantity: asNumber(raw.packageQuantity), unitQuantity: asNumber(raw.unitQuantity), costPerPackage: asNumber(raw.costPerPackage), unitCost: asNumber(raw.unitCost), total: asNumber(raw.total), receivedPackageQuantity: asNumber(raw.receivedPackageQuantity), receivedUnitQuantity: asNumber(raw.receivedUnitQuantity) });
const adaptOrder = (raw: RawOrder): PurchaseOrder => ({ ...adaptSummary(raw), items: Array.isArray(raw.items) ? raw.items.map((item) => adaptItem(item as RawOrder)) : [], events: Array.isArray(raw.events) ? raw.events as PurchaseOrderEvent[] : [] });
const body = (input: Partial<CreatePurchaseOrderDto>) => ({ ...(input.supplierId === undefined ? {} : { supplierId: input.supplierId }), ...(input.warehouseId === undefined ? {} : { warehouseId: input.warehouseId }), ...(input.expectedDate === undefined ? {} : { expectedDate: input.expectedDate || undefined }), ...(input.reference === undefined ? {} : { reference: input.reference?.trim() || undefined }), ...(input.notes === undefined ? {} : { notes: input.notes?.trim() || undefined }), ...(input.items === undefined ? {} : { items: input.items.map((item) => ({ productId: item.productId, ...(item.packagingId ? { packagingId: item.packagingId } : { packagingName: item.packagingName?.trim(), unitsPerPack: item.unitsPerPack }), packageQuantity: Number(item.packageQuantity), costPerPackage: Number(item.costPerPackage) })) }) });
async function fetchJson(path: string, init: RequestInit = {}) { const response = await fetch(`${baseUrl()!.replace(/\/$/, "")}${path}`, { ...init, headers: { Accept: "application/json", ...(init.body ? { "Content-Type": "application/json" } : {}), ...authHeaders(), ...init.headers } }); const payload: unknown = response.status === 204 ? undefined : await response.json().catch(() => undefined); if (!response.ok) { const message = payload && typeof payload === "object" && typeof (payload as { message?: unknown }).message === "string" ? (payload as { message: string }).message : "No pudimos completar la operación."; throw Object.assign(new Error(response.status === 401 || response.status === 403 ? "No tenés permiso para gestionar compras." : message), { status: response.status }); } return payload; }
function fixtureOrder(input: CreatePurchaseOrderDto, id = `po-${crypto.randomUUID()}`, existing?: PurchaseOrder): PurchaseOrder { const now = new Date().toISOString(); const supplier = suppliers.find((item) => item.id === input.supplierId) ?? { id: input.supplierId, name: "Proveedor" }; const warehouse = warehouses.find((item) => item.id === input.warehouseId) ?? { id: input.warehouseId, name: "Depósito" }; const items = input.items.map((inputItem, index) => { const packaging = packagings.find((item) => item.id === inputItem.packagingId); const presentation = packaging?.name ?? inputItem.packagingName ?? "Presentación"; const unitsPerPack = packaging?.unitsPerPack ?? Number(inputItem.unitsPerPack); const preview = previewPurchaseOrderLine({ packageQuantity: inputItem.packageQuantity, unitsPerPack, costPerPackage: inputItem.costPerPackage }); return { id: `${id}-line-${index + 1}`, productId: inputItem.productId, packagingId: packaging?.id ?? null, product: products.find((item) => item.id === inputItem.productId) ?? { id: inputItem.productId, name: "Producto", slug: "" }, packagingName: presentation, unitsPerPack, packageQuantity: Number(inputItem.packageQuantity), ...preview, costPerPackage: Number(inputItem.costPerPackage), receivedPackageQuantity: 0, receivedUnitQuantity: 0 }; }); const status = existing?.status ?? "DRAFT"; return { id, supplierId: input.supplierId, warehouseId: input.warehouseId, status, receiptStatus: "NOT_RECEIVED", expectedDate: input.expectedDate || null, reference: input.reference?.trim() || null, notes: input.notes?.trim() || null, createdAt: existing?.createdAt ?? now, updatedAt: now, total: items.reduce((sum, item) => sum + item.total, 0), itemCount: items.length, supplier, warehouse, items, events: existing?.events ?? [{ id: `${id}-created`, type: "CREATED", actorUserId: "fixture-admin", note: null, createdAt: now }] }; }

export const purchaseOrderApi: PurchaseOrderApi = {
  async list(filters = {}) { if (!baseUrl()) { await wait(); const all = orders.filter((item) => (!filters.supplierId || item.supplierId === filters.supplierId) && (!filters.warehouseId || item.warehouseId === filters.warehouseId) && (!filters.status || item.status === filters.status)); const page = filters.page ?? 1, pageSize = filters.pageSize ?? 50; return { items: all.slice((page - 1) * pageSize, page * pageSize), total: all.length, page, pageSize }; } const params = new URLSearchParams({ page: String(filters.page ?? 1), pageSize: String(filters.pageSize ?? 50) }); if (filters.supplierId) params.set("supplierId", filters.supplierId); if (filters.warehouseId) params.set("warehouseId", filters.warehouseId); if (filters.status) params.set("status", filters.status); const payload = await fetchJson(`/purchase-orders?${params}`) as { items?: RawOrder[]; total?: number; page?: number; pageSize?: number }; return { items: (payload.items ?? []).map(adaptSummary), total: Number(payload.total ?? 0), page: Number(payload.page ?? 1), pageSize: Number(payload.pageSize ?? 50) } satisfies PaginatedPurchaseOrders; },
  async get(id) { if (!baseUrl()) { await wait(); const order = orders.find((item) => item.id === id); if (!order) throw new Error("La orden de compra ya no está disponible."); return order; } return adaptOrder((await fetchJson(`/purchase-orders/${encodeURIComponent(id)}`)) as RawOrder); },
  async create(input) { if (!baseUrl()) { await wait(); const order = fixtureOrder(input); orders = [order, ...orders]; return order; } return adaptOrder((await fetchJson("/purchase-orders", { method: "POST", body: JSON.stringify(body(input)) })) as RawOrder); },
  async update(id, input: UpdatePurchaseOrderDto) { if (!baseUrl()) { await wait(); const current = orders.find((item) => item.id === id); if (!current) throw new Error("La orden de compra ya no está disponible."); if (current.status !== "DRAFT") throw new Error("Sólo se puede editar una orden en borrador."); const next = fixtureOrder({ supplierId: input.supplierId ?? current.supplierId, warehouseId: input.warehouseId ?? current.warehouseId, expectedDate: input.expectedDate ?? current.expectedDate ?? undefined, reference: input.reference ?? current.reference ?? undefined, notes: input.notes ?? current.notes ?? undefined, items: input.items ?? current.items.map((item) => ({ productId: item.productId, packagingId: item.packagingId ?? undefined, packagingName: item.packagingName, unitsPerPack: item.unitsPerPack, packageQuantity: item.packageQuantity, costPerPackage: item.costPerPackage })) }, id, current); next.events = [...current.events, { id: `${id}-updated-${Date.now()}`, type: "UPDATED", actorUserId: "fixture-admin", note: null, createdAt: next.updatedAt }]; orders = orders.map((item) => item.id === id ? next : item); return next; } return adaptOrder((await fetchJson(`/purchase-orders/${encodeURIComponent(id)}`, { method: "PATCH", body: JSON.stringify(body(input)) })) as RawOrder); },
  async confirm(id) { if (!baseUrl()) { await wait(); const order = await this.get(id); if (order.status !== "DRAFT" || !order.items.length) throw new Error("La orden no se puede confirmar."); const next = { ...order, status: "CONFIRMED" as const, updatedAt: new Date().toISOString(), events: [...order.events, { type: "CONFIRMED" as const, actorUserId: "fixture-admin", note: null, createdAt: new Date().toISOString() }] }; orders = orders.map((item) => item.id === id ? next : item); return next; } return adaptOrder((await fetchJson(`/purchase-orders/${encodeURIComponent(id)}/confirm`, { method: "POST" })) as RawOrder); },
  async cancel(id) { if (!baseUrl()) { await wait(); const order = await this.get(id); if (order.status !== "DRAFT" && order.status !== "CONFIRMED") throw new Error("La orden no se puede cancelar."); const next = { ...order, status: "CANCELLED" as const, updatedAt: new Date().toISOString(), events: [...order.events, { type: "CANCELLED" as const, actorUserId: "fixture-admin", note: null, createdAt: new Date().toISOString() }] }; orders = orders.map((item) => item.id === id ? next : item); return next; } return adaptOrder((await fetchJson(`/purchase-orders/${encodeURIComponent(id)}/cancel`, { method: "POST" })) as RawOrder); },
  async searchProducts(query) { if (!baseUrl()) { await wait(); const normalized = query.trim().toLocaleLowerCase("es-AR"); return products.filter((item) => !normalized || [item.name, item.slug].some((value) => value.toLocaleLowerCase("es-AR").includes(normalized))); } const payload = await fetchJson(`/products?q=${encodeURIComponent(query)}&pageSize=10`) as { items?: RawOrder[] }; return (payload.items ?? []).map(adaptProduct); },
  async listPackagings(productId, supplierId) { if (!baseUrl()) { await wait(); return packagings.filter((item) => item.productId === productId && item.supplierId === supplierId); } const payload = await fetchJson(`/products/${encodeURIComponent(productId)}/purchase-packagings?supplierId=${encodeURIComponent(supplierId)}`); const items = Array.isArray(payload) ? payload : (payload as { items?: unknown[] })?.items ?? []; return items.map((item) => { const raw = item as RawOrder; return { id: asString(raw.id), name: asString(raw.name), unitsPerPack: asNumber(raw.unitsPerPack), isActive: raw.isActive !== false }; }); },
};
