import { authFetch } from "./http";
import type { ReceivingApi, ReceivingDetail, ReceivingFilters, ReceivingHeader, ReceivingPage, ValidateReceivingInput } from "./receiving-contract";

const baseUrl = () => process.env.NEXT_PUBLIC_SUPERX_API_BASE_URL;
const wait = () => new Promise<void>((resolve) => setTimeout(resolve, 220));
export class ReceivingApiError extends Error { constructor(message: string, readonly status?: number, readonly code?: string) { super(message); this.name = "ReceivingApiError"; } }
const messageOf = (payload: unknown) => { const message = payload && typeof payload === "object" ? (payload as { message?: unknown }).message : undefined; return typeof message === "string" ? message : Array.isArray(message) ? message.filter((part): part is string => typeof part === "string").join(" ") : "No pudimos completar la operación."; };
async function request(path: string, init: RequestInit = {}) { const response = await authFetch(`${baseUrl()!.replace(/\/$/, "")}${path}`, { ...init, headers: { Accept: "application/json", ...(init.body ? { "Content-Type": "application/json" } : {}), ...init.headers } }); const payload: unknown = await response.json().catch(() => undefined); if (!response.ok) { if (response.status === 401) throw new ReceivingApiError("Iniciá sesión para trabajar en depósito.", 401, "unauthenticated"); if (response.status === 403) throw new ReceivingApiError("Tu cuenta no tiene acceso a Depósito.", 403, "forbidden"); throw new ReceivingApiError(messageOf(payload), response.status, response.status === 409 ? "conflict" : "request_failed"); } return payload; }

const now = new Date();
const fixture: ReceivingDetail[] = [
  { purchaseOrderId: "po-receiving-1", number: "OC-000184", supplier: { id: "sup-1", name: "Distribuidora Río Plata" }, warehouse: { id: "wh-1", name: "Depósito central" }, expectedDate: new Date(now.getTime() - 86400000).toISOString(), orderDate: now.toISOString(), receiptStatus: "NOT_RECEIVED", lineCount: 2, pendingPackages: 10, pendingUnits: 84, isLate: true, locations: [{ id: "loc-1", code: "A-01-01" }, { id: "loc-2", code: "A-02-03" }], previousReceipts: [], lines: [
    { purchaseOrderItemId: "line-1", product: { id: "prd-1", name: "Yerba mate tradicional 500 g", slug: "yerba-mate", barcodes: ["7791234567891"] }, packagingName: "Caja x12", unitsPerPack: 12, packagingBarcode: "17791234567898", orderedPackages: 6, orderedUnits: 72, receivedPackages: 0, receivedUnits: 0, pendingPackages: 6, pendingUnits: 72, suggestedLocationId: "loc-1" },
    { purchaseOrderItemId: "line-2", product: { id: "prd-2", name: "Agua mineral sin gas 1,5 L", slug: "agua-mineral", barcodes: ["7791234567890"] }, packagingName: "Fardo x3", unitsPerPack: 3, orderedPackages: 4, orderedUnits: 12, receivedPackages: 0, receivedUnits: 0, pendingPackages: 4, pendingUnits: 12, suggestedLocationId: "loc-1" },
  ] },
  { purchaseOrderId: "po-receiving-2", number: "OC-000181", supplier: { id: "sup-2", name: "Alimentos del Sur" }, warehouse: { id: "wh-2", name: "Sucursal Norte" }, expectedDate: now.toISOString(), orderDate: now.toISOString(), receiptStatus: "PARTIALLY_RECEIVED", lineCount: 1, pendingPackages: 3, pendingUnits: 36, isLate: false, locations: [{ id: "loc-3", code: "B-01-02" }], previousReceipts: [], lines: [{ purchaseOrderItemId: "line-3", product: { id: "prd-3", name: "Galletitas de agua 300 g", slug: "galletitas", barcodes: ["7790000000001"] }, packagingName: "Caja x12", unitsPerPack: 12, orderedPackages: 8, orderedUnits: 96, receivedPackages: 5, receivedUnits: 60, pendingPackages: 3, pendingUnits: 36, suggestedLocationId: "loc-3" }] },
];
const clone = <T,>(value: T): T => structuredClone(value);
const header = (detail: ReceivingDetail): ReceivingHeader => { const item: Partial<ReceivingDetail> = { ...detail }; delete item.lines; delete item.locations; delete item.previousReceipts; return item as ReceivingHeader; };

export const receivingApi: ReceivingApi = {
  async list(filters: ReceivingFilters = {}): Promise<ReceivingPage> { if (!baseUrl()) { await wait(); const needle = filters.q?.trim().toLocaleLowerCase("es-AR") ?? ""; const items = fixture.filter((item) => (!filters.warehouseId || item.warehouse.id === filters.warehouseId) && (filters.status === "all" || !filters.status || (filters.status === "pending" ? item.receiptStatus === "NOT_RECEIVED" : item.receiptStatus === "PARTIALLY_RECEIVED")) && (!needle || `${item.number} ${item.supplier.name}`.toLocaleLowerCase("es-AR").includes(needle))).map(header); return { items: clone(items), total: items.length, page: 1, pageSize: 20 }; } const params = new URLSearchParams(); Object.entries(filters).forEach(([key, value]) => { if (value !== undefined && value !== "") params.set(key, String(value)); }); return request(`/receiving?${params}`) as Promise<ReceivingPage>; },
  async detail(id) { if (!baseUrl()) { await wait(); const found = fixture.find((item) => item.purchaseOrderId === id); if (!found) throw new ReceivingApiError("La recepción ya no está disponible.", 404); return clone(found); } return request(`/receiving/${encodeURIComponent(id)}`) as Promise<ReceivingDetail>; },
  async validate(id, input: ValidateReceivingInput) { if (!baseUrl()) { await wait(); const index = fixture.findIndex((item) => item.purchaseOrderId === id); if (index < 0) throw new ReceivingApiError("La recepción ya no está disponible.", 404); const current = fixture[index]; const lines = current.lines.map((line) => { const entry = input.items.find((item) => item.purchaseOrderItemId === line.purchaseOrderItemId); const accepted = Math.max(0, (entry?.packageQuantity ?? 0) - (entry?.rejectedPackageQuantity ?? 0)); return { ...line, receivedPackages: line.receivedPackages + accepted, receivedUnits: line.receivedUnits + accepted * line.unitsPerPack, pendingPackages: Math.max(0, line.pendingPackages - accepted), pendingUnits: Math.max(0, line.pendingUnits - accepted * line.unitsPerPack) }; }); const pendingPackages = lines.reduce((sum, line) => sum + line.pendingPackages, 0); const next = { ...current, lines, pendingPackages, pendingUnits: lines.reduce((sum, line) => sum + line.pendingUnits, 0), receiptStatus: pendingPackages ? "PARTIALLY_RECEIVED" as const : "RECEIVED" as const }; fixture[index] = next; return clone(next); } return request(`/receiving/${encodeURIComponent(id)}/validate`, { method: "POST", body: JSON.stringify(input) }) as Promise<ReceivingDetail>; },
};
