import { authFetch } from "@/app/lib/http";
import type { PaginatedSupplierMovements, PaginatedSuppliers, PurchasePackaging, PurchasePackagingInput, Supplier, SupplierAccount, SupplierApi, SupplierBalance, SupplierEvent, SupplierInput, SupplierMovementType, SupplierProduct, UpdateSupplierDto } from "./supplier-contract";

const wait = () => new Promise<void>((resolve) => setTimeout(resolve, 250));
const baseUrl = () => process.env.NEXT_PUBLIC_SUPERX_API_BASE_URL;
const now = () => new Date().toISOString();

let suppliers: Supplier[] = [
  { id: "sup-001", name: "Distribuidora Río Plata", legalName: "Distribuidora Río Plata S.A.", taxId: "30-71234567-1", contactName: "María López", phone: "+54 11 4555-0101", email: "ventas@rioplata.test", address: "Av. Rivadavia 2450, CABA", paymentTermDays: 30, paymentCondition: "CREDIT", status: "ACTIVE", notes: "Entrega lunes, miércoles y viernes.", createdAt: "2026-09-01T10:00:00.000Z", updatedAt: "2026-09-01T10:00:00.000Z" },
  { id: "sup-002", name: "Alimentos del Sur", legalName: null, taxId: "30-69876543-1", contactName: "Juan Pérez", phone: "+54 221 440-2200", email: "compras@alsur.test", address: "Ruta 2 km 52, La Plata", paymentTermDays: 15, paymentCondition: "CREDIT", status: "ACTIVE", notes: null, createdAt: "2026-09-02T10:00:00.000Z", updatedAt: "2026-09-02T10:00:00.000Z" },
  { id: "sup-003", name: "Comercial Norte", legalName: null, taxId: null, contactName: null, phone: null, email: null, address: null, paymentTermDays: null, paymentCondition: "CREDIT", status: "INACTIVE", notes: "Cuenta suspendida.", createdAt: "2026-09-03T10:00:00.000Z", updatedAt: "2026-09-03T10:00:00.000Z" },
];
const products: SupplierProduct[] = [
  { id: "prd-001", name: "Agua mineral sin gas 1,5 L", slug: "agua-mineral-sin-gas-1-5-l" },
  { id: "prd-002", name: "Yerba mate tradicional 500 g", slug: "yerba-mate-tradicional-500-g" },
  { id: "prd-003", name: "Jugo de naranja 1 L", slug: "jugo-de-naranja-1-l" },
];
let packagings: PurchasePackaging[] = [
  { id: "pack-001", productId: "prd-001", supplierId: "sup-001", supplier: { id: "sup-001", name: "Distribuidora Río Plata" }, product: products[0], name: "Fardo x 6", unitsPerPack: 6, barcode: "7791234567890", supplierCode: "RP-AG-6", isDefault: true, isActive: true, createdAt: "2026-09-01T10:00:00.000Z", updatedAt: "2026-09-01T10:00:00.000Z" },
  { id: "pack-002", productId: "prd-002", supplierId: "sup-001", supplier: { id: "sup-001", name: "Distribuidora Río Plata" }, product: products[1], name: "Caja x 12", unitsPerPack: 12, barcode: null, supplierCode: "RP-YE-12", isDefault: false, isActive: true, createdAt: "2026-09-01T10:00:00.000Z", updatedAt: "2026-09-01T10:00:00.000Z" },
];

type RawSupplier = Omit<Supplier, "id" | "legalName" | "taxId" | "contactName" | "phone" | "email" | "address" | "paymentTermDays" | "paymentCondition" | "notes"> & { id: string | number; legalName?: string | null; taxId?: string | null; contactName?: string | null; phone?: string | null; email?: string | null; address?: string | null; paymentTermDays?: number | null; paymentCondition?: Supplier["paymentCondition"]; notes?: string | null };
type RawPackaging = Omit<PurchasePackaging, "id" | "productId" | "supplierId" | "product" | "barcode" | "supplierCode"> & { id: string | number; productId: string | number; supplierId?: string | number | null; product?: { id: string | number; name: string; slug?: string }; barcode?: string | null; supplierCode?: string | null };
const adaptSupplier = (raw: RawSupplier): Supplier => ({ ...raw, id: String(raw.id), legalName: raw.legalName ?? null, taxId: raw.taxId ?? null, contactName: raw.contactName ?? null, phone: raw.phone ?? null, email: raw.email ?? null, address: raw.address ?? null, paymentTermDays: raw.paymentTermDays ?? null, paymentCondition: raw.paymentCondition ?? "CREDIT", notes: raw.notes ?? null });
const adaptPackaging = (raw: RawPackaging): PurchasePackaging => ({ ...raw, id: String(raw.id), productId: String(raw.productId), supplierId: raw.supplierId == null ? null : String(raw.supplierId), product: { id: String(raw.product?.id ?? raw.productId), name: raw.product?.name ?? "Producto", slug: raw.product?.slug ?? "" }, barcode: raw.barcode ?? null, supplierCode: raw.supplierCode ?? null });
const clean = (value: string | undefined) => value?.trim() || undefined;
const supplierBody = (input: Partial<SupplierInput>) => ({ ...(input.name === undefined ? {} : { name: input.name.trim() }), ...(input.legalName === undefined ? {} : { legalName: clean(input.legalName) }), ...(input.taxId === undefined ? {} : { taxId: clean(input.taxId) }), ...(input.contactName === undefined ? {} : { contactName: clean(input.contactName) }), ...(input.phone === undefined ? {} : { phone: clean(input.phone) }), ...(input.email === undefined ? {} : { email: clean(input.email) }), ...(input.address === undefined ? {} : { address: clean(input.address) }), ...(input.paymentTermDays === undefined ? {} : { paymentTermDays: input.paymentTermDays }), ...(input.paymentCondition === undefined ? {} : { paymentCondition: input.paymentCondition }), ...(input.status === undefined ? {} : { status: input.status }), ...(input.notes === undefined ? {} : { notes: clean(input.notes) }) });
const packagingBody = (input: Partial<PurchasePackagingInput>) => ({ ...(input.supplierId === undefined ? {} : { supplierId: input.supplierId }), ...(input.name === undefined ? {} : { name: input.name.trim() }), ...(input.unitsPerPack === undefined ? {} : { unitsPerPack: input.unitsPerPack }), ...(input.barcode === undefined ? {} : { barcode: clean(input.barcode) }), ...(input.supplierCode === undefined ? {} : { supplierCode: clean(input.supplierCode) }), ...(input.isDefault === undefined ? {} : { isDefault: input.isDefault }), ...(input.isActive === undefined ? {} : { isActive: input.isActive }) });

async function fetchJson(path: string, init: RequestInit = {}): Promise<unknown> {
  const response = await authFetch(`${baseUrl()!.replace(/\/$/, "")}${path}`, { ...init, headers: { Accept: "application/json", ...(init.body ? { "Content-Type": "application/json" } : {}), ...init.headers } });
  const payload: unknown = response.status === 204 ? undefined : await response.json().catch(() => undefined);
  if (!response.ok) {
    const message = payload && typeof payload === "object" && typeof (payload as { message?: unknown }).message === "string" ? (payload as { message: string }).message : "No pudimos completar la operación.";
    throw Object.assign(new Error(response.status === 401 || response.status === 403 ? "No tenés permiso para gestionar proveedores." : message), { status: response.status });
  }
  return payload;
}

export const supplierApi: SupplierApi = {
  async listSuppliers(filters = {}) {
    if (!baseUrl()) { await wait(); const query = filters.q?.trim().toLocaleLowerCase("es-AR") ?? ""; const matches = suppliers.filter((item) => (!filters.status || item.status === filters.status) && (!query || [item.name, item.taxId, item.contactName, item.email].some((value) => value?.toLocaleLowerCase("es-AR").includes(query)))); const page = filters.page ?? 1, pageSize = filters.pageSize ?? 20; return { items: matches.slice((page - 1) * pageSize, page * pageSize), total: matches.length, page, pageSize }; }
    const params = new URLSearchParams({ q: filters.q ?? "", page: String(filters.page ?? 1), pageSize: String(filters.pageSize ?? 20) }); if (filters.status) params.set("status", filters.status);
    const payload = await fetchJson(`/suppliers?${params}`) as { items?: RawSupplier[]; total?: number; page?: number; pageSize?: number };
    return { items: (payload.items ?? []).map(adaptSupplier), total: Number(payload.total ?? 0), page: Number(payload.page ?? 1), pageSize: Number(payload.pageSize ?? 20) } satisfies PaginatedSuppliers;
  },
  async getSupplier(id) { if (!baseUrl()) { await wait(); const supplier = suppliers.find((item) => item.id === id); if (!supplier) throw new Error("El proveedor ya no está disponible."); return { ...supplier, purchasePackagings: packagings.filter((item) => item.supplierId === id) }; } const raw = await fetchJson(`/suppliers/${encodeURIComponent(id)}`) as RawSupplier & { purchasePackagings?: RawPackaging[] }; return { ...adaptSupplier(raw), purchasePackagings: (raw.purchasePackagings ?? []).map(adaptPackaging) }; },
  async balances(supplierIds) {
    if (!supplierIds.length) return [];
    if (!baseUrl()) { await wait(); return supplierIds.map((supplierId) => ({ supplierId, currency: "ARS", openBalance: "0.00", overdueBalance: "0.00", advanceBalance: "0.00" })); }
    const payload = await fetchJson(`/suppliers/balances?supplierIds=${encodeURIComponent(supplierIds.join(","))}`);
    const rows = Array.isArray(payload) ? payload : (payload as { items?: unknown[] })?.items ?? [];
    return rows.map((row) => { const raw = row as Record<string, unknown>; return { supplierId: String(raw.supplierId ?? ""), currency: String(raw.currency ?? "ARS"), openBalance: String(raw.openBalance ?? "0.00"), overdueBalance: String(raw.overdueBalance ?? "0.00"), advanceBalance: String(raw.advanceBalance ?? "0.00") }; }) satisfies SupplierBalance[];
  },
  async account(id) {
    if (!baseUrl()) { await wait(); return { supplierId: id, currencies: [{ currency: "ARS", totalInvoiced: "0.00", totalPaid: "0.00", openBalance: "0.00", overdueBalance: "0.00", overdueCount: 0, upcoming: { next7: "0.00", next30: "0.00", later: "0.00" }, advanceBalance: "0.00", netBalance: "0.00", openInvoiceCount: 0, paymentCount: 0 }] }; }
    const raw = await fetchJson(`/suppliers/${encodeURIComponent(id)}/account`) as Record<string, unknown>;
    const currencies = Array.isArray(raw.currencies) ? raw.currencies : [];
    return { supplierId: String(raw.supplierId ?? id), currencies: currencies.map((item) => { const value = item as Record<string, unknown>, upcoming = (value.upcoming ?? {}) as Record<string, unknown>; return { currency: String(value.currency ?? "ARS"), totalInvoiced: String(value.totalInvoiced ?? "0.00"), totalPaid: String(value.totalPaid ?? "0.00"), openBalance: String(value.openBalance ?? "0.00"), overdueBalance: String(value.overdueBalance ?? "0.00"), overdueCount: Number(value.overdueCount ?? 0), upcoming: { next7: String(upcoming.next7 ?? "0.00"), next30: String(upcoming.next30 ?? "0.00"), later: String(upcoming.later ?? "0.00") }, advanceBalance: String(value.advanceBalance ?? "0.00"), netBalance: String(value.netBalance ?? "0.00"), openInvoiceCount: Number(value.openInvoiceCount ?? 0), paymentCount: Number(value.paymentCount ?? 0) }; }) } satisfies SupplierAccount;
  },
  async movements(id, filters = {}) {
    if (!baseUrl()) { await wait(); return { items: [], total: 0, page: filters.page ?? 1, pageSize: filters.pageSize ?? 50, currency: filters.currency ?? "ARS", openingBalanceForPeriod: "0.00" }; }
    const params = new URLSearchParams({ currency: filters.currency ?? "ARS", page: String(filters.page ?? 1), pageSize: String(filters.pageSize ?? 50) });
    (["from", "to", "type"] as const).forEach((key) => { if (filters[key]) params.set(key, String(filters[key])); });
    const raw = await fetchJson(`/suppliers/${encodeURIComponent(id)}/movements?${params}`) as Record<string, unknown>;
    const items = Array.isArray(raw.items) ? raw.items : [];
    return { items: items.map((item) => { const value = item as Record<string, unknown>; return { date: String(value.date ?? ""), type: (value.type as SupplierMovementType) ?? "INVOICE", reference: String(value.reference ?? "—"), documentId: String(value.documentId ?? ""), currency: String(value.currency ?? filters.currency ?? "ARS"), debit: String(value.debit ?? "0.00"), credit: String(value.credit ?? "0.00"), runningBalance: String(value.runningBalance ?? "0.00") }; }), total: Number(raw.total ?? 0), page: Number(raw.page ?? 1), pageSize: Number(raw.pageSize ?? 50), currency: String(raw.currency ?? filters.currency ?? "ARS"), openingBalanceForPeriod: String(raw.openingBalanceForPeriod ?? "0.00") } satisfies PaginatedSupplierMovements;
  },
  async events(id) { if (!baseUrl()) { await wait(); return []; } const payload = await fetchJson(`/suppliers/${encodeURIComponent(id)}/events`); const rows = Array.isArray(payload) ? payload : (payload as { items?: unknown[] })?.items ?? []; return rows.map((row) => { const raw = row as Record<string, unknown>; return { id: String(raw.id ?? ""), supplierId: String(raw.supplierId ?? id), type: (raw.type as SupplierEvent["type"]) ?? "UPDATED", actorUserId: String(raw.actorUserId ?? ""), data: raw.data && typeof raw.data === "object" ? raw.data as Record<string, unknown> : null, createdAt: String(raw.createdAt ?? "") }; }); },
  async listPackagings(productId) { if (!baseUrl()) { await wait(); return packagings.filter((item) => item.productId === productId); } const payload = await fetchJson(`/products/${encodeURIComponent(productId)}/purchase-packagings`); const items = Array.isArray(payload) ? payload : (payload as { items?: RawPackaging[] })?.items ?? []; return items.map(adaptPackaging); },
  async createSupplier(input) { if (!baseUrl()) { await wait(); const taxId = clean(input.taxId); if (taxId && suppliers.some((item) => item.taxId === taxId)) throw new Error("Ya existe un proveedor con ese CUIT."); const created: Supplier = { id: `sup-${crypto.randomUUID()}`, name: input.name.trim(), legalName: clean(input.legalName) ?? null, taxId: taxId ?? null, contactName: clean(input.contactName) ?? null, phone: clean(input.phone) ?? null, email: clean(input.email) ?? null, address: clean(input.address) ?? null, paymentTermDays: input.paymentTermDays ?? null, paymentCondition: input.paymentCondition ?? "CREDIT", status: input.status ?? "ACTIVE", notes: clean(input.notes) ?? null, createdAt: now(), updatedAt: now() }; suppliers = [...suppliers, created]; return created; } return adaptSupplier((await fetchJson("/suppliers", { method: "POST", body: JSON.stringify(supplierBody(input)) })) as RawSupplier); },
  async updateSupplier(id, input: UpdateSupplierDto) { if (!baseUrl()) { await wait(); const current = suppliers.find((item) => item.id === id); if (!current) throw new Error("El proveedor ya no está disponible."); const taxId = input.taxId === undefined ? current.taxId : clean(input.taxId) ?? null; if (taxId && suppliers.some((item) => item.id !== id && item.taxId === taxId)) throw new Error("Ya existe un proveedor con ese CUIT."); const next: Supplier = { ...current, ...supplierBody(input), ...(input.legalName === undefined ? {} : { legalName: clean(input.legalName) ?? null }), ...(input.taxId === undefined ? {} : { taxId }), ...(input.contactName === undefined ? {} : { contactName: clean(input.contactName) ?? null }), ...(input.phone === undefined ? {} : { phone: clean(input.phone) ?? null }), ...(input.email === undefined ? {} : { email: clean(input.email) ?? null }), ...(input.address === undefined ? {} : { address: clean(input.address) ?? null }), ...(input.notes === undefined ? {} : { notes: clean(input.notes) ?? null }), updatedAt: now() }; suppliers = suppliers.map((item) => item.id === id ? next : item); return next; } return adaptSupplier((await fetchJson(`/suppliers/${encodeURIComponent(id)}`, { method: "PATCH", body: JSON.stringify(supplierBody(input)) })) as RawSupplier); },
  async searchProducts(query) { if (!baseUrl()) { await wait(); const normalized = query.trim().toLocaleLowerCase("es-AR"); return products.filter((item) => !normalized || [item.name, item.slug].some((value) => value.toLocaleLowerCase("es-AR").includes(normalized))); } const payload = await fetchJson(`/products?q=${encodeURIComponent(query)}&pageSize=10`); const items = payload && typeof payload === "object" && Array.isArray((payload as { items?: unknown }).items) ? (payload as { items: Array<{ id: string | number; name: string; slug?: string }> }).items : []; return items.map((item) => ({ id: String(item.id), name: item.name, slug: item.slug ?? "" })); },
  async createPackaging(productId, input) { if (!baseUrl()) { await wait(); if (packagings.some((item) => item.productId === productId && item.supplierId === (input.supplierId ?? null) && item.name.toLocaleLowerCase() === input.name.trim().toLocaleLowerCase())) throw new Error("Ya existe esa presentación para este proveedor y producto."); const supplier = suppliers.find((item) => item.id === input.supplierId); const product = products.find((item) => item.id === productId) ?? { id: productId, name: "Producto", slug: "" }; const created: PurchasePackaging = { id: `pack-${crypto.randomUUID()}`, productId, supplierId: input.supplierId ?? null, supplier: supplier ? { id: supplier.id, name: supplier.name } : undefined, product, name: input.name.trim(), unitsPerPack: input.unitsPerPack, barcode: clean(input.barcode) ?? null, supplierCode: clean(input.supplierCode) ?? null, isDefault: input.isDefault ?? false, isActive: input.isActive ?? true, createdAt: now(), updatedAt: now() }; packagings = [...packagings, created]; return created; } return adaptPackaging((await fetchJson(`/products/${encodeURIComponent(productId)}/purchase-packagings`, { method: "POST", body: JSON.stringify({ productId, ...packagingBody(input) }) })) as RawPackaging); },
  async updatePackaging(id, input) { if (!baseUrl()) { await wait(); const current = packagings.find((item) => item.id === id); if (!current) throw new Error("La presentación ya no está disponible."); const body = packagingBody(input); const next = { ...current, ...body, barcode: input.barcode === undefined ? current.barcode : clean(input.barcode) ?? null, supplierCode: input.supplierCode === undefined ? current.supplierCode : clean(input.supplierCode) ?? null, updatedAt: now() }; packagings = packagings.map((item) => item.id === id ? next : item); return next; } return adaptPackaging((await fetchJson(`/purchase-packagings/${encodeURIComponent(id)}`, { method: "PATCH", body: JSON.stringify(packagingBody(input)) })) as RawPackaging); },
};
