import { authFetch } from "./http";
import type { Tax, TaxApi, TaxInput, TaxPatch } from "./tax-contract";

const baseUrl = () => process.env.NEXT_PUBLIC_SUPERX_API_BASE_URL;
type Raw = Record<string, unknown>;
const adapt = (raw: Raw): Tax => ({ id: String(raw.id ?? ""), name: String(raw.name ?? ""), type: raw.type as Tax["type"], rate: Number(raw.rate ?? 0), includeInCost: raw.includeInCost === true, isDefault: raw.isDefault === true, isActive: raw.isActive !== false, createdAt: String(raw.createdAt ?? ""), updatedAt: String(raw.updatedAt ?? "") });
async function fetchJson(path: string, init: RequestInit = {}) { if (!baseUrl()) throw Object.assign(new Error("El catálogo de impuestos requiere conexión con la API."), { status: 404 }); const response = await authFetch(`${baseUrl()!.replace(/\/$/, "")}${path}`, { ...init, headers: { Accept: "application/json", ...(init.body ? { "Content-Type": "application/json" } : {}), ...init.headers } }); const payload: unknown = await response.json().catch(() => undefined); if (!response.ok) throw Object.assign(new Error(response.status === 409 ? "Ya existe un impuesto con ese nombre." : response.status === 401 || response.status === 403 ? "No tenés permiso para gestionar impuestos." : "No pudimos completar la operación."), { status: response.status }); return payload; }
const clean = (input: TaxInput | TaxPatch) => ({ ...input, ...(input.name === undefined ? {} : { name: input.name.trim() }), ...(input.rate === undefined ? {} : { rate: Number(input.rate) }) });
export const taxApi: TaxApi = { async list(active) { const raw = await fetchJson(`/taxes${active ? "?active=true" : ""}`); return (Array.isArray(raw) ? raw : []).map((item) => adapt(item as Raw)); }, async create(input) { return adapt(await fetchJson("/taxes", { method: "POST", body: JSON.stringify(clean(input)) }) as Raw); }, async update(id, input) { return adapt(await fetchJson(`/taxes/${encodeURIComponent(id)}`, { method: "PATCH", body: JSON.stringify(clean(input)) }) as Raw); } };
