import { authFetch } from "@/app/lib/http";
import type { TreasuryAccount, TreasuryAccountsResponse, TreasuryApi, TreasuryMovement } from "./treasury-contract";
import { addDecimalAmounts, applyDecimalMovement } from "./treasury-rules";

const baseUrl = () => process.env.NEXT_PUBLIC_SUPERX_API_BASE_URL;
const wait = () => new Promise<void>((resolve) => setTimeout(resolve, 180));
type Raw = Record<string, unknown>;
const string = (value: unknown) => String(value ?? "");
const nullable = (value: unknown) => value == null ? null : string(value);
const adaptAccount = (raw: Raw): TreasuryAccount => ({ id: string(raw.id), name: string(raw.name), type: raw.type as TreasuryAccount["type"], currency: string(raw.currency || "ARS"), isActive: raw.isActive !== false, allowNegative: raw.allowNegative !== false, openingBalance: string(raw.openingBalance), openingDate: string(raw.openingDate), createdAt: string(raw.createdAt), updatedAt: string(raw.updatedAt), balance: string(raw.balance) });
const adaptMovement = (raw: Raw): TreasuryMovement => ({ id: string(raw.id), accountId: string(raw.accountId), type: raw.type as TreasuryMovement["type"], amount: string(raw.amount), occurredAt: string(raw.occurredAt), referenceType: string(raw.referenceType), referenceId: nullable(raw.referenceId), description: nullable(raw.description), reversalOfId: nullable(raw.reversalOfId), transferId: nullable(raw.transferId), reversalReason: nullable(raw.reversalReason), ...(raw.runningBalance == null ? {} : { runningBalance: string(raw.runningBalance) }), ...(raw.direction === "IN" || raw.direction === "OUT" ? { direction: raw.direction } : {}), ...(typeof raw.sourceLabel === "string" ? { sourceLabel: raw.sourceLabel } : {}) });
async function fetchJson(path: string, init: RequestInit = {}) { const response = await authFetch(`${baseUrl()!.replace(/\/$/, "")}${path}`, { ...init, headers: { Accept: "application/json", ...(init.body ? { "Content-Type": "application/json" } : {}), ...init.headers } }); const payload: unknown = response.status === 204 ? undefined : await response.json().catch(() => undefined); if (!response.ok) { const message = payload && typeof payload === "object" && typeof (payload as { message?: unknown }).message === "string" ? (payload as { message: string }).message : "No pudimos completar la operación."; throw Object.assign(new Error(response.status === 401 || response.status === 403 ? "No tenés permiso para gestionar tesorería." : message), { status: response.status }); } return payload; }
let accounts: TreasuryAccount[] = [{ id: "1", name: "Caja central", type: "CASH", currency: "ARS", isActive: true, allowNegative: false, openingBalance: "15000.00", openingDate: "2026-09-01T09:00:00.000Z", createdAt: "2026-09-01T09:00:00.000Z", updatedAt: "2026-09-01T09:00:00.000Z", balance: "15000.00" }, { id: "2", name: "Banco operativo", type: "BANK", currency: "ARS", isActive: true, allowNegative: false, openingBalance: "85000.00", openingDate: "2026-09-01T09:00:00.000Z", createdAt: "2026-09-01T09:00:00.000Z", updatedAt: "2026-09-01T09:00:00.000Z", balance: "85000.00" }];
let movements: TreasuryMovement[] = [];
const totals = (): TreasuryAccountsResponse => ({ items: accounts, totalsByCurrency: Object.entries(accounts.reduce<Record<string, string[]>>((result, account) => ({ ...result, [account.currency]: [...(result[account.currency] ?? []), account.balance] }), {})).map(([currency, values]) => ({ currency, balance: addDecimalAmounts(values) })) });
const fixtureBalance = (accountId: string) => { const account = accounts.find((item) => item.id === accountId)!; account.balance = movements.filter((item) => item.accountId === accountId).reduce((balance, movement) => { const reversed = movement.reversalOfId ? movements.find((item) => item.id === movement.reversalOfId) : undefined; const effective = reversed?.type ?? movement.type; return ["INCOME", "TRANSFER_IN"].includes(effective) ? applyDecimalMovement(balance, movement.amount, movement.type === "REVERSAL" ? "OUT" : "IN") : ["EXPENSE", "TRANSFER_OUT"].includes(effective) ? applyDecimalMovement(balance, movement.amount, movement.type === "REVERSAL" ? "IN" : "OUT") : balance; }, account.openingBalance); };
export const treasuryApi: TreasuryApi = {
  async listAccounts() { if (!baseUrl()) { await wait(); return totals(); } const raw = await fetchJson("/treasury/accounts") as Raw; return { items: Array.isArray(raw.items) ? raw.items.map((item) => adaptAccount(item as Raw)) : [], totalsByCurrency: Array.isArray(raw.totalsByCurrency) ? raw.totalsByCurrency.map((item) => ({ currency: string((item as Raw).currency), balance: string((item as Raw).balance) })) : [] }; },
  async summary() { if (!baseUrl()) return this.listAccounts(); const raw = await fetchJson("/treasury/summary") as Raw; return { items: Array.isArray(raw.accounts) ? raw.accounts.map((item) => adaptAccount(item as Raw)) : [], totalsByCurrency: Array.isArray(raw.totalsByCurrency) ? raw.totalsByCurrency.map((item) => ({ currency: string((item as Raw).currency), balance: string((item as Raw).balance) })) : [] }; },
  async getAccount(id) { if (!baseUrl()) { const account = accounts.find((item) => item.id === id); if (!account) throw new Error("Cuenta no encontrada."); return account; } return adaptAccount((await fetchJson(`/treasury/accounts/${encodeURIComponent(id)}`)) as Raw); },
  async createAccount(input) { if (!baseUrl()) { await wait(); if (accounts.some((item) => item.name.toLowerCase() === input.name.trim().toLowerCase())) throw new Error("Ya existe una cuenta con ese nombre."); const now = new Date().toISOString(); const account: TreasuryAccount = { id: String(accounts.length + 1), name: input.name.trim(), type: input.type, currency: input.currency ?? "ARS", isActive: true, allowNegative: input.allowNegative ?? true, openingBalance: input.openingBalance || "0", openingDate: input.openingDate || now, createdAt: now, updatedAt: now, balance: input.openingBalance || "0" }; accounts = [...accounts, account]; return account; } return adaptAccount((await fetchJson("/treasury/accounts", { method: "POST", body: JSON.stringify(input) })) as Raw); },
  async updateAccount(id, input) { if (!baseUrl()) { await wait(); const current = await this.getAccount(id); const next = { ...current, ...input, name: input.name?.trim() || current.name, updatedAt: new Date().toISOString() }; accounts = accounts.map((item) => item.id === id ? next : item); return next; } return adaptAccount((await fetchJson(`/treasury/accounts/${encodeURIComponent(id)}`, { method: "PATCH", body: JSON.stringify(input) })) as Raw); },
  async ledger(id, filters = {}) { if (!baseUrl()) { await wait(); const all = movements.filter((item) => item.accountId === id && (!filters.type || item.type === filters.type) && (!filters.referenceType || item.referenceType === filters.referenceType) && (!filters.q || `${item.description} ${item.referenceId}`.toLowerCase().includes(filters.q.toLowerCase()))); return { items: all.map((item) => ({ ...item, runningBalance: accounts.find((account) => account.id === id)?.balance ?? "0.00" })), total: all.length, page: filters.page ?? 1, pageSize: filters.pageSize ?? 25, openingBalanceForPeriod: "0.00" }; } const params = new URLSearchParams(); (["from", "to", "type", "referenceType", "q", "page", "pageSize"] as const).forEach((key) => { if (filters[key]) params.set(key, String(filters[key])); }); const raw = await fetchJson(`/treasury/accounts/${encodeURIComponent(id)}/ledger?${params}`) as Raw; return { items: Array.isArray(raw.items) ? raw.items.map((item) => adaptMovement(item as Raw)) : [], total: Number(raw.total ?? 0), page: Number(raw.page ?? 1), pageSize: Number(raw.pageSize ?? 25), openingBalanceForPeriod: string(raw.openingBalanceForPeriod) }; },
  async createManualMovement(input) { if (!baseUrl()) { await wait(); const account = await this.getAccount(input.accountId); const movement: TreasuryMovement = { id: crypto.randomUUID(), accountId: input.accountId, type: input.type, amount: input.amount, occurredAt: input.occurredAt || new Date().toISOString(), referenceType: "MANUAL", referenceId: null, description: input.description, reversalOfId: null, transferId: null, reversalReason: null }; movements = [...movements, movement]; fixtureBalance(account.id); return movement; } return adaptMovement((await fetchJson("/treasury/movements", { method: "POST", body: JSON.stringify({ ...input, accountId: Number(input.accountId) }) })) as Raw); },
  async reverseMovement(id, reason) { if (!baseUrl()) { const original = movements.find((item) => item.id === id); if (!original) throw new Error("Movimiento no encontrado."); const reversal = { ...original, id: crypto.randomUUID(), type: "REVERSAL" as const, reversalOfId: id, description: `Reversa de movimiento #${id}`, reversalReason: reason, occurredAt: new Date().toISOString() }; movements = [...movements, reversal]; fixtureBalance(original.accountId); return reversal; } return adaptMovement((await fetchJson(`/treasury/movements/${encodeURIComponent(id)}/reverse`, { method: "POST", body: JSON.stringify({ reason }) })) as Raw); },
  async createTransfer(input) { if (!baseUrl()) { await wait(); const transferId = crypto.randomUUID(); const out: TreasuryMovement = { id: crypto.randomUUID(), accountId: input.fromAccountId, type: "TRANSFER_OUT", amount: input.amount, occurredAt: input.date, referenceType: "TRANSFER", referenceId: transferId, description: input.notes || null, reversalOfId: null, transferId, reversalReason: null }; const incoming: TreasuryMovement = { id: crypto.randomUUID(), accountId: input.toAccountId, type: "TRANSFER_IN", amount: input.amount, occurredAt: input.date, referenceType: "TRANSFER", referenceId: transferId, description: input.notes || null, reversalOfId: null, transferId, reversalReason: null }; movements = [...movements, out, incoming]; fixtureBalance(out.accountId); fixtureBalance(incoming.accountId); return { movements: [out, incoming] }; } return fetchJson("/treasury/transfers", { method: "POST", body: JSON.stringify({ ...input, fromAccountId: Number(input.fromAccountId), toAccountId: Number(input.toAccountId) }) }); },
  async reverseTransfer(id, reason) { if (!baseUrl()) { const originals = movements.filter((item) => item.transferId === id && item.type !== "REVERSAL"); if (originals.length !== 2) throw new Error("La transferencia ya fue revertida o no está disponible."); const reversals = originals.map((original) => ({ ...original, id: crypto.randomUUID(), type: "REVERSAL" as const, reversalOfId: original.id, description: `Reversa de transferencia #${id}`, reversalReason: reason, occurredAt: new Date().toISOString() })); movements = [...movements, ...reversals]; originals.forEach((item) => fixtureBalance(item.accountId)); return { id, movements: reversals }; } return fetchJson(`/treasury/transfers/${encodeURIComponent(id)}/reverse`, { method: "POST", body: JSON.stringify({ reason }) }); },
};
