"use client";

import { Notice } from "@/app/components/ui/notice";

import { type FormEvent, useEffect, useRef, useState } from "react";
import type { PaymentCondition, Supplier, SupplierInput, SupplierStatus } from "@/app/lib/supplier-contract";
import { normalizeCuit, validateSupplierInput } from "@/app/lib/supplier-rules";

export type SupplierFormValues = Required<Omit<SupplierInput, "paymentTermDays">> & { paymentTermDays: string };
export const emptySupplierForm: SupplierFormValues = { name: "", legalName: "", taxId: "", contactName: "", phone: "", email: "", address: "", paymentTermDays: "", paymentCondition: "CREDIT", status: "ACTIVE", notes: "" };
export const supplierToForm = (supplier?: Supplier | null): SupplierFormValues => supplier ? { name: supplier.name, legalName: supplier.legalName ?? "", taxId: supplier.taxId ?? "", contactName: supplier.contactName ?? "", phone: supplier.phone ?? "", email: supplier.email ?? "", address: supplier.address ?? "", paymentTermDays: supplier.paymentTermDays?.toString() ?? "", paymentCondition: supplier.paymentCondition, status: supplier.status, notes: supplier.notes ?? "" } : emptySupplierForm;
export const formToInput = (form: SupplierFormValues): SupplierInput => ({ ...form, paymentTermDays: form.paymentTermDays === "" ? null : Number(form.paymentTermDays), status: form.status as SupplierStatus });

export function SupplierDialog({ supplier, pending, onClose, onSubmit }: { supplier?: Supplier | null; pending: boolean; onClose: () => void; onSubmit: (input: SupplierInput) => void }) {
  const [form, setForm] = useState<SupplierFormValues>(() => supplierToForm(supplier)); const [errors, setErrors] = useState<Record<string, string>>({}); const [errorTick, setErrorTick] = useState(0); const errorRef = useRef<HTMLDivElement>(null);
  // Only move focus to the error summary right after a failed submit, not on every
  // keystroke — `change()` below also touches `errors` (to clear a field's message
  // as the user retypes it), which would otherwise steal focus back mid-typing.
  useEffect(() => { if (errorTick) errorRef.current?.focus(); }, [errorTick]);
  const change = <K extends keyof SupplierFormValues>(key: K, value: SupplierFormValues[K]) => { setForm((current) => ({ ...current, [key]: value })); setErrors((current) => ({ ...current, [key]: "" })); };
  const submit = (event: FormEvent) => { event.preventDefault(); const next = validateSupplierInput(formToInput(form)); setErrors(next as unknown as Record<string, string>); if (!Object.keys(next).length) { onSubmit(formToInput(form)); return; } setErrorTick((tick) => tick + 1); };
  return <div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true" aria-labelledby="supplier-form-title"><header><div><p className="eyebrow">OPERACIONES / PROVEEDORES</p><h2 id="supplier-form-title">{supplier ? "Editar proveedor" : "Nuevo proveedor"}</h2></div><button type="button" className="icon-button" aria-label="Cerrar" onClick={onClose}>×</button></header><form onSubmit={submit}><div ref={errorRef} tabIndex={-1}>{Object.values(errors).filter(Boolean).length > 0 && <Notice kind="error" role="alert">{Object.values(errors).filter(Boolean).join(" ")}</Notice>}</div><div className="form-grid"><Field label="Nombre comercial *" error={errors.name}><input autoFocus value={form.name} onChange={(event) => change("name", event.target.value)} /></Field><Field label="Razón social"><input value={form.legalName} onChange={(event) => change("legalName", event.target.value)} /></Field><Field label="CUIT" error={errors.taxId}><input inputMode="numeric" value={form.taxId} onChange={(event) => change("taxId", normalizeCuit(event.target.value))} /></Field><Field label="Contacto"><input value={form.contactName} onChange={(event) => change("contactName", event.target.value)} /></Field><Field label="Teléfono"><input value={form.phone} onChange={(event) => change("phone", event.target.value)} /></Field><Field label="Email"><input type="email" value={form.email} onChange={(event) => change("email", event.target.value)} /></Field><Field label="Condición"><select value={form.paymentCondition} onChange={(event) => change("paymentCondition", event.target.value as PaymentCondition)}><option value="CREDIT">Crédito</option><option value="CASH">Contado</option><option value="TRANSFER">Transferencia</option><option value="OTHER">Otra</option></select></Field><Field label="Plazo de pago (días)" error={errors.paymentTermDays}><input type="number" min="0" step="1" value={form.paymentTermDays} onChange={(event) => change("paymentTermDays", event.target.value)} /></Field><Field label="Estado"><select value={form.status} onChange={(event) => change("status", event.target.value as SupplierStatus)}><option value="ACTIVE">Activo</option><option value="INACTIVE">Inactivo</option></select></Field><Field label="Dirección"><input value={form.address} onChange={(event) => change("address", event.target.value)} /></Field></div><Field label="Notas"><textarea rows={3} value={form.notes} onChange={(event) => change("notes", event.target.value)} /></Field><footer><button type="button" className="button ghost" onClick={onClose}>Cancelar</button><button className="button primary" disabled={pending}>{pending ? "Guardando…" : supplier ? "Guardar cambios" : "Crear proveedor"}</button></footer></form></section></div>;
}

function Field({ label, error, children }: { label: string; error?: string; children: React.ReactNode }) { return <label className="field"><span>{label}</span>{children}{error && <small className="field-error">{error}</small>}</label>; }
