"use client";

import Link from "next/link";
import { useRouter, useSearchParams } from "next/navigation";
import { useCallback, useEffect, useMemo, useState } from "react";
import { ListSkeleton } from "@/app/components/list-skeleton";
import { roles } from "@/app/components/location-ui";
import { getStoredUser } from "@/app/lib/auth-api";
import { orderApi } from "@/app/lib/order-api";
import type { Order, OrderPaymentMethodSetting, OrderStatus } from "@/app/lib/order-contract";
import type { UserRole } from "@/app/lib/product-contract";
import { formatDeliveryWindow, getOrderDashboardStatus, ORDER_PAYMENT_METHOD_LABELS, ORDER_STATUS_LABELS } from "@/app/lib/order-rules";
import { dateTime, getOrderAlerts, money, OrderIcon, OrderPaymentBadge, OrderStatusBadge } from "./order-shared";

type Sort = "recent" | "oldest" | "delivery" | "total";
const statusCards = [
  { key: "pending", label: "Pendientes", icon: "clock", statuses: ["CREATED"] },
  { key: "confirmed", label: "Confirmados", icon: "check", statuses: ["CONFIRMED", "PAID"] },
  { key: "picking", label: "Picking", icon: "items", statuses: ["PICKING", "PACKED"] },
  { key: "ready", label: "Listos", icon: "orders", statuses: ["READY"] },
  { key: "delivery", label: "Reparto", icon: "delivery", statuses: ["OUT_FOR_DELIVERY"] },
  { key: "delivered", label: "Entregados", icon: "check", statuses: ["DELIVERED"] },
  { key: "cancelled", label: "Cancelados", icon: "close", statuses: ["CANCELLED"] },
] as const;
function deliveryKey(order: Order) { return order.deliverySlot ? `${order.deliverySlot.date}T${order.deliverySlot.startTime}` : "9999"; }

export function OrdersWorkspace() {
  const router = useRouter(); const params = useSearchParams();
  const [orders, setOrders] = useState<Order[]>([]); const [role, setRole] = useState<UserRole>("viewer"); const [loading, setLoading] = useState(true); const [loadError, setLoadError] = useState("");
  const [paymentSettings, setPaymentSettings] = useState<OrderPaymentMethodSetting[] | null>(null); const [savingMethod, setSavingMethod] = useState("");
  const query = params.get("q") ?? ""; const status = (params.get("status") ?? "all") as "all" | OrderStatus; const stage = params.get("stage") ?? ""; const date = params.get("date") ?? ""; const zone = params.get("zone") ?? "all"; const payment = params.get("payment") ?? "all"; const sort = (params.get("sort") ?? "recent") as Sort;
  const setParam = useCallback((key: string, value: string, defaultValue = "") => { const next = new URLSearchParams(params.toString()); if (!value || value === defaultValue) next.delete(key); else next.set(key, value); router.replace(`/pedidos${next.size ? `?${next}` : ""}`, { scroll: false }); }, [params, router]);
  const load = useCallback(async () => { setLoading(true); setLoadError(""); try { if (!navigator.onLine) throw new Error("Verificá tu conexión y reintentá."); setOrders(await orderApi.listOrders()); } catch (error) { setLoadError(error instanceof Error ? error.message : "No pudimos cargar los pedidos."); } finally { setLoading(false); } }, []);
  useEffect(() => { // Initial synchronization with the orders adapter.
    // eslint-disable-next-line react-hooks/set-state-in-effect
    void load();
  }, [load]);
  useEffect(() => { const user = getStoredUser(); // eslint-disable-next-line react-hooks/set-state-in-effect
    setRole(user?.role === "admin" ? "admin" : "viewer"); }, []);
  const counts = useMemo(() => Object.fromEntries(statusCards.map(({ key }) => [key, orders.filter((order) => getOrderDashboardStatus(order.status) === key).length])), [orders]);
  const zones = useMemo(() => [...new Set(orders.map((order) => order.deliveryZone))].sort(), [orders]);
  const visible = useMemo(() => { const normalized = query.trim().toLocaleLowerCase("es-AR"); return orders.filter((order) => { const matchesSearch = [order.code, order.customerName, order.customerPhone].some((value) => value.toLocaleLowerCase("es-AR").includes(normalized)); return (!normalized || matchesSearch) && (status === "all" || order.status === status) && (!stage || getOrderDashboardStatus(order.status) === stage) && (!date || order.deliverySlot?.date === date) && (zone === "all" || order.deliveryZone === zone) && (payment === "all" || (payment === "paid" ? order.payment.status === "PAID" : order.payment.status === "PENDING")); }).sort((a, b) => sort === "oldest" ? a.createdAt.localeCompare(b.createdAt) : sort === "delivery" ? deliveryKey(a).localeCompare(deliveryKey(b)) : sort === "total" ? b.total - a.total : b.createdAt.localeCompare(a.createdAt)); }, [date, orders, payment, query, sort, stage, status, zone]);
  const clearFilters = () => router.replace("/pedidos", { scroll: false });
  const selectSummary = (key: string) => { const next = new URLSearchParams(params.toString()); next.delete("status"); if (stage === key) next.delete("stage"); else next.set("stage", key); router.replace(`/pedidos${next.size ? `?${next}` : ""}`, { scroll: false }); };
  const selectExactStatus = (value: string) => { const next = new URLSearchParams(params.toString()); next.delete("stage"); if (value === "all") next.delete("status"); else next.set("status", value); router.replace(`/pedidos${next.size ? `?${next}` : ""}`, { scroll: false }); };
  const detailHref = (id: string) => `/pedidos/${encodeURIComponent(id)}${params.size ? `?from=${encodeURIComponent(params.toString())}` : ""}`;
  const openPaymentSettings = async () => { setPaymentSettings(await orderApi.listPaymentMethods()); };
  const togglePaymentMethod = async (item: OrderPaymentMethodSetting) => { setSavingMethod(item.method); try { const updated = await orderApi.setPaymentMethodEnabled(item.method, !item.enabled); setPaymentSettings((current) => current?.map((method) => method.method === updated.method ? updated : method) ?? null); } finally { setSavingMethod(""); } };

  return <section className="workspace orders-workspace" id="pedidos">
    <header className="orders-header"><div><p className="orders-breadcrumb">Operaciones <span>/</span> Pedidos</p><h1>Pedidos</h1><p>Control operativo de todos los pedidos del supermercado. Gestioná, prepará y realizá el seguimiento en tiempo real.</p></div><div className="orders-header-tools">{role === "admin" && <button className="button secondary" onClick={() => void openPaymentSettings()}>Medios de pago</button>}<span className="orders-role">Vista: {roles[role]}</span></div></header>
    <section className="order-status-summary" aria-label="Resumen por estado">{statusCards.map((card) => { const count = Number(counts[card.key] ?? 0); const active = stage === card.key || (!stage && card.statuses.includes(status as never)); return <button key={card.key} className={`order-summary-card summary-${card.key}${active ? " active" : ""}`} aria-pressed={active} onClick={() => selectSummary(card.key)}><span className="summary-icon"><OrderIcon name={card.icon} /></span><span><small>{card.label}</small><strong>{count}</strong></span><em>{orders.length ? Math.round(count / orders.length * 100) : 0}%</em></button>; })}</section>
    <section className="orders-filterbar" aria-label="Filtros de pedidos"><label className="orders-search"><span className="sr-only">Buscar pedidos</span><OrderIcon name="search" /><input value={query} onChange={(event) => setParam("q", event.target.value)} placeholder="Buscar por código de pedido o cliente..." /></label><label><span>Estado</span><select value={status} onChange={(event) => selectExactStatus(event.target.value)}><option value="all">Todos los estados</option>{Object.entries(ORDER_STATUS_LABELS).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label><span>Fecha de entrega</span><input type="date" value={date} onChange={(event) => setParam("date", event.target.value)} /></label><label><span>Zona</span><select value={zone} onChange={(event) => setParam("zone", event.target.value, "all")}><option value="all">Todas las zonas</option>{zones.map((item) => <option key={item}>{item}</option>)}</select></label><label><span>Pago</span><select value={payment} onChange={(event) => setParam("payment", event.target.value, "all")}><option value="all">Todos</option><option value="paid">Pagado</option><option value="pending">Pendiente</option></select></label><button className="orders-clear" onClick={clearFilters}>Limpiar filtros</button></section>
    <section className="orders-list-card"><header><div><h2>{visible.length} {visible.length === 1 ? "pedido" : "pedidos"}</h2><p>{visible.length === orders.length ? "Todos los pedidos cargados" : `de ${orders.length} pedidos cargados`}</p></div><label className="orders-sort"><span>Ordenar por</span><select value={sort} onChange={(event) => setParam("sort", event.target.value, "recent")}><option value="recent">Más recientes</option><option value="oldest">Más antiguos</option><option value="delivery">Entrega más próxima</option><option value="total">Mayor total</option></select></label></header>
      {loading ? <ListSkeleton label="Cargando pedidos…" /> : loadError ? <div className="orders-state"><OrderIcon name="alert" /><strong>No pudimos cargar los pedidos.</strong><span>{loadError}</span><button className="button secondary" onClick={() => void load()}>Reintentar</button></div> : visible.length === 0 ? <div className="orders-state"><OrderIcon name="orders" /><strong>No hay pedidos que coincidan con los filtros.</strong><button className="button secondary" onClick={clearFilters}>Limpiar filtros</button></div> : <><div className="orders-table-wrap"><table className="orders-table"><thead><tr><th>Pedido</th><th>Cliente</th><th>Estado</th><th>Entrega</th><th>Pago</th><th>Total</th><th>Zona</th><th>Items</th><th>Alertas</th><th><span className="sr-only">Acción</span></th></tr></thead><tbody>{visible.map((order) => { const alerts = getOrderAlerts(order); const window = formatDeliveryWindow(order.deliverySlot).split(" · "); return <tr key={order.id} tabIndex={0} role="link" aria-label={`Ver detalle de ${order.code}`} onClick={() => router.push(detailHref(order.id))} onKeyDown={(event) => { if (event.key === "Enter" || event.key === " ") router.push(detailHref(order.id)); }}><td><strong>{order.code}</strong><small>{dateTime.format(new Date(order.createdAt))}</small></td><td><strong>{order.customerName}</strong><small>{order.customerPhone}</small></td><td><OrderStatusBadge status={order.status} /></td><td><strong>{window[0]}</strong><small>{window[1] ?? "Horario pendiente"}</small></td><td><OrderPaymentBadge order={order} /></td><td className="orders-total">{money.format(order.total)}</td><td>{order.deliveryZone}</td><td className="orders-count">{order.lines.length}</td><td>{alerts.length ? <span className="order-alert" title={alerts.join(" · ")} aria-label={alerts.join(". ")}><OrderIcon name="alert" /><b>{alerts.length}</b></span> : <span className="orders-none">—</span>}</td><td><Link className="orders-row-link" href={detailHref(order.id)} aria-label={`Abrir ${order.code}`} onClick={(event) => event.stopPropagation()}><OrderIcon name="chevron" /></Link></td></tr>; })}</tbody></table></div><div className="orders-mobile-list">{visible.map((order) => <Link key={order.id} className="order-mobile-card" href={detailHref(order.id)}><header><strong>{order.code}</strong><OrderStatusBadge status={order.status} /></header><h3>{order.customerName}</h3><p>Entrega: {formatDeliveryWindow(order.deliverySlot)}</p><dl><div><dt>Zona</dt><dd>{order.deliveryZone}</dd></div><div><dt>Productos</dt><dd>{order.lines.length}</dd></div><div><dt>Total</dt><dd>{money.format(order.total)}</dd></div></dl><footer><OrderPaymentBadge order={order} /><span>Ver pedido <OrderIcon name="chevron" /></span></footer></Link>)}</div></>}
    </section>{paymentSettings && <div className="modal-backdrop"><section className="modal payment-settings-modal" role="dialog" aria-modal="true" aria-labelledby="payment-settings-title"><header><div><h2 id="payment-settings-title">Medios de pago</h2><p>Definí qué opciones pueden seleccionarse al acreditar un pedido.</p></div><button className="icon-button" aria-label="Cerrar" onClick={() => setPaymentSettings(null)}>×</button></header><div className="payment-settings-list">{paymentSettings.map((item) => <div key={item.method}><span><strong>{ORDER_PAYMENT_METHOD_LABELS[item.method]}</strong><small>{item.enabled ? "Disponible para nuevos cobros" : "No disponible"}</small></span><button className={`button ${item.enabled ? "secondary" : "primary"}`} disabled={savingMethod === item.method || (item.enabled && paymentSettings.filter((method) => method.enabled).length === 1)} onClick={() => void togglePaymentMethod(item)}>{savingMethod === item.method ? "Guardando…" : item.enabled ? "Desactivar" : "Activar"}</button></div>)}</div><footer><button className="button primary" onClick={() => setPaymentSettings(null)}>Listo</button></footer></section></div>}
  </section>;
}
