"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { ListSkeleton } from "@/app/components/list-skeleton";
import { Notice } from "@/app/components/ui/notice";
import { getStoredUser } from "@/app/lib/auth-api";
import { orderApi } from "@/app/lib/order-api";
import type { Order, OrderPaymentMethod, OrderStatus, PackingChecklist } from "@/app/lib/order-contract";
import type { UserRole } from "@/app/lib/product-contract";
import { canRoleTransitionOrder, formatDeliveryWindow, getAvailableOrderTransitions, ORDER_PAYMENT_METHOD_LABELS, ORDER_PAYMENT_STATUS_LABELS, ORDER_STATUS_LABELS, summarizeOrderCharges } from "@/app/lib/order-rules";
import { ConfirmOrderPayment, ConfirmOrderTransition, dateTime, getOrderAlerts, money, OrderIcon, OrderPaymentBadge, OrderStatusBadge } from "./order-shared";

const actors: Record<UserRole, string> = { viewer: "Usuario de consulta", operator: "Operador actual", admin: "Administración actual" };
const flow: Array<{ status: OrderStatus; label: string }> = [{ status: "CREATED", label: "Pendiente" }, { status: "CONFIRMED", label: "Confirmado" }, { status: "PICKING", label: "Picking" }, { status: "READY", label: "Listo" }, { status: "OUT_FOR_DELIVERY", label: "Reparto" }, { status: "DELIVERED", label: "Entregado" }];
const ranks: Record<OrderStatus, number> = { CREATED: 0, CONFIRMED: 1, PAID: 1, PICKING: 2, PACKED: 2, READY: 3, OUT_FOR_DELIVERY: 4, DELIVERED: 5, CANCELLED: -1 };
type NoticeState = { kind: "success" | "error"; text: string } | null;

export function OrderDetailWorkspace({ id, returnQuery }: { id: string; returnQuery?: string }) {
  const [order, setOrder] = useState<Order | null>(null); const [role, setRole] = useState<UserRole>("viewer"); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [notice, setNotice] = useState<NoticeState>(null); const [pendingStatus, setPendingStatus] = useState<OrderStatus | null>(null); const [paymentModal, setPaymentModal] = useState(false); const [pending, setPending] = useState(false);
  const backHref = `/pedidos${returnQuery ? `?${returnQuery}` : ""}`;
  const load = async () => { setLoading(true); setError(""); try { setOrder(await orderApi.getOrder(id)); } catch (caught) { setError(caught instanceof Error ? caught.message : "No pudimos cargar el pedido."); } finally { setLoading(false); } };
  useEffect(() => { // Initial synchronization with the order adapter.
    // eslint-disable-next-line react-hooks/set-state-in-effect
    void load();
    // The id is the only input that selects a record; load is intentionally local.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [id]);
  useEffect(() => { const user = getStoredUser(); // eslint-disable-next-line react-hooks/set-state-in-effect
    setRole(user?.role === "admin" ? "admin" : "viewer"); }, []);
  const transition = async (note?: string, checklist?: PackingChecklist) => { if (!order || !pendingStatus) return; setPending(true); setNotice(null); try { const updated = await orderApi.transitionOrder(order.id, { status: pendingStatus, performedBy: actors[role], performedByRole: role, note, checklist }); setOrder(updated); setNotice({ kind: "success", text: `${updated.code} quedó ${ORDER_STATUS_LABELS[updated.status].toLocaleLowerCase("es-AR")}.` }); } catch (caught) { setNotice({ kind: "error", text: caught instanceof Error ? caught.message : "No se pudo actualizar el pedido." }); } finally { setPending(false); setPendingStatus(null); } };
  const confirmPayment = async (paymentMethod: OrderPaymentMethod, treasuryAccountId: string, note?: string) => { if (!order) return; setPending(true); setNotice(null); try { const updated = await orderApi.updatePayment(order.id, { status: "PAID", paymentMethod, treasuryAccountId, note }); setOrder(updated); setNotice({ kind: "success", text: `El pago de ${updated.code} fue acreditado en Tesorería sin modificar su estado logístico.` }); } catch (caught) { setNotice({ kind: "error", text: caught instanceof Error ? caught.message : "No se pudo acreditar el pago." }); } finally { setPending(false); setPaymentModal(false); } };
  if (loading) return <section className="workspace order-detail-workspace"><ListSkeleton label="Cargando detalle del pedido…" /></section>;
  if (error || !order) return <section className="workspace order-detail-workspace"><Link href={backHref} className="order-back">← Volver a pedidos</Link><div className="orders-state"><OrderIcon name="alert" /><strong>No pudimos cargar el pedido.</strong><span>{error}</span><button className="button secondary" onClick={() => void load()}>Reintentar</button></div></section>;
  const alerts = getOrderAlerts(order); const transitions = getAvailableOrderTransitions(order) as OrderStatus[];
  return <section className="workspace order-detail-workspace">
    <header className="order-detail-header"><div><p className="orders-breadcrumb">Operaciones <span>/</span> <Link href={backHref}>Pedidos</Link> <span>/</span> Detalle</p><div className="order-title-line"><h1>Pedido {order.code}</h1><OrderStatusBadge status={order.status} /></div><p>Realizado el {dateTime.format(new Date(order.createdAt))}</p></div><div className="order-header-actions"><Link href={backHref} className="button secondary">Volver a pedidos</Link><button className="button secondary" onClick={() => window.print()}><OrderIcon name="print" /> Imprimir</button></div></header>
    {notice && <Notice kind={notice.kind} label={notice.kind === "success" ? "Listo" : "No se pudo completar"} onDismiss={() => setNotice(null)}>{notice.text}</Notice>}
    {alerts.length > 0 && <div className="order-alert-strip"><OrderIcon name="alert" /><strong>Atención operativa</strong><span>{alerts.join(" · ")}</span></div>}
    <OrderSummary order={order} />
    <section className="order-detail-layout"><main><OrderTimeline order={order} /><OrderItems order={order} /></main><aside><CustomerCard order={order} /><AddressCard order={order} /><PaymentCard order={order} canManage={role === "admin"} onPay={() => setPaymentModal(true)} /><OrderActions order={order} role={role} transitions={transitions} onTransition={setPendingStatus} /></aside></section>
    <OrderHistory order={order} />
    {pendingStatus && <ConfirmOrderTransition order={order} status={pendingStatus} pending={pending} onCancel={() => setPendingStatus(null)} onConfirm={(note, checklist) => void transition(note, checklist)} />}{paymentModal && <ConfirmOrderPayment order={order} pending={pending} onCancel={() => setPaymentModal(false)} onConfirm={(paymentMethod, treasuryAccountId, note) => void confirmPayment(paymentMethod, treasuryAccountId, note)} />}
  </section>;
}

function OrderSummary({ order }: { order: Order }) { const cards = [{ icon: "payment" as const, label: "Total del pedido", value: money.format(order.total) }, { icon: "check" as const, label: "Estado actual", node: <OrderStatusBadge status={order.status} /> }, { icon: "calendar" as const, label: "Ventana de entrega", value: formatDeliveryWindow(order.deliverySlot) }, { icon: "payment" as const, label: "Método de pago", node: <OrderPaymentBadge order={order} /> }, { icon: "location" as const, label: "Zona", value: order.deliveryZone }, { icon: "items" as const, label: "Productos", value: `${order.lines.length} ítems` }]; return <section className="order-detail-summary" aria-label="Resumen del pedido">{cards.map((card) => <article key={card.label}><span><OrderIcon name={card.icon} /></span><div><small>{card.label}</small>{card.node ?? <strong>{card.value}</strong>}</div></article>)}</section>; }

function OrderTimeline({ order }: { order: Order }) { const currentRank = ranks[order.status]; if (order.status === "CANCELLED") { const cancelled = [...order.events].reverse().find((event) => event.status === "CANCELLED"); return <section className="order-section-card"><header><div><p className="section-kicker">Flujo operativo</p><h2>Seguimiento del pedido</h2></div></header><div className="cancelled-timeline"><span><OrderIcon name="close" /></span><div><strong>Pedido cancelado</strong>{cancelled && <><time>{dateTime.format(new Date(cancelled.occurredAt))}</time><p>{cancelled.note ?? "La operación fue detenida."}</p></>}</div></div></section>; } return <section className="order-section-card"><header><div><p className="section-kicker">Flujo operativo</p><h2>Seguimiento del pedido</h2></div></header><ol className="order-timeline">{flow.map((step, index) => { const event = order.events.find((item) => item.status === step.status || (step.status === "CONFIRMED" && item.status === "PAID") || (step.status === "PICKING" && item.status === "PACKED")); const complete = index < currentRank; const current = index === currentRank; return <li key={step.status} className={complete ? "complete" : current ? "current" : "future"}><span className="timeline-dot">{complete ? <OrderIcon name="check" /> : index + 1}</span><strong>{step.label}</strong>{event ? <time>{dateTime.format(new Date(event.occurredAt))}</time> : <small>{current ? "Estado actual" : "Pendiente"}</small>}</li>; })}</ol></section>; }

function OrderItems({ order }: { order: Order }) { const breakdown = summarizeOrderCharges(order); return <section className="order-section-card order-items-section"><header><div><p className="section-kicker">Detalle comercial</p><h2>Resumen del pedido</h2></div><span>{order.lines.length} productos</span></header><div className="order-items-wrap"><table><thead><tr><th>Producto</th><th>Precio unit.</th><th>Cant.</th><th>Subtotal</th><th>Sustituciones / notas</th></tr></thead><tbody>{order.lines.map((item) => <tr key={item.id}><td><span className="product-placeholder"><OrderIcon name="items" /></span><strong>{item.productName}</strong></td><td>{money.format(item.unitPrice)}</td><td>{item.quantity}</td><td><strong>{money.format(item.quantity * item.unitPrice)}</strong></td><td>{item.substitution ? <span className="substitution-note">Reemplazo: {item.substitution.replacedBy}{item.substitution.note && <small>{item.substitution.note}</small>}</span> : <span className="orders-none">—</span>}</td></tr>)}</tbody></table></div><dl className="order-totals"><div><dt>Subtotal</dt><dd>{money.format(breakdown.subtotal)}</dd></div><div><dt>Descuentos</dt><dd>{breakdown.discount ? `−${money.format(breakdown.discount)}` : money.format(0)}</dd></div><div><dt>Costo de envío</dt><dd>{money.format(breakdown.deliveryFee)}</dd></div><div className="total"><dt>Total</dt><dd>{money.format(breakdown.total)}</dd></div></dl></section>; }

function CustomerCard({ order }: { order: Order }) { const phone = order.customerPhone.replace(/\D/g, ""); return <section className="order-side-card"><header><span><OrderIcon name="customer" /></span><h2>Cliente</h2></header><strong className="side-primary">{order.customerName}</strong><p>{order.customerPhone}</p><div className="side-actions"><a className="button secondary" href={`tel:${phone}`}><OrderIcon name="phone" /> Llamar</a><a className="button secondary" href={`https://wa.me/${phone}`} target="_blank" rel="noreferrer">WhatsApp</a></div>{order.customerNotes && <div className="side-note"><small>Nota del cliente</small><p>{order.customerNotes}</p></div>}</section>; }
function AddressCard({ order }: { order: Order }) { const map = `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(order.deliveryAddress)}`; return <section className="order-side-card"><header><span><OrderIcon name="location" /></span><h2>Dirección de entrega</h2></header><strong className="side-primary">{order.deliveryAddress}</strong><p>Zona {order.deliveryZone}</p><a className="side-link" href={map} target="_blank" rel="noreferrer">Ver en mapa ↗</a></section>; }
function PaymentCard({ order, canManage, onPay }: { order: Order; canManage: boolean; onPay: () => void }) { const paid = order.payment.status === "PAID"; return <section className="order-side-card payment-card"><header><span><OrderIcon name="payment" /></span><div><h2>Cobro y pago</h2><span className={`payment-card-status ${order.payment.status.toLowerCase()}`}><i aria-hidden="true" />{ORDER_PAYMENT_STATUS_LABELS[order.payment.status]}</span></div></header><div className="payment-card-total"><small>Total del pedido</small><strong>{money.format(order.total)}</strong></div><dl><div><dt>Método</dt><dd>{ORDER_PAYMENT_METHOD_LABELS[order.payment.method]}</dd></div></dl>{canManage && order.payment.status === "PENDING" && <button className="button primary payment-action" onClick={onPay}><OrderIcon name="payment" /> Acreditar pago</button>}{paid && <p className="payment-card-confirmation"><OrderIcon name="check" /> Pago acreditado</p>}<small className="side-muted">El cobro se gestiona independientemente del avance logístico.</small></section>; }
function OrderActions({ order, role, transitions, onTransition }: { order: Order; role: UserRole; transitions: OrderStatus[]; onTransition: (status: OrderStatus) => void }) { return <section className="order-side-card order-actions-card"><header><span><OrderIcon name="check" /></span><h2>Acciones del pedido</h2></header>{transitions.length ? <div>{transitions.map((status) => <button key={status} className={`button ${status === "CANCELLED" ? "danger-outline" : "primary"}`} disabled={!canRoleTransitionOrder(role, order, status)} onClick={() => onTransition(status)}>{status === "CANCELLED" ? "Cancelar pedido" : `Marcar como ${ORDER_STATUS_LABELS[status].toLocaleLowerCase("es-AR")}`}</button>)}</div> : <p className="side-muted">Este pedido no tiene acciones disponibles.</p>}<small>Las transiciones respetan el flujo y los permisos del backend.</small></section>; }

function OrderHistory({ order }: { order: Order }) { const [tab, setTab] = useState<"all" | "status" | "customer">("all"); const events = useMemo(() => [...order.events].reverse(), [order.events]); return <section className="order-section-card order-history"><header><div><p className="section-kicker">Trazabilidad</p><h2>Historial y observaciones</h2></div></header><div className="history-tabs" role="tablist"><button className={tab === "all" ? "active" : ""} onClick={() => setTab("all")}>Todos</button><button className={tab === "status" ? "active" : ""} onClick={() => setTab("status")}>Cambios de estado</button><button className={tab === "customer" ? "active" : ""} onClick={() => setTab("customer")}>Notas del cliente</button></div>{tab === "customer" ? <div className="customer-history-note">{order.customerNotes ?? "El cliente no dejó observaciones."}</div> : <div className="order-history-list">{events.map((event) => <article key={event.id}><span><OrderIcon name="history" /></span><div><strong>Pedido {ORDER_STATUS_LABELS[event.status].toLocaleLowerCase("es-AR")}</strong><p>por {event.actor}{event.role ? ` · ${event.role}` : ""}</p><time>{dateTime.format(new Date(event.occurredAt))}</time>{event.note && <blockquote>{event.note}</blockquote>}</div></article>)}</div>}</section>; }
