/* eslint-disable @next/next/no-img-element */
import Link from "next/link";
import type { InventoryItem } from "@/app/lib/inventory-contract";
import type { Price } from "@/app/lib/price-contract";
import type { Product } from "@/app/lib/product-contract";
const money = new Intl.NumberFormat("es-AR", { style: "currency", currency: "ARS" });
export function PricingTab({ price }: { price: Price | null }) { const cost = price?.cost ?? null; const sale = price?.price ?? null; const profit = sale !== null && cost !== null ? sale - cost : null; return <section className="erp-tab-content"><div className="erp-column"><h2>Venta</h2><Metric label="Precio de venta" value={sale === null ? "Sin precio" : money.format(sale)} /><Metric label="Precio anterior" value={price?.previousPrice === null || price?.previousPrice === undefined ? "—" : money.format(price.previousPrice)} /><Link className="button primary" href="/precios">Gestionar precio</Link></div><div className="erp-column"><h2>Costos</h2><Metric label="Costo actual" value={cost === null ? "Sin costo cargado" : money.format(cost)} /></div><div className="erp-column"><h2>Métricas automáticas</h2><Metric label="Ganancia por unidad" value={profit === null ? "—" : money.format(profit)} /><Metric label="Margen" value={price?.margin === null || price?.margin === undefined ? "—" : `${price.margin.toFixed(2)}%`} /><Metric label="Markup" value="—" /></div><section className="erp-table-section"><h2>Historial de costos</h2><Empty text="Consultá el historial completo desde Gestión de precios." /></section></section>; }
export function InventoryTab({ item }: { item: InventoryItem | null }) { const onHand = item?.onHand ?? 0; return <section className="erp-tab-content"><div className="inventory-summary"><Metric label="Stock físico" value={`${onHand} unidades`} /><Metric label="Stock reservado" value="—" /><Metric label="Stock disponible para venta" value={`${onHand} unidades`} /><Metric label="Stock mínimo" value="Sin configurar" /><Metric label="Stock objetivo" value="Sin configurar" /></div><div className="erp-column"><h2>Operación de inventario</h2><p className="erp-note">El stock no se edita desde esta ficha. Cada cambio deja un movimiento trazable.</p><Link className="button primary" href="/inventario">Registrar movimiento</Link><Link className="button secondary" href="/ubicaciones">Gestionar ubicación</Link></div><section className="erp-table-section"><h2>Movimientos de inventario</h2>{item?.movements.length ? <table className="erp-table"><thead><tr><th>Fecha</th><th>Tipo</th><th>Cantidad</th><th>Referencia</th><th>Usuario</th></tr></thead><tbody>{item.movements.map((movement) => <tr key={movement.id}><td>{new Intl.DateTimeFormat("es-AR", { dateStyle: "short", timeStyle: "short" }).format(new Date(movement.occurredAt))}</td><td>{movement.type}</td><td>{movement.quantity > 0 ? "+" : ""}{movement.quantity}</td><td>{movement.reason}</td><td>{movement.createdBy}</td></tr>)}</tbody></table> : <Empty text="No hay movimientos de inventario para este producto." />}</section></section>; }
export function SuppliersTab() { return <section className="erp-tab-content"><div className="erp-column"><h2>Proveedor principal</h2><p className="erp-note">Todavía no existe una relación producto–proveedor en el backend. Esta sección está preparada para conectarla sin afectar el catálogo actual.</p><button className="button secondary" type="button" disabled>Agregar proveedor</button></div><section className="erp-table-section"><h2>Proveedores</h2><Empty text="No hay proveedores asociados a este artículo." /></section></section>; }
export function StoreTab({ product }: { product: Product | null }) { return <section className="erp-tab-content"><div className="erp-column"><h2>Publicación en tienda</h2><label className="toggle"><input type="checkbox" checked={product?.active ?? true} readOnly /><span aria-hidden="true" /><div><strong>Publicado en tienda</strong><small>El catálogo público usa el estado activo del producto.</small></div></label><label className="toggle"><input type="checkbox" disabled /><span aria-hidden="true" /><div><strong>Destacado</strong><small>Próximamente configurable.</small></div></label></div><div className="store-preview"><p className="eyebrow">VISTA EN TIENDA</p><div className="store-preview-image">{product?.imageUrl ? <img src={product.imageUrl} alt="" /> : "Sin imagen"}</div><strong>{product?.name ?? "Producto"}</strong><span>{product?.price === undefined ? "Sin precio" : money.format(product.price)}</span><small>{product?.availableStock ? "Disponible" : "Sin stock"}</small></div></section>; }
export function SettingsTab({ product }: { product: Product | null }) { return <section className="erp-tab-content settings-list"><Metric label="ID interno" value={product?.id ?? "Se asigna al crear"} /><Metric label="SKU" value={product?.sku ?? "Se genera al crear"} /><Metric label="EAN" value={product?.barcode || "—"} /><Metric label="Última actualización" value={product ? new Intl.DateTimeFormat("es-AR", { dateStyle: "medium", timeStyle: "short" }).format(new Date(product.updatedAt)) : "—"} /></section>; }
function Metric({ label, value }: { label: string; value: string }) { return <div className="erp-metric"><span>{label}</span><strong>{value}</strong></div>; } function Empty({ text }: { text: string }) { return <p className="erp-empty">{text}</p>; }
