"use client";
/* eslint-disable @next/next/no-img-element */
import { useRef, useState, type DragEvent } from "react";
import { productApi } from "@/app/lib/product-api";
import { PRODUCT_IMAGE_ACCEPT, validateProductImage } from "@/app/lib/product-image-rules.js";
import type { ProductImage } from "@/app/lib/product-contract";

type UploadItem = { id: string; name: string; preview: string; state: "waiting" | "uploading" | "done" | "error"; error?: string };
export function ProductImagesTab({ productId, productName, initialImages, disabled, onImagesChange }: { productId: string; productName: string; initialImages: ProductImage[]; disabled: boolean; onImagesChange: (images: ProductImage[]) => void }) {
  const [images, setImages] = useState(initialImages); const [uploads, setUploads] = useState<UploadItem[]>([]); const [pending, setPending] = useState(""); const [error, setError] = useState(""); const [dragging, setDragging] = useState(false); const input = useRef<HTMLInputElement>(null);
  const commit = (next: ProductImage[]) => { setImages(next); onImagesChange(next); };
  const upload = async (files: File[]) => { const batch = files.map((file) => ({ file, item: { id: crypto.randomUUID(), name: file.name, preview: URL.createObjectURL(file), state: "waiting" as const, error: validateProductImage(file) || undefined } })); setUploads(batch.map(({ item }) => ({ ...item, state: item.error ? "error" : item.state }))); setError(""); for (const { file, item } of batch) { if (item.error) continue; setUploads((current) => current.map((row) => row.id === item.id ? { ...row, state: "uploading" } : row)); try { const next = await productApi.uploadProductImage(productId, file, productName); commit(next); setUploads((current) => current.map((row) => row.id === item.id ? { ...row, state: "done" } : row)); } catch (cause) { const message = cause instanceof Error ? cause.message : "No pudimos subir esta foto."; setUploads((current) => current.map((row) => row.id === item.id ? { ...row, state: "error", error: message } : row)); } } if (input.current) input.current.value = ""; };
  const reorder = async (next: ProductImage[], action: string) => { setPending(action); setError(""); try { commit(await productApi.reorderProductImages(productId, next.map((image) => image.id))); } catch (cause) { setError(cause instanceof Error ? cause.message : "No pudimos reordenar las fotos."); } finally { setPending(""); } };
  const move = (index: number, offset: number) => { const next = [...images]; const [image] = next.splice(index, 1); next.splice(index + offset, 0, image); void reorder(next, image.id); }; const makePrimary = (index: number) => { const next = [...images]; const [image] = next.splice(index, 1); next.unshift(image); void reorder(next, image.id); };
  const remove = async (image: ProductImage) => { if (!window.confirm("¿Querés eliminar esta foto? Esta acción no se puede deshacer.")) return; setPending(image.id); setError(""); try { commit(await productApi.deleteProductImage(productId, image.id)); } catch (cause) { setError(cause instanceof Error ? cause.message : "No pudimos eliminar la foto."); } finally { setPending(""); } };
  const drop = (event: DragEvent<HTMLDivElement>) => { event.preventDefault(); setDragging(false); if (!disabled) void upload(Array.from(event.dataTransfer.files)); };
  return <section className="product-images-tab" aria-labelledby="product-images-title"><header><div><p className="eyebrow">MULTIMEDIA</p><h2 id="product-images-title">Fotos del producto</h2><p>La primera foto se usa como principal en el catálogo y la tienda.</p></div><button type="button" className="button primary" disabled={disabled} onClick={() => input.current?.click()}>Seleccionar fotos</button></header>{error && <div className="form-summary" role="alert"><strong>No pudimos actualizar las fotos</strong><span>{error}</span></div>}<div className={`product-image-dropzone ${dragging ? "dragging" : ""}`} onDragEnter={(event) => { event.preventDefault(); setDragging(true); }} onDragOver={(event) => event.preventDefault()} onDragLeave={(event) => { if (!event.currentTarget.contains(event.relatedTarget as Node)) setDragging(false); }} onDrop={drop}><input ref={input} className="sr-only" type="file" accept={PRODUCT_IMAGE_ACCEPT} multiple disabled={disabled} onChange={(event) => void upload(Array.from(event.target.files ?? []))}/><strong>Arrastrá las fotos acá</strong><span>o usá “Seleccionar fotos” · JPEG, PNG o WebP · máximo 5 MB por archivo</span></div>{uploads.length > 0 && <section className="product-upload-list" aria-label="Progreso de las cargas" aria-live="polite">{uploads.map((item) => <article key={item.id}><img src={item.preview} alt=""/><div><strong>{item.name}</strong><span className={item.state === "error" ? "upload-error" : ""}>{item.error ?? ({ waiting: "En espera", uploading: "Subiendo…", done: "Carga completa", error: "Error" }[item.state])}</span></div>{item.state === "uploading" && <progress aria-label={`Subiendo ${item.name}`}/>}</article>)}</section>}{images.length === 0 ? <div className="product-images-empty"><strong>Todavía no hay fotos</strong><span>Subí una o más para mostrar el producto en el catálogo.</span></div> : <div className="product-images-grid">{images.map((image, index) => <article key={image.id} className="product-image-card"><div className="product-image-preview"><img src={image.url} alt={image.altText || `${productName}, foto ${index + 1}`}/>{index === 0 && <span>Principal</span>}</div><div className="product-image-actions">{index > 0 && <button type="button" disabled={disabled || !!pending} onClick={() => makePrimary(index)}>Hacer principal</button>}<div><button type="button" aria-label={`Mover foto ${index + 1} a la izquierda`} disabled={disabled || !!pending || index === 0} onClick={() => move(index, -1)}>←</button><button type="button" aria-label={`Mover foto ${index + 1} a la derecha`} disabled={disabled || !!pending || index === images.length - 1} onClick={() => move(index, 1)}>→</button><button type="button" className="danger" aria-label={`Eliminar foto ${index + 1}`} disabled={disabled || !!pending} onClick={() => void remove(image)}>{pending === image.id ? "…" : "Eliminar"}</button></div></div></article>)}</div>}</section>;
}
