"use client";
/* eslint-disable react-hooks/set-state-in-effect */
import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { getStoredUser } from "@/app/lib/auth-api";
import { invoiceApi } from "@/app/lib/invoice-api";
import { invoiceStatus } from "@/app/lib/invoice-rules";
import type { InvoicePaymentStatus, SupplierInvoiceSummary } from "@/app/lib/invoice-contract";
import { supplierApi } from "@/app/lib/supplier-api";
import { StatusBadge } from "@/app/components/ui/status-badge";
const money = (v: string, c = "ARS") => new Intl.NumberFormat("es-AR", { style: "currency", currency: c }).format(Number(v)); const date = (v: string) => new Intl.DateTimeFormat("es-AR", { dateStyle: "medium" }).format(new Date(`${v}T12:00:00`));
export function InvoiceList() { const [items, setItems] = useState<SupplierInvoiceSummary[]>([]), [suppliers, setSuppliers] = useState<Array<{id:string;name:string}>>([]), [loading, setLoading] = useState(true), [error, setError] = useState(""), [filter, setFilter] = useState<{supplierId:string;paymentStatus:InvoicePaymentStatus|"";q:string;overdue:boolean}>({supplierId:"",paymentStatus:"",q:"",overdue:false}), [summary, setSummary] = useState<Awaited<ReturnType<typeof invoiceApi.summary>> | null>(null);
 const allowed = !process.env.NEXT_PUBLIC_SUPERX_API_BASE_URL || getStoredUser()?.role === "admin";
 const load = useCallback(async () => { if (!allowed) return; setLoading(true); try { const result = await invoiceApi.list({ supplierId:filter.supplierId || undefined, paymentStatus: filter.overdue ? "OVERDUE" : filter.paymentStatus || undefined, q:filter.q || undefined }); setItems(result.items); setSummary(await invoiceApi.summary(filter.supplierId || undefined)); setError(""); } catch(e) { setError(e instanceof Error ? e.message : "No pudimos cargar facturas."); } finally { setLoading(false); } }, [allowed,filter]);
 useEffect(() => { void supplierApi.listSuppliers({pageSize:100}).then(x => setSuppliers(x.items)); }, []); useEffect(() => { void load(); }, [load]);
 if (!allowed) return <section className="workspace"><div className="state error-state"><strong>No autorizado</strong><span>Facturas de proveedor es sólo para administradores.</span></div></section>;
 const currencySummary = summary?.byCurrency ?? [];
 return <section className="workspace invoices-workspace"><header className="topbar"><div><p className="eyebrow">COMPRAS</p><h1>Facturas de proveedor</h1><p className="subtitle">Comprobantes, vencimientos y saldos informados por el servidor.</p></div><Link className="button primary" href="/facturas/nueva">Nueva factura</Link></header>{error && <div className="notice error" role="alert">{error}<button aria-label="Cerrar" onClick={()=>setError("")}>×</button></div>}<div className="invoice-summary">{currencySummary.length ? currencySummary.map(x=><div key={x.currency}><span>Abierto · {x.currency}</span><strong>{money(x.totalOpen,x.currency)}</strong><small>Vencido: {money(x.overdue.amount,x.currency)} · {x.overdue.count} doc.</small></div>) : <div><span>Total abierto</span><strong>—</strong><small>Sin documentos abiertos.</small></div>}</div><div className="filters invoice-filters"><label className="search">Buscar<input value={filter.q} onChange={e=>setFilter({...filter,q:e.target.value})} placeholder="Proveedor o comprobante" /></label><label className="field">Proveedor<select value={filter.supplierId} onChange={e=>setFilter({...filter,supplierId:e.target.value})}><option value="">Todos</option>{suppliers.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label className="field">Estado<select value={filter.paymentStatus} onChange={e=>setFilter({...filter,paymentStatus:e.target.value as InvoicePaymentStatus|""})}><option value="">Todos</option><option value="UNPAID">Sin pagar</option><option value="PARTIALLY_PAID">Pago parcial</option><option value="PAID">Pagada</option><option value="OVERDUE">Vencida</option></select></label><label className="invoice-check"><input type="checkbox" checked={filter.overdue} onChange={e=>setFilter({...filter,overdue:e.target.checked})}/> Sólo vencidas</label></div><div className="location-table-wrap"><table className="location-stock-table invoice-table"><thead><tr><th>Proveedor</th><th>Comprobante</th><th>Emisión / vencimiento</th><th>Total</th><th>Pagado</th><th>Saldo</th><th>Estado</th></tr></thead><tbody>{loading ? <tr><td colSpan={7}>Cargando facturas…</td></tr> : !items.length ? <tr><td colSpan={7}>No hay facturas para estos filtros.</td></tr> : items.map(x=>{const badge=invoiceStatus(x.status,x.paymentStatus); return <tr key={x.id}><td><Link href={`/facturas/${x.id}`}>{x.supplier.name || "—"}</Link></td><td><strong>{x.voucherType.replace("_"," ")}</strong><small>{x.pointOfSale}-{x.number}</small></td><td>{date(x.issueDate)}<small>Vence {date(x.dueDate)}</small></td><td>{money(x.total,x.currency)}</td><td>{money(x.paidAmount,x.currency)}</td><td><strong>{money(x.balance,x.currency)}</strong></td><td><StatusBadge tone={badge.tone === "active" ? "success" : badge.tone === "order-cancelled" ? "danger" : "neutral"} label={badge.label} /></td></tr>})}</tbody></table></div></section>; }
