"use client";

import { Notice } from "@/app/components/ui/notice";

import { FormEvent, useEffect, useMemo, useRef, useState } from "react";
import { ListSkeleton } from "@/app/components/list-skeleton";
import { InventoryDetailPanel } from "@/app/components/inventory/inventory-detail-panel";
import { InventoryFiltersBar } from "@/app/components/inventory/inventory-filters-bar";
import { InventoryGrid } from "@/app/components/inventory/inventory-grid";
import { InventoryList } from "@/app/components/inventory/inventory-list";
import { InventoryPageHeader } from "@/app/components/inventory/inventory-page-header";
import { InventoryStatsCards } from "@/app/components/inventory/inventory-stats-cards";
import { InventoryIcon } from "@/app/components/inventory/inventory-ui";
import { InventoryView, InventoryViewToggle } from "@/app/components/inventory/inventory-view-toggle";
import { roles } from "@/app/components/location-ui";
import { getStoredUser } from "@/app/lib/auth-api";
import { inventoryApi } from "@/app/lib/inventory-api";
import type { InventoryItem, InventoryMovementInput, InventoryStatus, Warehouse } from "@/app/lib/inventory-contract";
import type { UserRole } from "@/app/lib/product-contract";
import { getInventoryPermissions, getInventoryStatus, validateInventoryAdjustment } from "@/app/lib/inventory-rules";

type Notice = { kind: "success" | "error"; text: string } | null;
type Dialog = "adjust" | "confirm" | null;
type Adjustment = Pick<InventoryMovementInput, "quantity" | "reason">;
const actors: Record<UserRole, string> = { viewer: "Usuario de consulta", operator: "Operador actual", admin: "Administración actual" };

export function InventoryManager() {
  const [items, setItems] = useState<InventoryItem[]>([]), [warehouses, setWarehouses] = useState<Warehouse[]>([]), [selectedId, setSelectedId] = useState<string | null>(null), [role, setRole] = useState<UserRole>("viewer"), [query, setQuery] = useState(""), [warehouseId, setWarehouseId] = useState(""), [status, setStatus] = useState<"all" | InventoryStatus>("all"), [view, setView] = useState<InventoryView>("grid"), [loading, setLoading] = useState(true), [loadError, setLoadError] = useState(""), [notice, setNotice] = useState<Notice>(null), [dialog, setDialog] = useState<Dialog>(null), [adjustment, setAdjustment] = useState<Adjustment>({ quantity: 0, reason: "" }), [errors, setErrors] = useState<Partial<Record<keyof Adjustment, string>>>({}), [pending, setPending] = useState(false);
  const errorRef = useRef<HTMLDivElement>(null); const permissions = getInventoryPermissions(role); const selected = items.find((item) => item.id === selectedId) ?? null;
  const load = async () => { setLoading(true); setLoadError(""); try { if (!navigator.onLine) throw new Error("Sin conexión a internet. Verificá tu conexión y reintentá."); const [nextItems, nextWarehouses] = await Promise.all([inventoryApi.listInventory(), inventoryApi.listWarehouses()]); setItems(nextItems); setWarehouses(nextWarehouses); setSelectedId((current) => current && nextItems.some((item) => item.id === current) ? current : nextItems[0]?.id ?? null); } catch (error) { setLoadError(error instanceof Error ? error.message : "No se pudo cargar el inventario."); } finally { setLoading(false); } };
  useEffect(() => { // Sincronización inicial con el adaptador temporal de inventario.
    // eslint-disable-next-line react-hooks/set-state-in-effect
    void load();
  }, []); useEffect(() => { if (Object.keys(errors).length) errorRef.current?.focus(); }, [errors]);
  useEffect(() => { const user = getStoredUser(); // eslint-disable-next-line react-hooks/set-state-in-effect
    setRole(user?.role === "admin" ? "admin" : "viewer"); }, []);
  const visible = useMemo(() => { const normalized = query.trim().toLocaleLowerCase("es-AR"); return items.filter((item) => (!normalized || [item.productName, item.sku].some((value) => value.toLocaleLowerCase("es-AR").includes(normalized))) && (!warehouseId || item.warehouseId === warehouseId) && (status === "all" || getInventoryStatus(item) === status)); }, [items, query, warehouseId, status]);
  const warehouseName = (id: string) => warehouses.find((warehouse) => warehouse.id === id)?.name ?? "Depósito no disponible";
  const openAdjustment = () => { setAdjustment({ quantity: 0, reason: "" }); setErrors({}); setDialog("adjust"); };
  const reviewAdjustment = (event: FormEvent) => { event.preventDefault(); if (!selected) return; const nextErrors = validateInventoryAdjustment(adjustment, selected); setErrors(nextErrors); if (!Object.keys(nextErrors).length) setDialog("confirm"); };
  const createAdjustment = async () => { if (!selected) return; setPending(true); setNotice(null); try { const updated = await inventoryApi.createMovement({ inventoryItemId: selected.id, quantity: adjustment.quantity, reason: adjustment.reason, createdBy: actors[role] }); setItems((current) => current.map((item) => item.id === updated.id ? updated : item)); setDialog(null); setNotice({ kind: "success", text: `Se registró el ajuste de ${adjustment.quantity > 0 ? "+" : ""}${adjustment.quantity} unidades. El movimiento quedó auditado.` }); } catch (error) { setDialog(null); setNotice({ kind: "error", text: error instanceof Error ? error.message : "No se pudo registrar el movimiento." }); } finally { setPending(false); } };
  const updateThreshold = async (itemId: string, threshold: number) => { const updated = await inventoryApi.updateReorderThreshold(itemId, threshold); setItems((current) => current.map((item) => item.id === updated.id ? updated : item)); setNotice({ kind: "success", text: "Se actualizó el mínimo operativo." }); };
  return <section className="workspace inventory-workspace" id="inventario"><InventoryPageHeader role={role} canAdjust={permissions.adjust} disabled={!selected} onAdjust={openAdjustment} />{notice && <Notice kind={notice.kind} label={notice.kind === "success" ? "Listo" : "No se pudo completar"} onDismiss={() => setNotice(null)} dismissLabel="Cerrar mensaje" closeContent={<InventoryIcon name="close" />}>{notice.text}</Notice>}<div className="permission-note">Estás operando como <strong>{roles[role]}</strong>. {permissions.adjust ? "Los ajustes crean movimientos auditables; no editan el stock directamente." : "Sólo podés consultar existencias y movimientos."}</div><InventoryStatsCards items={items} /><section className="inventory-layout"><div className="inventory-content"><InventoryFiltersBar query={query} warehouseId={warehouseId} status={status} warehouses={warehouses} onQuery={setQuery} onWarehouse={setWarehouseId} onStatus={setStatus} onClear={() => { setQuery(""); setWarehouseId(""); setStatus("all"); }}><InventoryViewToggle view={view} onChange={setView} /></InventoryFiltersBar><div className="inventory-results-meta">Mostrando <strong>{visible.length}</strong> de <strong>{items.length}</strong> posiciones</div>{loading ? <ListSkeleton label="Cargando inventario…" /> : loadError ? <div className="state error-state"><strong>{loadError.startsWith("Sin conexión") ? "Sin conexión" : "No pudimos cargar el inventario"}</strong><span>{loadError}</span><button className="button secondary" onClick={() => void load()}>Reintentar</button></div> : visible.length === 0 ? <div className="state"><InventoryIcon name="boxes" /><strong>No encontramos posiciones</strong><span>Probá ajustar los filtros.</span></div> : view === "grid" ? <InventoryGrid items={visible} warehouses={warehouses} selectedId={selected?.id ?? null} onSelect={setSelectedId} /> : <InventoryList items={visible} warehouses={warehouses} selectedId={selected?.id ?? null} onSelect={setSelectedId} />}</div><InventoryDetailPanel selected={selected} allItems={items} warehouses={warehouses} canAdjust={permissions.adjust} onAdjust={openAdjustment} onClose={() => setSelectedId(null)} onUpdateThreshold={updateThreshold} /></section>{dialog === "adjust" && selected && <AdjustmentDialog item={selected} warehouseName={warehouseName(selected.warehouseId)} adjustment={adjustment} errors={errors} errorRef={errorRef} onChange={(key, value) => { setAdjustment((current) => ({ ...current, [key]: value })); setErrors((current) => ({ ...current, [key]: undefined })); }} onClose={() => setDialog(null)} onSubmit={reviewAdjustment} />}{dialog === "confirm" && selected && <ConfirmDialog item={selected} adjustment={adjustment} pending={pending} onCancel={() => setDialog("adjust")} onConfirm={() => void createAdjustment()} />}</section>;
}

function AdjustmentDialog({ item, warehouseName, adjustment, errors, errorRef, onChange, onClose, onSubmit }: { item: InventoryItem; warehouseName: string; adjustment: Adjustment; errors: Partial<Record<keyof Adjustment, string>>; errorRef: React.RefObject<HTMLDivElement | null>; onChange: <K extends keyof Adjustment>(key: K, value: Adjustment[K]) => void; onClose: () => void; onSubmit: (event: FormEvent) => void }) { const messages = Object.values(errors).filter(Boolean); return <div className="modal-backdrop" role="presentation"><section className="modal inventory-modal" role="dialog" aria-modal="true" aria-labelledby="adjustment-title"><header><div><p className="eyebrow">INVENTARIO / MOVIMIENTO</p><h2 id="adjustment-title">Ajustar stock</h2></div><button className="icon-button" aria-label="Cerrar ajuste" onClick={onClose}><InventoryIcon name="close" /></button></header><p className="modal-lede"><strong>{item.productName}</strong><br />{warehouseName} · Disponible: {item.onHand} unidades.</p><form onSubmit={onSubmit} noValidate>{messages.length > 0 && <div className="form-summary" ref={errorRef} tabIndex={-1} role="alert"><strong>Revisá el ajuste</strong>{messages.map((message) => <span key={message}>{message}</span>)}</div>}<label className="field"><span>Variación de unidades <b aria-hidden="true">*</b></span><input id="quantity" type="number" step="1" value={adjustment.quantity || ""} onChange={(event) => onChange("quantity", Number(event.target.value))} aria-invalid={Boolean(errors.quantity)} aria-describedby={errors.quantity ? "quantity-error" : undefined} autoFocus /><small>Usá un valor positivo para sumar o negativo para descontar.</small>{errors.quantity && <small id="quantity-error" role="alert">{errors.quantity}</small>}</label><label className="field reason-field"><span>Motivo <b aria-hidden="true">*</b></span><input id="reason" value={adjustment.reason} onChange={(event) => onChange("reason", event.target.value)} aria-invalid={Boolean(errors.reason)} aria-describedby={errors.reason ? "reason-error" : undefined} placeholder="Ej.: Diferencia de conteo físico" />{errors.reason && <small id="reason-error" role="alert">{errors.reason}</small>}</label><footer><button type="button" className="button ghost" onClick={onClose}>Cancelar</button><button className="button primary">Revisar ajuste</button></footer></form></section></div>; }
function ConfirmDialog({ item, adjustment, pending, onCancel, onConfirm }: { item: InventoryItem; adjustment: Adjustment; pending: boolean; onCancel: () => void; onConfirm: () => void }) { return <div className="modal-backdrop" role="presentation"><section className="modal confirm" role="alertdialog" aria-modal="true" aria-labelledby="confirm-title"><h2 id="confirm-title">¿Confirmar movimiento?</h2><p>Se registrará un ajuste de <strong>{adjustment.quantity > 0 ? "+" : ""}{adjustment.quantity} unidades</strong> para “{item.productName}”. El stock quedará en {item.onHand + adjustment.quantity} unidades y el motivo será auditable.</p><footer><button className="button ghost" onClick={onCancel} disabled={pending}>Volver</button><button className="button primary" onClick={onConfirm} disabled={pending}>{pending ? "Registrando…" : "Confirmar ajuste"}</button></footer></section></div>; }
