"use client";

import { useEffect, useMemo, useState } from "react";
import { ListSkeleton } from "@/app/components/list-skeleton";
import { Notice } from "@/app/components/ui/notice";
import { ProductGeneralTab } from "@/app/components/products/product-general-tab";
import { CatalogEntityDialog } from "@/app/components/products/catalog-entity-dialog";
import { ProductHeader } from "@/app/components/products/product-header";
import { ProductImagesTab } from "@/app/components/products/product-images-tab";
import { InventoryTab, PricingTab, SettingsTab, StoreTab, SuppliersTab } from "@/app/components/products/product-operation-tabs";
import { ProductSmartButtons, ProductTabs, type ProductTab } from "@/app/components/products/product-smart-buttons";
import { SupplierDialog } from "@/app/components/suppliers/supplier-form";
import { inventoryApi } from "@/app/lib/inventory-api";
import { priceApi } from "@/app/lib/price-api";
import { productApi } from "@/app/lib/product-api";
import { supplierApi } from "@/app/lib/supplier-api";
import type { Brand, Category, Product, ProductInput, Unit, UserRole } from "@/app/lib/product-contract";
import { getPermissions, validateProduct } from "@/app/lib/product-rules";

const empty: ProductInput = { name: "", description: "", barcode: "", categoryId: "", brandId: "", unit: "", imageUrl: "", active: true };
export function ProductDetail({ mode, productId }: { mode: "create" | "edit"; productId?: string }) {
  const [product, setProduct] = useState<Product | null>(null); const [categories, setCategories] = useState<Category[]>([]); const [brands, setBrands] = useState<Brand[]>([]); const [units, setUnits] = useState<Unit[]>([]); const [inventory, setInventory] = useState<Awaited<ReturnType<typeof inventoryApi.listInventory>>[number] | null>(null); const [price, setPrice] = useState<Awaited<ReturnType<typeof priceApi.listPrices>>[number] | null>(null); const [form, setForm] = useState<ProductInput>(empty); const [role, setRole] = useState<UserRole>("admin"); const [tab, setTab] = useState<ProductTab>("general"); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [statusPending, setStatusPending] = useState(false); const [error, setError] = useState(""); const [notice, setNotice] = useState(""); const [catalogDialog, setCatalogDialog] = useState<"category" | "brand" | "unit" | null>(null); const [supplierDialog, setSupplierDialog] = useState(false); const [relatedPending, setRelatedPending] = useState(false);
  const permissions = getPermissions(role); const canSave = mode === "create" ? permissions.create : permissions.update; const dirty = useMemo(() => product ? JSON.stringify(form) !== JSON.stringify({ name: product.name, description: product.description, barcode: product.barcode, categoryId: product.categoryId, brandId: product.brandId, unit: product.unit, imageUrl: product.imageUrl, active: product.active }) : form.name.length > 0, [form, product]);
  const load = async () => { setLoading(true); setError(""); try { const [record, cats, brandList, unitList, stockRows, priceRows] = await Promise.all([mode === "edit" ? productApi.getProduct(productId!) : Promise.resolve(null), productApi.listCategories(), productApi.listBrands(), productApi.listUnits(), inventoryApi.listInventory(), priceApi.listPrices()]); setProduct(record); setCategories(cats); setBrands(brandList); setUnits(unitList); if (record) { setForm({ name: record.name, description: record.description, barcode: record.barcode, categoryId: record.categoryId, brandId: record.brandId, unit: record.unit, imageUrl: record.imageUrl, active: record.active }); setInventory(stockRows.find((item) => item.productId === record.id) ?? null); setPrice(priceRows.find((item) => item.productId === record.id) ?? null); } } catch (cause) { setError(cause instanceof Error ? cause.message : "No se pudo cargar la ficha."); } finally { setLoading(false); } };
  useEffect(() => { // eslint-disable-next-line react-hooks/set-state-in-effect
    void load(); // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [mode, productId]);
  useEffect(() => { const onBeforeUnload = (event: BeforeUnloadEvent) => { if (dirty) { event.preventDefault(); event.returnValue = ""; } }; window.addEventListener("beforeunload", onBeforeUnload); return () => window.removeEventListener("beforeunload", onBeforeUnload); }, [dirty]);
  const change = <K extends keyof ProductInput>(key: K, value: ProductInput[K]) => setForm((current) => ({ ...current, [key]: value }));
  const save = async () => { const errors = validateProduct(form, product ? [product] : [], product?.id); const message = Object.values(errors)[0]; if (message) { setError(message); return; } setSaving(true); setError(""); try { const saved = mode === "create" ? await productApi.createProduct(form) : await productApi.updateProduct(product!.id, form); setProduct(saved); setNotice(mode === "create" ? "Producto creado correctamente." : "Cambios guardados correctamente."); } catch (cause) { setError(cause instanceof Error ? cause.message : "No se pudo guardar el producto."); } finally { setSaving(false); } };
  const duplicate = () => { if (!product) return; setForm((current) => ({ ...current, name: `${current.name} (copia)`, barcode: "" })); setProduct(null); setNotice("Se preparó una copia. Revisá los datos y guardala como producto nuevo."); };
  const toggleStatus = async () => { if (!product) return; const nextActive = !product.active; setStatusPending(true); setError(""); try { const updated = await productApi.setProductStatus(product.id, nextActive); setProduct(updated); setForm((current) => ({ ...current, active: updated.active })); setNotice(updated.active ? "Producto activado correctamente." : "Producto desactivado correctamente."); } catch (cause) { setError(cause instanceof Error ? cause.message : "No se pudo actualizar el estado del producto."); } finally { setStatusPending(false); } };
  const createCatalogEntity = async (value: { name: string; code?: string }) => { if (!catalogDialog) return; setRelatedPending(true); try { if (catalogDialog === "category") { const created = await productApi.createCategory({ name: value.name }); setCategories((current) => [...current, created]); change("categoryId", created.id); } else if (catalogDialog === "brand") { const created = await productApi.createBrand({ name: value.name }); setBrands((current) => [...current, created]); change("brandId", created.id); } else { const created = await productApi.createUnit({ name: value.name, code: value.code ?? "" }); setUnits((current) => [...current, created]); change("unit", created.code); } setNotice(`${value.name} se creó y quedó seleccionado.`); setCatalogDialog(null); } finally { setRelatedPending(false); } };
  const displayProduct = product ? { ...product, price: price?.amount ?? product.price, availableStock: inventory?.onHand ?? product.availableStock } : null;
  return <section className="workspace product-erp-page" id="productos"><ProductHeader product={displayProduct} name={form.name} role={role} onRole={setRole} saving={saving} dirty={dirty} onSave={() => void save()} onDuplicate={duplicate} onToggleStatus={() => void toggleStatus()} statusPending={statusPending} />{notice && <Notice kind="success" label="Listo" onDismiss={() => setNotice("")} dismissLabel="Cerrar">{notice}</Notice>}{error && <div className="form-summary" role="alert"><strong>Revisá la ficha</strong><span>{error}</span></div>}{loading ? <ListSkeleton label="Cargando ficha de producto…" /> : <div><ProductSmartButtons stock={displayProduct?.availableStock} price={price?.amount} tab={tab} onTab={setTab} /><ProductTabs active={tab} onChange={setTab} />{tab === "general" && <ProductGeneralTab form={form} categories={categories} brands={brands} units={units} disabled={!canSave || saving} onChange={change} onCreateCategory={() => setCatalogDialog("category")} onCreateBrand={() => setCatalogDialog("brand")} onCreateUnit={() => setCatalogDialog("unit")} onCreateSupplier={() => setSupplierDialog(true)} />}{tab === "photos" && product && <ProductImagesTab productId={product.id} productName={product.name} initialImages={product.images} disabled={!permissions.update} onImagesChange={(images) => setProduct((current) => current ? { ...current, images, imageUrl: images[0]?.url ?? "" } : current)} />}{tab === "prices" && <PricingTab price={price} />}{tab === "inventory" && <InventoryTab item={inventory} />}{tab === "suppliers" && <SuppliersTab product={displayProduct} units={units} />}{tab === "store" && <StoreTab product={displayProduct} />}{tab === "settings" && <SettingsTab product={displayProduct} />}<footer className="product-erp-footer"><span>{dirty ? "Cambios sin guardar" : "Todos los cambios están guardados"}</span><button type="button" className="button primary" onClick={() => void save()} disabled={!canSave || saving}>{saving ? "Guardando…" : "Guardar"}</button></footer></div>}{catalogDialog && <CatalogEntityDialog kind={catalogDialog} pending={relatedPending} onClose={() => setCatalogDialog(null)} onSubmit={createCatalogEntity} />}{supplierDialog && <SupplierDialog pending={relatedPending} onClose={() => setSupplierDialog(false)} onSubmit={async (input) => { setRelatedPending(true); try { const created = await supplierApi.createSupplier(input); setNotice(`${created.name} se creó correctamente. Guardá el producto y vinculalo desde la pestaña Proveedores.`); setSupplierDialog(false); } catch (cause) { setError(cause instanceof Error ? cause.message : "No se pudo crear el proveedor."); } finally { setRelatedPending(false); } }} />}</section>;
}
