"use client";
/* eslint-disable @next/next/no-img-element */

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { ListSkeleton } from "@/app/components/list-skeleton";
import { LocationIcon, RolePicker, roles } from "@/app/components/location-ui";
import { productApi } from "@/app/lib/product-api";
import type { Brand, Category, Product, ProductFilters, Unit, UserRole } from "@/app/lib/product-contract";
import { getPermissions } from "@/app/lib/product-rules";

const money = new Intl.NumberFormat("es-AR", { style: "currency", currency: "ARS", maximumFractionDigits: 0 });
const date = new Intl.DateTimeFormat("es-AR", { day: "2-digit", month: "short", year: "numeric" });
function ProductImage({ product }: { product: Product }) { return <span className="catalog-product-image">{product.imageUrl ? <img src={product.imageUrl} alt="" /> : <span aria-hidden="true">{product.name.slice(0, 1)}</span>}</span>; }

export function ProductManager() {
  const [products, setProducts] = useState<Product[]>([]); const [categories, setCategories] = useState<Category[]>([]); const [brands, setBrands] = useState<Brand[]>([]); const [units, setUnits] = useState<Unit[]>([]);
  const [role, setRole] = useState<UserRole>("admin"); const [filters, setFilters] = useState<ProductFilters>({ status: "all", stock: "all", sort: "name_asc", page: 1, pageSize: 25 }); const [total, setTotal] = useState(0); const [loading, setLoading] = useState(true); const [loadError, setLoadError] = useState(""); const permissions = getPermissions(role);
  const load = async (next = filters) => { setLoading(true); setLoadError(""); try { if (!navigator.onLine) throw new Error("Sin conexión a internet. Verificá tu conexión y reintentá."); const [page, nextCategories, nextBrands, nextUnits] = await Promise.all([productApi.listProductPage(next), productApi.listCategories(), productApi.listBrands(), productApi.listUnits()]); setProducts(page.items); setTotal(page.total); setCategories(nextCategories); setBrands(nextBrands); setUnits(nextUnits); } catch (error) { setLoadError(error instanceof Error ? error.message : "No se pudo cargar el catálogo. Intentá nuevamente."); } finally { setLoading(false); } };
  useEffect(() => {
    // The catalog query is synchronized with its filter state.
    // eslint-disable-next-line react-hooks/set-state-in-effect
    void load();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [filters]);
  const visibleProducts = useMemo(() => filters.status === "all" ? products : products.filter((product) => filters.status === "active" ? product.active : !product.active), [products, filters.status]);
  const updateFilter = <K extends keyof ProductFilters>(key: K, value: ProductFilters[K]) => setFilters((current) => ({ ...current, [key]: value, page: key === "page" ? Number(value) : 1 }));
  const totalPages = Math.max(1, Math.ceil(total / (filters.pageSize ?? 25))); const active = products.filter((item) => item.active).length; const outOfStock = products.filter((item) => item.availableStock === 0).length;
  return <section className="workspace products-workspace" id="productos">
    <header className="topbar products-topbar"><div><p className="eyebrow">CATÁLOGO / ARTÍCULOS</p><h1>Productos</h1><p className="subtitle">Catálogo maestro, precios, disponibilidad y datos de venta en una sola vista.</p></div><div className="top-actions"><RolePicker role={role} onChange={setRole} />{permissions.create && <Link className="button primary" href="/productos/nuevo"><LocationIcon name="plus" /> Nuevo</Link>}</div></header>
    <div className="permission-note">Estás operando como <strong>{roles[role]}</strong>. {permissions.update ? "Podés abrir y actualizar las fichas del catálogo." : "Sólo podés consultar el catálogo."}</div>
    <section className="product-pulse" aria-label="Resumen del catálogo"><div><span>ARTÍCULOS</span><strong>{total}</strong><small>resultados del catálogo</small></div><div><span>ACTIVOS EN ESTA VISTA</span><strong>{active}</strong><small>listos para vender</small></div><div><span>SIN STOCK EN ESTA VISTA</span><strong>{outOfStock}</strong><small>requieren reposición</small></div><div><span>UNIDADES DE VENTA</span><strong>{units.length}</strong><small>configuradas en catálogo</small></div></section>
    <section className="product-catalog" aria-label="Listado de productos"><header className="product-catalog-head"><div><h2>Artículos</h2><span>Usá filtros y abrí una ficha para editar en detalle.</span></div><label className="product-search"><LocationIcon name="search" /><span className="sr-only">Buscar productos</span><input value={filters.query ?? ""} onChange={(event) => updateFilter("query", event.target.value)} placeholder="Buscar nombre, referencia o código…" /></label></header>
      <div className="product-filterbar"><label>Estado<select value={filters.status} onChange={(event) => updateFilter("status", event.target.value as ProductFilters["status"])}><option value="all">Todos</option><option value="active">Activos</option><option value="inactive">Archivados</option></select></label><label>Categoría<select value={filters.categoryId ?? ""} onChange={(event) => updateFilter("categoryId", event.target.value)}><option value="">Todas</option>{categories.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Marca<select value={filters.brandId ?? ""} onChange={(event) => updateFilter("brandId", event.target.value)}><option value="">Todas</option>{brands.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Disponibilidad<select value={filters.stock} onChange={(event) => updateFilter("stock", event.target.value as ProductFilters["stock"])}><option value="all">Cualquier stock</option><option value="in_stock">Con stock</option><option value="out_of_stock">Sin stock</option></select></label><label>Orden<select value={filters.sort} onChange={(event) => updateFilter("sort", event.target.value as ProductFilters["sort"])}><option value="name_asc">Nombre A–Z</option><option value="name_desc">Nombre Z–A</option><option value="newest">Actualizados primero</option><option value="oldest">Más antiguos</option></select></label><button className="link-button" onClick={() => setFilters({ status: "all", stock: "all", sort: "name_asc", page: 1, pageSize: 25 })}>Restablecer</button></div>
      {loading ? <ListSkeleton label="Cargando catálogo…" /> : loadError ? <div className="state error-state"><strong>No pudimos cargar los productos</strong><span>{loadError}</span><button className="button secondary" onClick={() => void load()}>Reintentar</button></div> : visibleProducts.length === 0 ? <div className="state"><LocationIcon name="warehouse" /><strong>No encontramos artículos</strong><span>Probá ajustar los filtros o creá un producto nuevo.</span></div> : <div className="product-table-wrap"><table className="product-table"><thead><tr><th aria-label="Imagen" /><th>Producto</th><th>Referencia interna</th><th>Categoría</th><th>Precio de venta</th><th>Disponible</th><th>Estado</th><th>Actualizado</th></tr></thead><tbody>{visibleProducts.map((product) => <tr key={product.id}><td><ProductImage product={product} /></td><td><Link href={`/productos/${encodeURIComponent(product.slug)}`} className="product-table-name"><strong>{product.name}</strong><span>{product.barcode || "Sin código de barras"} · {product.brandName}</span></Link></td><td><span className="product-ref">{product.sku}</span><small>{product.unit}</small></td><td>{product.categoryName}</td><td className={product.price === undefined ? "product-no-price" : ""}>{product.price === undefined ? "Sin precio" : money.format(product.price)}</td><td><span className={`product-stock ${product.availableStock === 0 ? "product-stock-out" : ""}`}>{product.availableStock === undefined ? "—" : product.availableStock}</span></td><td><span className={`status ${product.active ? "active" : "inactive"}`}>{product.active ? "Activo" : "Archivado"}</span></td><td><time>{date.format(new Date(product.updatedAt))}</time></td></tr>)}</tbody></table></div>}
      {!loading && !loadError && total > 0 && <footer className="product-pagination"><span>Mostrando {visibleProducts.length} de {total} artículos</span><div><button className="button secondary" disabled={(filters.page ?? 1) <= 1} onClick={() => updateFilter("page", (filters.page ?? 1) - 1)}>Anterior</button><strong>Página {filters.page} de {totalPages}</strong><button className="button secondary" disabled={(filters.page ?? 1) >= totalPages} onClick={() => updateFilter("page", (filters.page ?? 1) + 1)}>Siguiente</button></div></footer>}
    </section>
  </section>;
}
