"use client";

import { useEffect, useMemo, useState } from "react";
import { ListSkeleton } from "@/app/components/list-skeleton";
import { ProductGeneralTab } from "@/app/components/products/product-general-tab";
import { ProductHeader } from "@/app/components/products/product-header";
import { InventoryTab, PricingTab, SettingsTab, StoreTab, SuppliersTab } from "@/app/components/products/product-operation-tabs";
import { ProductSmartButtons, ProductTabs, type ProductTab } from "@/app/components/products/product-smart-buttons";
import { inventoryApi } from "@/app/lib/inventory-api";
import { priceApi } from "@/app/lib/price-api";
import { productApi } from "@/app/lib/product-api";
import type { Brand, Category, Product, ProductInput, Unit, UserRole } from "@/app/lib/product-contract";
import { getPermissions, validateProduct } from "@/app/lib/product-rules";

const empty: ProductInput = { name: "", description: "", barcode: "", categoryId: "", brandId: "", unit: "", imageUrl: "", active: true };
export function ProductDetail({ mode, productId }: { mode: "create" | "edit"; productId?: string }) {
  const [product, setProduct] = useState<Product | null>(null); const [categories, setCategories] = useState<Category[]>([]); const [brands, setBrands] = useState<Brand[]>([]); const [units, setUnits] = useState<Unit[]>([]); const [inventory, setInventory] = useState<Awaited<ReturnType<typeof inventoryApi.listInventory>>[number] | null>(null); const [price, setPrice] = useState<Awaited<ReturnType<typeof priceApi.listPrices>>[number] | null>(null); const [form, setForm] = useState<ProductInput>(empty); const [role, setRole] = useState<UserRole>("admin"); const [tab, setTab] = useState<ProductTab>("general"); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(""); const [notice, setNotice] = useState("");
  const permissions = getPermissions(role); const canSave = mode === "create" ? permissions.create : permissions.update; const dirty = useMemo(() => product ? JSON.stringify(form) !== JSON.stringify({ name: product.name, description: product.description, barcode: product.barcode, categoryId: product.categoryId, brandId: product.brandId, unit: product.unit, imageUrl: product.imageUrl, active: product.active }) : form.name.length > 0, [form, product]);
  const load = async () => { setLoading(true); setError(""); try { const [record, cats, brandList, unitList, stockRows, priceRows] = await Promise.all([mode === "edit" ? productApi.getProduct(productId!) : Promise.resolve(null), productApi.listCategories(), productApi.listBrands(), productApi.listUnits(), inventoryApi.listInventory(), priceApi.listPrices()]); setProduct(record); setCategories(cats); setBrands(brandList); setUnits(unitList); if (record) { setForm({ name: record.name, description: record.description, barcode: record.barcode, categoryId: record.categoryId, brandId: record.brandId, unit: record.unit, imageUrl: record.imageUrl, active: record.active }); setInventory(stockRows.find((item) => item.productId === record.id) ?? null); setPrice(priceRows.find((item) => item.productId === record.id) ?? null); } } catch (cause) { setError(cause instanceof Error ? cause.message : "No se pudo cargar la ficha."); } finally { setLoading(false); } };
  useEffect(() => { // eslint-disable-next-line react-hooks/set-state-in-effect
    void load(); // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [mode, productId]);
  useEffect(() => { const onBeforeUnload = (event: BeforeUnloadEvent) => { if (dirty) { event.preventDefault(); event.returnValue = ""; } }; window.addEventListener("beforeunload", onBeforeUnload); return () => window.removeEventListener("beforeunload", onBeforeUnload); }, [dirty]);
  const change = <K extends keyof ProductInput>(key: K, value: ProductInput[K]) => setForm((current) => ({ ...current, [key]: value }));
  const save = async () => { const errors = validateProduct(form, product ? [product] : [], product?.id); const message = Object.values(errors)[0]; if (message) { setError(message); return; } setSaving(true); setError(""); try { const saved = mode === "create" ? await productApi.createProduct(form) : await productApi.updateProduct(product!.id, form); setProduct(saved); setNotice(mode === "create" ? "Producto creado correctamente." : "Cambios guardados correctamente."); } catch (cause) { setError(cause instanceof Error ? cause.message : "No se pudo guardar el producto."); } finally { setSaving(false); } };
  const duplicate = () => { if (!product) return; setForm((current) => ({ ...current, name: `${current.name} (copia)`, barcode: "" })); setProduct(null); setNotice("Se preparó una copia. Revisá los datos y guardala como producto nuevo."); };
  const displayProduct = product ? { ...product, price: price?.amount ?? product.price, availableStock: inventory?.onHand ?? product.availableStock } : null;
  return <section className="workspace product-erp-page" id="productos"><ProductHeader product={displayProduct} name={form.name} role={role} onRole={setRole} saving={saving} dirty={dirty} onSave={() => void save()} onDuplicate={duplicate} />{notice && <div className="notice success" role="status"><span>Listo</span>{notice}<button onClick={() => setNotice("")} aria-label="Cerrar">×</button></div>}{error && <div className="form-summary" role="alert"><strong>Revisá la ficha</strong><span>{error}</span></div>}{loading ? <ListSkeleton label="Cargando ficha de producto…" /> : <div><ProductSmartButtons stock={displayProduct?.availableStock} price={price?.amount} tab={tab} onTab={setTab} /><ProductTabs active={tab} onChange={setTab} />{tab === "general" && <ProductGeneralTab form={form} categories={categories} brands={brands} units={units} disabled={!canSave || saving} onChange={change} />}{tab === "prices" && <PricingTab price={price} />}{tab === "inventory" && <InventoryTab item={inventory} />}{tab === "suppliers" && <SuppliersTab product={displayProduct} units={units} />}{tab === "store" && <StoreTab product={displayProduct} />}{tab === "settings" && <SettingsTab product={displayProduct} />}<footer className="product-erp-footer"><span>{dirty ? "Cambios sin guardar" : "Todos los cambios están guardados"}</span><button type="button" className="button primary" onClick={() => void save()} disabled={!canSave || saving}>{saving ? "Guardando…" : "Guardar"}</button></footer></div>}</section>;
}
