"use client";
import { useCallback, useEffect, useState } from "react";
import { getStoredUser, listUsers, updateUserRole, type ManagedUser, type UserRole } from "@/app/lib/auth-api";
import { Notice } from "./ui/notice";

const roles: Array<[UserRole, string]> = [["customer", "Cliente"], ["admin", "Administración"], ["picker", "Preparador"], ["driver", "Repartidor"], ["warehouse", "Depósito"]];
const date = new Intl.DateTimeFormat("es-AR", { dateStyle: "medium" });
export function UserManager() {
  const [users, setUsers] = useState<ManagedUser[]>([]), [query, setQuery] = useState(""), [role, setRole] = useState<UserRole | "">(""), [loading, setLoading] = useState(true), [error, setError] = useState(""), [busyId, setBusyId] = useState("");
  const me = getStoredUser();
  const load = useCallback(async () => { setLoading(true); try { const result = await listUsers({ q: query.trim() || undefined, role, pageSize: 100 }); setUsers(result.items); setError(""); } catch (cause) { setError(cause instanceof Error ? cause.message : "No pudimos cargar los usuarios."); } finally { setLoading(false); } }, [query, role]);
  useEffect(() => { const timer = setTimeout(() => void load(), 250); return () => clearTimeout(timer); }, [load]);
  const changeRole = async (user: ManagedUser, nextRole: UserRole) => { if (user.id === me?.id && user.role === "admin" && nextRole !== "admin") { setError("No podés quitarte tu propio acceso de Administración. Pedile el cambio a otra persona administradora."); return; } if (!window.confirm(`¿Cambiar el rol de ${user.email} a ${roles.find(([value]) => value === nextRole)?.[1]}?`)) return; setBusyId(user.id); try { const updated = await updateUserRole(user.id, nextRole); setUsers((current) => current.map((item) => item.id === user.id ? { ...item, ...updated } : item)); } catch (cause) { setError(cause instanceof Error ? cause.message : "No pudimos cambiar el rol."); } finally { setBusyId(""); } };
  return <section className="workspace"><header className="topbar"><div><p className="eyebrow">ADMINISTRACIÓN</p><h1>Usuarios</h1><p className="subtitle">Gestioná quién puede operar cada área de SuperX.</p></div></header>{error && <Notice kind="error" role="alert" onDismiss={() => setError("")}>{error}</Notice>}<section className="locations-filter-bar"><label className="search"><span className="sr-only">Buscar usuarios</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Buscar por email o nombre" /></label><label className="field"><span>Rol</span><select value={role} onChange={(event) => setRole(event.target.value as UserRole | "")}><option value="">Todos los roles</option>{roles.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label></section><section className="location-table-panel"><header><div><p className="eyebrow">EQUIPO</p><h2>{users.length} {users.length === 1 ? "usuario" : "usuarios"}</h2></div></header>{loading ? <div className="state">Cargando usuarios…</div> : <div className="location-table-wrap"><table className="location-stock-table"><thead><tr><th>Email</th><th>Nombre</th><th>Rol</th><th>Alta</th></tr></thead><tbody>{users.map((user) => <tr key={user.id}><td data-label="Email"><strong>{user.email}</strong>{user.id === me?.id && <small>Tu cuenta</small>}</td><td data-label="Nombre">{user.name || "—"}</td><td data-label="Rol"><select aria-label={`Rol de ${user.email}`} value={user.role} disabled={busyId === user.id || (user.id === me?.id && user.role === "admin")} onChange={(event) => void changeRole(user, event.target.value as UserRole)}>{roles.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></td><td data-label="Alta">{date.format(new Date(user.createdAt))}</td></tr>)}</tbody></table></div>}</section></section>;
}
