import test, { afterEach } from "node:test";
import assert from "node:assert/strict";
import React from "react";
import { cleanup, fireEvent, render, screen, waitFor, within } from "./picking-test-utils";
import { WithdrawalManager } from "../app/components/withdrawal-manager";
import { withdrawalApi } from "../app/lib/withdrawal-api";
import { UserManager } from "../app/components/user-manager";
import type { WithdrawalRequest } from "../app/lib/withdrawal-contract";
afterEach(cleanup);
const item: WithdrawalRequest = {id: "123", code: "ARR-000123", fullName: "Ana", email: "ana@example.com", phone: "1234567", orderNumber: "PX001", orderId: null, userId: null, reason: "Cambio de opinión", status: "PENDING", resolutionNote: null, createdAt: "2026-10-01T10:00:00Z", resolvedAt: null};
test("arrepentimientos pagina, reinicia al filtrar y guarda estado con nota", async (t) => {
  const loads: Array<{page?: number; status?: string}> = [];
  t.mock.method(withdrawalApi, "list", async (filters: Parameters<typeof withdrawalApi.list>[0]) => { loads.push(filters ?? {}); return {items: [item], total: 21, page: filters?.page, pageSize: 20}; });
  t.mock.method(withdrawalApi, "update", async (id: string, input: Parameters<typeof withdrawalApi.update>[1]) => { assert.equal(id, "123"); assert.deepEqual(input, {status: "RESOLVED", resolutionNote: "Reintegro coordinado"}); return {...item, ...input}; });
  render(<WithdrawalManager />);
  await screen.findByText("ARR-000123");
  fireEvent.click(screen.getByRole("button", {name: "Siguiente"}));
  await waitFor(() => assert.equal(loads.at(-1)?.page, 2));
  await waitFor(() => assert.equal((screen.getByRole("button", {name: "Anterior"}) as HTMLButtonElement).disabled, false));
  fireEvent.change(screen.getByLabelText("Estado"), {target: {value: "PENDING"}});
  await waitFor(() => assert.deepEqual(loads.at(-1), {status: "PENDING", page: 1, pageSize: 20}));
  await screen.findByRole("button", {name: "Ver detalle"});
  fireEvent.click(screen.getByRole("button", {name: "Ver detalle"}));
  const dialog = within(screen.getByRole("dialog"));
  assert.ok(dialog.getByText("Cambio de opinión"));
  fireEvent.change(dialog.getByLabelText("Estado"), {target: {value: "RESOLVED"}});
  fireEvent.change(dialog.getByLabelText("Nota de resolución (opcional)"), {target: {value: "Reintegro coordinado"}});
  fireEvent.click(dialog.getByRole("button", {name: "Guardar cambios"}));
  await screen.findByText("Solicitud actualizada.");
});
test("usuarios permite borrar datos, valida confirmación y confirma desactivación", async (t) => {
  const previous = process.env.NEXT_PUBLIC_SUPERX_API_BASE_URL;
  process.env.NEXT_PUBLIC_SUPERX_API_BASE_URL = "https://api.example";
  t.after(() => { if (previous === undefined) delete process.env.NEXT_PUBLIC_SUPERX_API_BASE_URL; else process.env.NEXT_PUBLIC_SUPERX_API_BASE_URL = previous; });
  window.sessionStorage.setItem("superx.access-user", JSON.stringify({ id: "admin1", email: "admin@example.com", role: "admin" }));
  t.after(() => window.sessionStorage.clear());
  const user = {id: "u1", email: "ana@example.com", name: "Ana", phone: "1234567", role: "picker", isActive: true, createdAt: item.createdAt};
  const writes: unknown[] = [];
  t.mock.method(globalThis, "fetch", async (_url: string | URL | Request, init?: RequestInit) => { if (init?.method === "PATCH") { writes.push(JSON.parse(init.body as string)); return Response.json({...user, name: null, phone: null}); } return Response.json({items: [user], total: 1, page: 1, pageSize: 100}); });
  t.mock.method(window, "confirm", () => false);
  render(<UserManager />);
  await screen.findByText("Activo");
  fireEvent.click(screen.getByRole("button", {name: "Desactivar"}));
  assert.equal(writes.length, 0);
  fireEvent.click(screen.getByRole("button", {name: "Editar datos"}));
  let dialog = within(screen.getByRole("dialog"));
  fireEvent.change(dialog.getByLabelText("Nombre"), {target: {value: ""}});
  fireEvent.change(dialog.getByLabelText("Teléfono"), {target: {value: ""}});
  fireEvent.click(dialog.getByRole("button", {name: "Guardar cambios"}));
  await screen.findByText("Datos actualizados.");
  assert.deepEqual(writes, [{email: user.email, name: null, phone: null}]);
  fireEvent.click(await screen.findByRole("button", {name: "Restablecer contraseña"}));
  dialog = within(screen.getByRole("dialog"));
  fireEvent.change(dialog.getByLabelText("Contraseña nueva"), {target: {value: "password123"}});
  fireEvent.change(dialog.getByLabelText("Confirmar contraseña"), {target: {value: "different"}});
  fireEvent.click(dialog.getByRole("button", {name: "Guardar cambios"}));
  await screen.findByText("Las contraseñas no coinciden.");
  assert.equal(writes.length, 1);
});
