"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { ListSkeleton } from "@/app/components/list-skeleton";
import { getStoredUser } from "@/app/lib/auth-api";
import { dashboardApi } from "@/app/lib/dashboard-api";
import type { DashboardDueItem, DashboardExpenseCategory, DashboardFilters, DashboardInvestment, DashboardKpis, DashboardPendingReceipt, DashboardSupplier, DashboardTreasury } from "@/app/lib/dashboard-contract";
import { supplierApi } from "@/app/lib/supplier-api";
import type { Supplier } from "@/app/lib/supplier-contract";
import { documentHref, documentLabel, formatRange, isNegativeAmount, presetRange } from "@/app/lib/dashboard-rules";

type Preset = "today" | "7d" | "month" | "custom";
type Block<T> = { loading: boolean; error: string; data: T | null };
const empty = <T,>(): Block<T> => ({ loading: true, error: "", data: null });
const localToday = () => { const date = new Date(); return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}-${String(date.getDate()).padStart(2, "0")}`; };
const money = (value: string, currency: string) => new Intl.NumberFormat("es-AR", { style: "currency", currency }).format(Number(value));
const date = (value: string | null | undefined) => value ? new Intl.DateTimeFormat("es-AR", { dateStyle: "short" }).format(new Date(`${value.slice(0, 10)}T12:00:00`)) : "—";
const presets: Array<{ key: Exclude<Preset, "custom">; label: string }> = [{ key: "today", label: "Hoy" }, { key: "7d", label: "7 días" }, { key: "month", label: "Mes" }];
const errorText = (error: unknown) => error instanceof Error ? error.message : "No pudimos cargar este bloque.";
function query(filters: DashboardFilters) { const params = new URLSearchParams(); Object.entries(filters).forEach(([key, value]) => { if (value) params.set(key, String(value)); }); return params.toString(); }
function BlockState({ block, onRetry, emptyText, children }: { block: Block<unknown>; onRetry: () => void; emptyText: string; children?: React.ReactNode }) { if (block.loading) return <div className="admin-block-skeleton"><ListSkeleton label="Cargando datos…" /></div>; if (block.error) return <div className="state error-state admin-block-state" role="alert"><strong>No pudimos cargar este bloque</strong><span>{block.error}</span><button className="button secondary" onClick={onRetry}>Reintentar</button></div>; if (block.data === null) return <div className="state admin-block-state"><strong>Sin datos</strong><span>{emptyText}</span></div>; return <>{children}</>; }
function KpiCard({ label, value, hint, href }: { label: string; value: string; hint?: string; href: string }) { return <Link className="kpi-card admin-kpi-card" href={href}><span>{label}</span><strong>{value}</strong>{hint && <small>{hint}</small>}</Link>; }

export function DashboardWorkspace() {
  const today = localToday();
  const [access, setAccess] = useState<"loading" | "ready" | "unauthenticated" | "forbidden">("loading");
  const [preset, setPreset] = useState<Preset>("month");
  const [range, setRange] = useState(() => presetRange("month", new Date(`${today}T12:00:00`)));
  const [draft, setDraft] = useState(range);
  const [supplierId, setSupplierId] = useState("");
  const [supplierSearch, setSupplierSearch] = useState("");
  const [suppliers, setSuppliers] = useState<Supplier[]>([]);
  const [currency, setCurrency] = useState("ARS");
  const [formError, setFormError] = useState("");
  const [kpis, setKpis] = useState<Block<DashboardKpis>>(empty);
  const [payables, setPayables] = useState<Block<DashboardDueItem[]>>(empty);
  const [receipts, setReceipts] = useState<Block<DashboardPendingReceipt[]>>(empty);
  const [topSuppliers, setTopSuppliers] = useState<Block<DashboardSupplier[]>>(empty);
  const [categories, setCategories] = useState<Block<DashboardExpenseCategory[]>>(empty);
  const [investments, setInvestments] = useState<Block<DashboardInvestment[]>>(empty);
  const [treasury, setTreasury] = useState<Block<DashboardTreasury>>(empty);
  const filters = useMemo<DashboardFilters>(() => ({ ...range, supplierId: supplierId || undefined, currency, limit: 12 }), [range, supplierId, currency]);

  useEffect(() => { const timer = window.setTimeout(() => { const user = getStoredUser(); setAccess(!process.env.NEXT_PUBLIC_SUPERX_API_BASE_URL || user?.role === "admin" ? "ready" : user ? "forbidden" : "unauthenticated"); }, 0); return () => window.clearTimeout(timer); }, []);
  useEffect(() => { if (access !== "ready") return; void supplierApi.listSuppliers({ status: "ACTIVE", pageSize: 100 }).then((result) => setSuppliers(result.items)).catch(() => setSuppliers([])); }, [access]);
  const loadKpis = async () => { setKpis((current) => ({ ...current, loading: true, error: "" })); try { setKpis({ loading: false, error: "", data: await dashboardApi.kpis(filters) }); } catch (error) { setKpis({ loading: false, error: errorText(error), data: null }); } };
  const loadPayables = async () => { setPayables((current) => ({ ...current, loading: true, error: "" })); try { setPayables({ loading: false, error: "", data: await dashboardApi.payablesDue(filters) }); } catch (error) { setPayables({ loading: false, error: errorText(error), data: null }); } };
  const loadReceipts = async () => { setReceipts((current) => ({ ...current, loading: true, error: "" })); try { setReceipts({ loading: false, error: "", data: await dashboardApi.pendingReceipts(filters) }); } catch (error) { setReceipts({ loading: false, error: errorText(error), data: null }); } };
  const loadSuppliers = async () => { setTopSuppliers((current) => ({ ...current, loading: true, error: "" })); try { setTopSuppliers({ loading: false, error: "", data: await dashboardApi.topSuppliers(filters) }); } catch (error) { setTopSuppliers({ loading: false, error: errorText(error), data: null }); } };
  const loadCategories = async () => { setCategories((current) => ({ ...current, loading: true, error: "" })); try { setCategories({ loading: false, error: "", data: await dashboardApi.expensesByCategory(filters) }); } catch (error) { setCategories({ loading: false, error: errorText(error), data: null }); } };
  const loadInvestments = async () => { setInvestments((current) => ({ ...current, loading: true, error: "" })); try { setInvestments({ loading: false, error: "", data: await dashboardApi.investments(filters) }); } catch (error) { setInvestments({ loading: false, error: errorText(error), data: null }); } };
  const loadTreasury = async () => { setTreasury((current) => ({ ...current, loading: true, error: "" })); try { setTreasury({ loading: false, error: "", data: await dashboardApi.treasury(filters) }); } catch (error) { setTreasury({ loading: false, error: errorText(error), data: null }); } };
  useEffect(() => { if (access !== "ready") return; const timer = window.setTimeout(() => { void loadKpis(); void loadPayables(); void loadReceipts(); void loadSuppliers(); void loadCategories(); void loadInvestments(); void loadTreasury(); }, 0); return () => window.clearTimeout(timer); // filters are intentionally the dashboard refresh boundary
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [access, filters]);
  const applyPreset = (next: Exclude<Preset, "custom">) => { const nextRange = presetRange(next, new Date(`${today}T12:00:00`)); setPreset(next); setRange(nextRange); setDraft(nextRange); setFormError(""); };
  const applyCustom = (event: React.FormEvent) => { event.preventDefault(); if (!draft.from || !draft.to || draft.from > draft.to) { setFormError("Indicá un rango válido: la fecha Desde no puede ser posterior a Hasta."); return; } setPreset("custom"); setRange(draft); setFormError(""); };
  const matchingSuppliers = suppliers.filter((supplier) => supplier.name.toLocaleLowerCase("es-AR").includes(supplierSearch.toLocaleLowerCase("es-AR")));
  if (access === "loading") return <section className="workspace"><div className="state"><strong>Verificando acceso…</strong></div></section>;
  if (access !== "ready") return <section className="workspace"><div className="state error-state" role="alert"><strong>{access === "unauthenticated" ? "Necesitás iniciar sesión" : "No autorizado"}</strong><span>{access === "unauthenticated" ? "Iniciá sesión con una cuenta administradora para consultar Administración." : "Administración está disponible únicamente para cuentas administradoras."}</span>{access === "unauthenticated" && <Link className="button primary" href="/login?next=/administracion">Iniciar sesión</Link>}</div></section>;
  const k = kpis.data;
  const filterQuery = query({ ...filters, limit: undefined });
  const cashFlow = treasury.data?.cashFlow ?? [];
  const maxFlow = Math.max(1, ...cashFlow.flatMap((item) => [Math.abs(Number(item.in)), Math.abs(Number(item.out)), Math.abs(Number(item.net))]));
  const maxCategory = Math.max(1, ...(categories.data ?? []).map((item) => Math.abs(Number(item.total))));
  return <section className="workspace administracion-workspace" id="administracion">
    <header className="topbar"><div><p className="eyebrow">ADMINISTRACIÓN / RESUMEN</p><h1>Administración</h1><p className="subtitle">Compras, obligaciones y tesorería consolidadas por el servidor.</p></div></header>
    <section className="locations-filter-bar admin-filters" aria-label="Filtros del dashboard"><div className="kpi-presets" role="group" aria-label="Períodos rápidos">{presets.map((item) => <button key={item.key} type="button" className={`chip ${preset === item.key ? "chip-active" : ""}`} aria-pressed={preset === item.key} onClick={() => applyPreset(item.key)}>{item.label}</button>)}</div><form className="admin-range" onSubmit={applyCustom} noValidate><label className="date-filter"><span>Desde</span><input type="date" value={draft.from} onChange={(event) => setDraft((current) => ({ ...current, from: event.target.value }))} /></label><label className="date-filter"><span>Hasta</span><input type="date" value={draft.to} onChange={(event) => setDraft((current) => ({ ...current, to: event.target.value }))} /></label><button className="button secondary" type="submit">Personalizado</button></form><label className="field admin-supplier"><span>Proveedor</span><input value={supplierSearch} onChange={(event) => setSupplierSearch(event.target.value)} placeholder="Buscar proveedor…" aria-label="Buscar proveedor" /><select value={supplierId} onChange={(event) => setSupplierId(event.target.value)} aria-label="Filtrar por proveedor"><option value="">Todos los proveedores</option>{matchingSuppliers.map((supplier) => <option key={supplier.id} value={supplier.id}>{supplier.name}</option>)}</select></label><label className="field"><span>Moneda</span><select value={currency} onChange={(event) => setCurrency(event.target.value)}><option value="ARS">ARS</option><option value="USD">USD</option></select></label></section>
    {formError && <div className="form-summary" role="alert"><strong>Revisá el rango</strong><span>{formError}</span></div>}
    <p className="kpi-range-note">Rango: {formatRange(range)}{k ? ` · actualizado ${new Intl.DateTimeFormat("es-AR", { dateStyle: "short", timeStyle: "short" }).format(new Date(k.generatedAt))}` : ""}</p>
    {kpis.loading ? <div className="kpi-grid admin-kpi-grid">{Array.from({ length: 10 }, (_, index) => <div className="kpi-card" key={index}><span>Cargando…</span><strong>—</strong></div>)}</div> : kpis.error || !k ? <BlockState block={kpis} onRetry={() => void loadKpis()} emptyText="No hay indicadores para este rango." /> : <section className="kpi-grid admin-kpi-grid" aria-label="Indicadores administrativos"><KpiCard label="Compras del período" value={money(k.purchases.total, currency)} href={`/compras?${filterQuery}`} /><KpiCard label="Mercadería pendiente" value={`${k.pendingReceipt.units} u.`} hint={`${k.pendingReceipt.orders} OC · ${money(k.pendingReceipt.value, currency)}`} href={`/compras?${filterQuery}`} /><KpiCard label="Facturado" value={money(k.invoiced, currency)} hint="Facturas de proveedor" href={`/facturas?${filterQuery}`} /><KpiCard label="Pagado a proveedores" value={money(k.paidSuppliers, currency)} href={`/pagos?${filterQuery}`} /><KpiCard label="Deuda total" value={money(k.payablesOpen.amount, currency)} hint={`${k.payablesOpen.count} comprobantes`} href={`/facturas?${filterQuery}`} /><KpiCard label="Deuda vencida" value={money(k.payablesOverdue.amount, currency)} hint={`${k.payablesOverdue.count} comprobantes`} href={`/facturas?${filterQuery}`} /><KpiCard label="Gastos" value={money(k.expenses.total, currency)} href={`/gastos?${filterQuery}`} /><KpiCard label="Inversiones" value={money(k.investments.total, currency)} href={`/inversiones?${filterQuery}`} /><KpiCard label="Saldo tesorería" value={treasury.data ? money(treasury.data.total, currency) : "—"} hint="Suma de las cuentas de la moneda" href={`/tesoreria?${filterQuery}`} /><KpiCard label="Movimiento neto" value={treasury.data ? money(treasury.data.netMovement, currency) : "—"} href={`/tesoreria?${filterQuery}`} /><KpiCard label="Vencimientos próximos" value={`${k.dueSoon.next7.length} / ${k.dueSoon.next30.length}`} hint="7 / 30 días" href={`/facturas?${filterQuery}`} /></section>}
    <section className="admin-grid-two"><section className="location-table-panel"><header><div><p className="eyebrow">CUENTAS POR PAGAR</p><h2>Próximas y vencidas</h2></div><Link className="link-button" href={`/facturas?${filterQuery}`}>Ver facturas →</Link></header><BlockState block={payables} onRetry={() => void loadPayables()} emptyText="No hay cuentas por pagar abiertas para estos filtros.">{payables.data?.length ? <DataTable headers={["Documento", "Proveedor", "Vence", "Saldo", "Estado"]}>{payables.data.map((item) => <tr key={`${item.type}-${item.id}`}><td data-label="Documento"><Link href={documentHref(item.link)}>{item.label}</Link><small>{documentLabel(item.type)}</small></td><td data-label="Proveedor">{item.supplier ?? "—"}</td><td data-label="Vence">{date(item.dueDate)}</td><td data-label="Saldo">{money(item.balance, currency)}</td><td data-label="Estado"><span className={`status ${item.status === "OVERDUE" ? "status-cancelled" : "status-confirmed"}`}>{item.status === "OVERDUE" ? "Vencido" : "Pendiente"}</span></td></tr>)}</DataTable> : <Empty text="No hay cuentas por pagar abiertas para estos filtros." />}</BlockState></section>
    <section className="location-table-panel"><header><div><p className="eyebrow">RECEPCIONES</p><h2>OC pendientes de recepción</h2></div><Link className="link-button" href={`/compras?${filterQuery}`}>Ver compras →</Link></header><BlockState block={receipts} onRetry={() => void loadReceipts()} emptyText="No hay órdenes pendientes de recepción.">{receipts.data?.length ? <DataTable headers={["OC", "Proveedor", "Pendiente", "Valor", "Acción"]}>{receipts.data.map((item) => <tr key={item.id}><td data-label="OC"><Link href={`/compras/${encodeURIComponent(item.id)}`}>{item.number}</Link><small>{item.warehouse}</small></td><td data-label="Proveedor">{item.supplier}</td><td data-label="Pendiente">{item.unitsPending} u.<small>{item.packsPending} bultos</small></td><td data-label="Valor">{money(item.value, currency)}</td><td data-label="Acción"><Link className="button secondary admin-inline-button" href={`/compras/${encodeURIComponent(item.id)}/recibir`}>Recibir</Link></td></tr>)}</DataTable> : <Empty text="No hay órdenes pendientes de recepción." />}</BlockState></section></section>
    <section className="admin-grid-three"><section className="location-table-panel"><header><div><p className="eyebrow">PROVEEDORES</p><h2>Mayor saldo abierto</h2></div></header><BlockState block={topSuppliers} onRetry={() => void loadSuppliers()} emptyText="No hay saldos abiertos por proveedor.">{topSuppliers.data?.length ? <DataTable headers={["Proveedor", "Abierto", "Vencido"]}>{topSuppliers.data.map((item) => <tr key={item.id}><td data-label="Proveedor"><Link href={`/proveedores/${encodeURIComponent(item.id)}`}>{item.name}</Link><small>{item.count} comprobantes</small></td><td data-label="Abierto">{money(item.balance, currency)}</td><td data-label="Vencido">{money(item.overdue, currency)}</td></tr>)}</DataTable> : <Empty text="No hay saldos abiertos por proveedor." />}</BlockState></section>
    <section className="location-table-panel"><header><div><p className="eyebrow">GASTOS</p><h2>Por categoría</h2></div><Link className="link-button" href={`/gastos?${filterQuery}`}>Ver gastos →</Link></header><BlockState block={categories} onRetry={() => void loadCategories()} emptyText="No hay gastos categorizados en este período.">{categories.data?.length ? <ul className="admin-bars">{categories.data.map((item) => <li key={item.id}><div><strong>{item.name}</strong><span>{money(item.total, currency)}</span></div><span className="admin-bar-track"><i style={{ width: `${Math.max(2, (Math.abs(Number(item.total)) / maxCategory) * 100)}%` }} /></span><small>Pagado {money(item.paid, currency)} · Pendiente {money(item.pending, currency)}</small></li>)}</ul> : <Empty text="No hay gastos categorizados en este período." />}</BlockState></section>
    <section className="location-table-panel"><header><div><p className="eyebrow">ACTIVOS</p><h2>Inversiones del período</h2></div><Link className="link-button" href={`/inversiones?${filterQuery}`}>Ver inversiones →</Link></header><BlockState block={investments} onRetry={() => void loadInvestments()} emptyText="No hubo inversiones en este período.">{investments.data?.length ? <DataTable headers={["Activo", "Fecha", "Costo", "Pendiente"]}>{investments.data.map((item) => <tr key={item.id}><td data-label="Activo"><Link href={documentHref(item.link)}>{item.name}</Link><small>{item.category ?? "—"}</small></td><td data-label="Fecha">{date(item.acquisitionDate)}</td><td data-label="Costo">{money(item.cost, currency)}</td><td data-label="Pendiente">{money(item.balance, currency)}</td></tr>)}</DataTable> : <Empty text="No hubo inversiones en este período." />}</BlockState></section></section>
    <section className="location-table-panel"><header><div><p className="eyebrow">TESORERÍA</p><h2>Cuentas y flujo diario</h2></div><Link className="link-button" href={`/tesoreria?${filterQuery}`}>Ver tesorería →</Link></header><BlockState block={treasury} onRetry={() => void loadTreasury()} emptyText="No hay cuentas ni movimientos para estos filtros.">{treasury.data && <div className="admin-treasury"><div>{treasury.data.accounts.length ? <DataTable headers={["Cuenta", "Tipo", "Saldo"]}>{treasury.data.accounts.map((item) => <tr key={item.id}><td data-label="Cuenta"><Link href={`/tesoreria/${encodeURIComponent(item.id)}`}>{item.name}</Link></td><td data-label="Tipo">{item.type}</td><td data-label="Saldo" className={isNegativeAmount(item.balance) ? "admin-negative" : ""}>{money(item.balance, item.currency)}</td></tr>)}</DataTable> : <Empty text="No hay cuentas de tesorería para esta moneda." />}</div><CashFlow items={cashFlow} max={maxFlow} currency={currency} /></div>}</BlockState></section>
  </section>;
}
function DataTable({ headers, children }: { headers: string[]; children: React.ReactNode }) { return <div className="location-table-wrap"><table className="location-stock-table"><thead><tr>{headers.map((header) => <th key={header}>{header}</th>)}</tr></thead><tbody>{children}</tbody></table></div>; }
function Empty({ text }: { text: string }) { return <div className="state admin-block-state"><strong>Sin datos</strong><span>{text}</span></div>; }
function CashFlow({ items, max, currency }: { items: DashboardTreasury["cashFlow"]; max: number; currency: string }) { if (!items.length) return <Empty text="No hubo flujo de caja en este período." />; return <section className="admin-flow" aria-labelledby="cashflow-title"><h3 id="cashflow-title">Flujo de caja diario</h3><p>Ingresos, egresos y neto del servidor.</p><div className="admin-flow-chart" role="img" aria-label="Gráfico de barras de ingresos, egresos y neto por día">{items.map((item) => <div className="admin-flow-day" key={item.date}><div className="admin-flow-bars"><i className="in" style={{ height: `${Math.max(2, Math.abs(Number(item.in)) / max * 100)}%` }} /><i className="out" style={{ height: `${Math.max(2, Math.abs(Number(item.out)) / max * 100)}%` }} /><i className="net" style={{ height: `${Math.max(2, Math.abs(Number(item.net)) / max * 100)}%` }} /></div><time>{item.date.slice(5)}</time></div>)}</div><span className="admin-flow-legend"><i className="in" />Ingreso <i className="out" />Egreso <i className="net" />Neto</span><details><summary>Ver tabla alternativa del flujo</summary><DataTable headers={["Fecha", "Ingresos", "Egresos", "Neto"]}>{items.map((item) => <tr key={item.date}><td>{date(item.date)}</td><td>{money(item.in, currency)}</td><td>{money(item.out, currency)}</td><td>{money(item.net, currency)}</td></tr>)}</DataTable></details></section>; }
