"use client";
import { useEffect, useRef, useState } from "react";
import type { DispatchOrder, LatLng } from "@/app/lib/dispatch-contract";
import styles from "./driver.module.css";
type Props = { orders: DispatchOrder[]; geometry: LatLng[]; selectedId: string | null; userLocation: LatLng | null; onSelect(id: string): void };
export default function RouteMap({ orders, geometry, selectedId, userLocation, onSelect }: Props) {
  const host = useRef<HTMLDivElement>(null); const mapRef = useRef<import("leaflet").Map | null>(null); const layerRef = useRef<import("leaflet").LayerGroup | null>(null); const resizeRef = useRef<ResizeObserver | null>(null); const fitKeyRef = useRef(""); const [ready, setReady] = useState(false);
  // The Leaflet instance is created once; the effect below synchronizes its layers.
  // eslint-disable-next-line react-hooks/exhaustive-deps
  useEffect(() => { let live = true; void import("leaflet").then((L) => { if (!live || !host.current || mapRef.current) return; const located = orders.filter((o) => o.location); const center = userLocation ?? located[0]?.location ?? { lat: -34.292, lng: -60.254 }; const map = L.map(host.current, { zoomControl: false, attributionControl: true }).setView([center.lat, center.lng], located.length ? 14 : 12); L.tileLayer("https://tile.openstreetmap.org/{z}/{x}/{y}.png", { attribution: "© OpenStreetMap", maxZoom: 19 }).addTo(map); L.control.zoom({ position: "topright" }).addTo(map); mapRef.current = map; layerRef.current = L.layerGroup().addTo(map); setTimeout(() => map.invalidateSize(), 0); if (host.current && typeof ResizeObserver !== "undefined") { resizeRef.current = new ResizeObserver(() => map.invalidateSize()); resizeRef.current.observe(host.current); } setReady(true); }); return () => { live = false; resizeRef.current?.disconnect(); mapRef.current?.remove(); mapRef.current = null; layerRef.current = null; }; }, []);
  useEffect(() => { void import("leaflet").then((L) => { const map = mapRef.current; const layer = layerRef.current; if (!map || !layer) return; layer.clearLayers(); const points: import("leaflet").LatLngExpression[] = []; orders.forEach((order, index) => { if (!order.location) return; const selected = order.id === selectedId; const tone = order.incident ? "incident" : order.status === "DELIVERED" ? "done" : "active"; const icon = L.divIcon({ className: "", html: `<span class="${styles.mapMarker} ${styles[tone]} ${selected ? styles.markerSelected : ""}">${index + 1}</span>`, iconSize: selected ? [42, 42] : [34, 34], iconAnchor: selected ? [21, 21] : [17, 17] }); L.marker([order.location.lat, order.location.lng], { icon, title: order.orderNumber }).addTo(layer).on("click", () => onSelect(order.id)); points.push([order.location.lat, order.location.lng]); }); if (geometry.length > 1) L.polyline(geometry.map((p) => [p.lat, p.lng]), { color: "#149c3b", weight: 5, opacity: .9 }).addTo(layer); if (userLocation) { const blue = L.divIcon({ className: "", html: `<span class="${styles.userDot}"></span>`, iconSize: [20, 20], iconAnchor: [10, 10] }); L.marker([userLocation.lat, userLocation.lng], { icon: blue, title: "Mi ubicación" }).addTo(layer); points.push([userLocation.lat, userLocation.lng]); } // Re-frame only when the set of stops changes, so selecting an order or a GPS update doesn't yank the view.
      const fitKey = orders.map((o) => `${o.id}:${o.location?.lat ?? ""}`).join("|") + (userLocation ? "|me" : ""); if (fitKey !== fitKeyRef.current) { fitKeyRef.current = fitKey; if (points.length > 1) map.fitBounds(L.latLngBounds(points), { padding: [56, 56], maxZoom: 16 }); else if (points.length === 1) map.setView(points[0], 16); } const focus = orders.find((o) => o.id === selectedId)?.location; if (focus && !map.getBounds().pad(-0.15).contains([focus.lat, focus.lng])) map.panTo([focus.lat, focus.lng]); }); }, [geometry, onSelect, orders, ready, selectedId, userLocation]);
  return <div ref={host} className={styles.mapCanvas} aria-label="Mapa interactivo de la ruta"/>;
}
