"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { getCustomer, type CustomerDetail } from "@/app/lib/customers-api";
import type { OrderStatus } from "@/app/lib/order-contract";
import { ORDER_STATUS_LABELS } from "@/app/lib/order-rules";
import { money, OrderStatusBadge } from "../orders/order-shared";
import { customerDate } from "./customer-list";

const isStatus = (status: string): status is OrderStatus => status in ORDER_STATUS_LABELS;

export function CustomerDetailView({ id }: { id: string }) {
  const [customer, setCustomer] = useState<CustomerDetail | null>(null), [error, setError] = useState(""), [attempt, setAttempt] = useState(0);
  useEffect(() => { let active = true; getCustomer(id).then((result) => { if (active) { setCustomer(result); setError(""); } }).catch((cause: unknown) => { if (active) setError(cause instanceof Error ? cause.message : "No pudimos cargar el cliente."); }); return () => { active = false; }; }, [id, attempt]);
  const back = <Link href="/clientes" className="button secondary">Volver a clientes</Link>;
  if (error) return <section className="workspace"><header className="topbar"><div><p className="eyebrow">CLIENTES</p><h1>Cliente</h1></div>{back}</header><div className="state"><strong>{error}</strong> <button className="button secondary" onClick={() => { setError(""); setAttempt(attempt + 1); }}>Reintentar</button></div></section>;
  if (!customer) return <section className="workspace"><div className="state">Cargando cliente…</div></section>;
  return <section className="workspace"><header className="topbar"><div><p className="eyebrow">CLIENTES</p><h1>{customer.name || customer.email}</h1><p className="subtitle">Cliente desde el {customerDate.format(new Date(customer.createdAt))}</p></div>{back}</header>
    <section className="location-table-panel"><header><div><p className="eyebrow">CONTACTO</p><h2>Datos de la cuenta</h2></div></header><div className="location-table-wrap"><table className="location-stock-table"><tbody><tr><th scope="row">Email</th><td><a href={`mailto:${customer.email}`}>{customer.email}</a></td></tr><tr><th scope="row">Teléfono</th><td>{customer.phone ? <a href={`tel:${customer.phone.replace(/[^\d+]/g, "")}`}>{customer.phone}</a> : "—"}</td></tr><tr><th scope="row">Pedidos</th><td>{customer.ordersCount}</td></tr><tr><th scope="row">Total gastado</th><td>{money.format(Number(customer.totalSpent))} <small>(sin cancelados)</small></td></tr><tr><th scope="row">Ticket promedio</th><td>{customer.averageTicket ? money.format(Number(customer.averageTicket)) : "—"}</td></tr><tr><th scope="row">Último pedido</th><td>{customer.lastOrderAt ? customerDate.format(new Date(customer.lastOrderAt)) : "Sin pedidos"}</td></tr></tbody></table></div></section>
    <section className="location-table-panel"><header><div><p className="eyebrow">DIRECCIONES</p><h2>{customer.addresses.length} {customer.addresses.length === 1 ? "dirección" : "direcciones"}</h2></div></header>{customer.addresses.length === 0 ? <div className="state">El cliente no cargó direcciones.</div> : <div className="location-table-wrap"><table className="location-stock-table"><thead><tr><th>Etiqueta</th><th>Dirección</th><th>Localidad</th><th>Recibe</th><th>Notas</th></tr></thead><tbody>{customer.addresses.map((address) => <tr key={address.id}><td data-label="Etiqueta"><strong>{address.label}</strong>{address.isDefault && <small>Principal</small>}</td><td data-label="Dirección">{address.street} {address.streetNumber}{address.apartment ? `, ${address.apartment}` : ""}{address.neighborhood ? ` · ${address.neighborhood}` : ""}</td><td data-label="Localidad">{address.city} ({address.postalCode})</td><td data-label="Recibe">{address.recipientName}<small>{address.phone}</small></td><td data-label="Notas">{address.notes || "—"}</td></tr>)}</tbody></table></div>}</section>
    <section className="location-table-panel"><header><div><p className="eyebrow">PEDIDOS</p><h2>{customer.ordersCount === 0 ? "Sin pedidos" : customer.ordersCount > customer.orders.length ? `Últimos ${customer.orders.length} de ${customer.ordersCount}` : `${customer.ordersCount} ${customer.ordersCount === 1 ? "pedido" : "pedidos"}`}</h2></div></header>{customer.orders.length === 0 ? <div className="state">Todavía no hizo pedidos.</div> : <div className="location-table-wrap"><table className="location-stock-table"><thead><tr><th>Pedido</th><th>Fecha</th><th>Estado</th><th>Total</th></tr></thead><tbody>{customer.orders.map((order) => <tr key={order.id}><td data-label="Pedido"><Link href={`/pedidos/${order.id}`}><strong>{order.orderNumber}</strong></Link></td><td data-label="Fecha">{customerDate.format(new Date(order.placedAt))}</td><td data-label="Estado">{isStatus(order.status) ? <OrderStatusBadge status={order.status} /> : order.status}</td><td data-label="Total">{money.format(Number(order.grandTotal))}</td></tr>)}</tbody></table></div>}</section>
  </section>;
}
