import type { InventoryItem, InventoryMovement, Warehouse } from "@/app/lib/inventory-contract";
import { getInventoryStatus } from "@/app/lib/inventory-rules";
import { InventoryIcon, StockStatusBadge } from "./inventory-ui";

const dates = new Intl.DateTimeFormat("es-AR", { dateStyle: "medium", timeStyle: "short" });
const typeLabel: Record<InventoryMovement["type"], string> = { adjustment: "Ajuste", receipt: "Ingreso", sale: "Venta", transfer: "Transferencia" };
export function InventoryStockByWarehouse({ items, warehouses }: { items: InventoryItem[]; warehouses: Warehouse[] }) { return <section className="inventory-detail-section"><h3>Stock por depósito</h3><ul className="inventory-warehouse-stock">{items.map((item) => <li key={item.id}><span>{warehouses.find((warehouse) => warehouse.id === item.warehouseId)?.name ?? "Depósito no disponible"}</span><strong>{item.onHand} u.</strong></li>)}</ul></section>; }
export function InventoryRecentMovements({ movements }: { movements: InventoryMovement[] }) { return <section className="inventory-detail-section inventory-movements"><div className="inventory-section-heading"><h3>Movimientos recientes</h3><button className="link-button" type="button">Ver todos</button></div>{movements.length ? movements.slice(0, 4).map((movement) => <article key={movement.id} className="inventory-movement"><strong className={movement.quantity > 0 ? "positive" : "negative"}>{movement.quantity > 0 ? "+" : ""}{movement.quantity} u.</strong><div><span>{typeLabel[movement.type]} · {movement.reason}</span><time>{dates.format(new Date(movement.occurredAt))} · {movement.createdBy}</time></div></article>) : <p className="muted">No hay movimientos para este producto.</p>}</section>; }
export function InventoryDetailPanel({ selected, allItems, warehouses, canAdjust, onAdjust, onClose }: { selected: InventoryItem | null; allItems: InventoryItem[]; warehouses: Warehouse[]; canAdjust: boolean; onAdjust: () => void; onClose: () => void }) {
  if (!selected) return <aside className="inventory-detail-panel"><div className="state detail-empty"><InventoryIcon name="boxes" /><strong>Seleccioná una posición</strong><span>Vas a ver el detalle y sus movimientos.</span></div></aside>;
  const productItems = allItems.filter((item) => item.productId === selected.productId);
  const movements = productItems.flatMap((item) => item.movements).sort((a, b) => Date.parse(b.occurredAt) - Date.parse(a.occurredAt));
  return <aside className="inventory-detail-panel" aria-live="polite"><button className="inventory-detail-close" aria-label="Cerrar detalle" onClick={onClose}><InventoryIcon name="close" /></button><div className="inventory-detail-hero"><span className="inventory-detail-image"><InventoryIcon name="boxes" /></span><StockStatusBadge status={getInventoryStatus(selected)} /><h2>{selected.productName}</h2><p>SKU: {selected.sku}</p><div className="inventory-detail-tags"><span>{warehouses.find((warehouse) => warehouse.id === selected.warehouseId)?.name ?? "Depósito no disponible"}</span></div></div><div className="inventory-stock-highlight"><span>Stock disponible</span><strong>{selected.onHand}</strong><small>Mínimo operativo: {selected.minimum} unidades</small></div>{canAdjust && <button className="button primary full-width" onClick={onAdjust}><InventoryIcon name="adjust" /> Ajustar stock</button>}<div className="inventory-detail-actions"><button className="button secondary" type="button"><InventoryIcon name="move" /> Mover stock</button><button className="button secondary" type="button"><InventoryIcon name="history" /> Ver historial</button></div><InventoryStockByWarehouse items={productItems} warehouses={warehouses} /><InventoryRecentMovements movements={movements} /></aside>;
}
