"use client";
/* eslint-disable react-hooks/set-state-in-effect */
import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { getStoredUser } from "@/app/lib/auth-api";
import { purchaseOrderApi } from "@/app/lib/purchase-order-api";
import type { PurchaseOrder, PurchaseOrderEventType } from "@/app/lib/purchase-order-contract";
import { date, money, OrderStatusBadge, orderCode, ReceiptStatusBadge } from "./purchase-order-ui";

const labels: Record<PurchaseOrderEventType, string> = { CREATED: "Creada", CONFIRMED: "Confirmada", CANCELLED: "Cancelada", UPDATED: "Editada" };
export function PurchaseOrderDetail({ orderId }: { orderId: string }) {
  const [access, setAccess] = useState<"loading" | "ready" | "denied">("loading"), [order, setOrder] = useState<PurchaseOrder | null>(null), [loading, setLoading] = useState(true), [error, setError] = useState(""), [pending, setPending] = useState(false);
  useEffect(() => { const user = getStoredUser(); setAccess(!process.env.NEXT_PUBLIC_SUPERX_API_BASE_URL || user?.role === "admin" ? "ready" : "denied"); }, []);
  const load = useCallback(async () => { if (access !== "ready") return; setLoading(true); try { setOrder(await purchaseOrderApi.get(orderId)); setError(""); } catch (cause) { setError(cause instanceof Error ? cause.message : "No se pudo cargar la orden."); } finally { setLoading(false); } }, [access, orderId]);
  useEffect(() => { void load(); }, [load]);
  const transition = async (kind: "confirm" | "cancel") => { if (!order || !window.confirm(kind === "confirm" ? "¿Confirmar esta orden de compra? Esta acción no se puede deshacer." : "¿Cancelar esta orden de compra?")) return; setPending(true); try { if (kind === "confirm") await purchaseOrderApi.confirm(order.id); else await purchaseOrderApi.cancel(order.id); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : "No se pudo actualizar la orden."); } finally { setPending(false); } };
  if (access === "loading" || loading) return <section className="workspace"><div className="state"><strong>Cargando orden…</strong></div></section>;
  if (access === "denied") return <section className="workspace"><div className="state error-state"><strong>No autorizado</strong><span>La gestión de compras está disponible únicamente para cuentas administradoras.</span></div></section>;
  if (!order) return <section className="workspace"><div className="state error-state"><strong>No pudimos cargar la orden</strong><span>{error}</span><button className="button secondary" onClick={() => void load()}>Reintentar</button></div></section>;
  const canCancel = (order.status === "DRAFT" || order.status === "CONFIRMED") && !order.items.some((item) => item.receivedPackageQuantity > 0);
  return <section className="workspace"><Link className="back-link" href="/compras">← Órdenes de compra</Link><article className="location-table-panel"><header className="topbar"><div><p className="eyebrow">ORDEN DE COMPRA</p><h1 className="mono">{orderCode(order.id)}</h1><div><OrderStatusBadge status={order.status} /> <ReceiptStatusBadge status={order.receiptStatus} /></div></div><div className="top-actions">{order.status === "DRAFT" && <><Link className="button secondary" href={`/compras/${encodeURIComponent(order.id)}/editar`}>Editar</Link><button className="button primary" disabled={pending} onClick={() => void transition("confirm")}>Confirmar</button></>}{canCancel && <button className="button danger" disabled={pending} onClick={() => void transition("cancel")}>Cancelar</button>}</div></header>{error && <div className="notice error" role="alert">{error}</div>}<section className="form-grid"><div className="field"><span>Proveedor</span><strong>{order.supplier.name}</strong></div><div className="field"><span>Depósito</span><strong>{order.warehouse.name}</strong></div><div className="field"><span>Fecha de orden</span><strong>{date(order.createdAt)}</strong></div><div className="field"><span>Fecha esperada</span><strong>{date(order.expectedDate)}</strong></div></section><div className="location-table-wrap"><table className="location-stock-table"><thead><tr><th>Producto</th><th>Presentación</th><th>Packs</th><th>Unidades</th><th>Recibido</th><th>Pendiente</th><th>Costo / pack</th><th>Costo unit.</th><th>Total</th></tr></thead><tbody>{order.items.map((item) => <tr key={item.id}><td><strong>{item.product.name}</strong><small className="mono">{item.product.slug}</small></td><td>{item.packagingName}<small>x{item.unitsPerPack}</small></td><td>{item.packageQuantity}</td><td>{item.unitQuantity}</td><td>{item.receivedPackageQuantity} packs</td><td>{item.packageQuantity - item.receivedPackageQuantity} packs</td><td>{money(item.costPerPackage)}</td><td>{money(item.unitCost)}</td><td><strong>{money(item.total)}</strong></td></tr>)}</tbody><tfoot><tr><td colSpan={8}><strong>Total general</strong></td><td><strong>{money(order.total)}</strong></td></tr></tfoot></table></div><section className="history"><p className="eyebrow">HISTORIAL</p><h3>Línea de tiempo</h3>{order.events.map((event, index) => <div className="history-row" key={event.id ?? `${event.type}-${index}`}><time>{date(event.createdAt)}</time><div><strong>{labels[event.type]}</strong><span>{event.actorUserId ?? "Sistema"}{event.note ? ` · ${event.note}` : ""}</span></div></div>)}</section></article></section>;
}
