"use client";

import { Notice } from "@/app/components/ui/notice";
/* eslint-disable react-hooks/set-state-in-effect */
import Link from "next/link";
import { type FormEvent, useCallback, useEffect, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { locationApi } from "@/app/lib/location-api";
import { purchaseOrderApi } from "@/app/lib/purchase-order-api";
import type { PurchaseOrder } from "@/app/lib/purchase-order-contract";
import { isOverReceipt, pendingPackages, stableIdempotencyKey, validateVarianceReason } from "@/app/lib/purchase-order-rules";

type Entry = { quantity: string; allowOver: boolean; reason: string };
/** Stock is tracked per warehouse for now; flip to true when locations/racks are rolled out. */
const LOCATIONS_ENABLED = false;

export function PurchaseOrderReceipt({ orderId }: { orderId: string }) {
  const router = useRouter(); const [order, setOrder] = useState<PurchaseOrder | null>(null); const [locations, setLocations] = useState<Array<{ id: string; code: string }>>([]); const [locationId, setLocationId] = useState(""); const [entries, setEntries] = useState<Record<string, Entry>>({}); const [reference, setReference] = useState(""); const [notes, setNotes] = useState(""); const [error, setError] = useState(""); const [pending, setPending] = useState(false); const key = useRef<string>("");
  const load = useCallback(async () => { try { const current = await purchaseOrderApi.get(orderId); setOrder(current); const rows = await locationApi.listLocations(current.warehouseId); setLocations(rows.filter((row) => row.isActive && row.status === "ACTIVE").map((row) => ({ id: row.id, code: row.code }))); setEntries(Object.fromEntries(current.items.map((item) => [item.id, { quantity: String(pendingPackages(item)), allowOver: false, reason: "" }]))); } catch (cause) { setError(cause instanceof Error ? cause.message : "No se pudo preparar la recepción."); } }, [orderId]);
  useEffect(() => { void load(); }, [load]);
  const change = (id: string, patch: Partial<Entry>) => setEntries((current) => ({ ...current, [id]: { ...current[id], ...patch } }));
  const submit = async (event: FormEvent) => { event.preventDefault(); if (!order) return; const selected = order.items.filter((item) => Number(entries[item.id]?.quantity) > 0);  if (!selected.length) return setError("Indicá al menos una cantidad a recibir."); for (const item of selected) { const entry = entries[item.id]; if (isOverReceipt(entry.quantity, item) && (!entry.allowOver || !validateVarianceReason(entry.reason))) return setError(`La línea ${item.product.name} supera el pendiente: autorizá el exceso e indicá un motivo de al menos 5 caracteres.`); } setPending(true); setError(""); key.current = stableIdempotencyKey(key.current); try { await purchaseOrderApi.receive(order.id, { ...(LOCATIONS_ENABLED && locationId ? { locationId } : {}), reference, notes, idempotencyKey: key.current, items: selected.map((item) => ({ purchaseOrderItemId: item.id, packageQuantity: Number(entries[item.id].quantity), ...(isOverReceipt(entries[item.id].quantity, item) ? { allowOverReceipt: true, varianceReason: entries[item.id].reason.trim() } : {}) })) }); router.push(`/compras/${encodeURIComponent(order.id)}`); } catch (cause) { const status = typeof cause === "object" && cause ? (cause as { status?: number }).status : undefined; setError(status === 409 ? "La orden cambió o hay un exceso no autorizado. Revisá el pendiente y reintentá." : status === 400 ? `Revisá ubicación, cantidades y motivo de desvío.${cause instanceof Error && cause.message ? ` (${cause.message})` : ""}` : cause instanceof Error ? cause.message : "No se pudo registrar la recepción."); } finally { setPending(false); } };
  if (!order) return <section className="workspace"><div className="state"><strong>{error || "Cargando recepción…"}</strong></div></section>;
  if (order.status !== "CONFIRMED") return <section className="workspace"><div className="state error-state"><strong>La orden no está disponible para recibir.</strong><Link className="button secondary" href={`/compras/${order.id}`}>Volver a la orden</Link></div></section>;
  return <section className="workspace"><Link className="back-link" href={`/compras/${order.id}`}>← Volver a la orden</Link><header className="topbar"><div><p className="eyebrow">COMPRAS / RECEPCIÓN</p><h1>Recibir mercadería</h1><p className="subtitle">Las unidades se calculan con el snapshot de cada presentación.</p></div></header>{error && <Notice kind="error" role="alert">{error}</Notice>}<form onSubmit={(event) => void submit(event)}><section className="location-table-panel po-form-panel"><div className="form-grid">{LOCATIONS_ENABLED && <label className="field"><span>Ubicación del depósito</span><select value={locationId} onChange={(event) => setLocationId(event.target.value)}><option value="">Elegí ubicación</option>{locations.map((location) => <option key={location.id} value={location.id}>{location.code}</option>)}</select></label>}<label className="field"><span>Referencia</span><input value={reference} onChange={(event) => setReference(event.target.value)} /></label></div><label className="field"><span>Notas</span><textarea rows={2} value={notes} onChange={(event) => setNotes(event.target.value)} /></label></section><section className="location-table-panel"><div className="location-table-wrap"><table className="location-stock-table"><thead><tr><th>Producto</th><th>Pedido</th><th>Recibido</th><th>Esta recepción (packs)</th><th>Unidades</th><th>Pendiente</th></tr></thead><tbody>{order.items.map((item) => { const entry = entries[item.id] ?? { quantity: "0", allowOver: false, reason: "" }; const over = isOverReceipt(entry.quantity, item); return <tr key={item.id}><td><strong>{item.product.name}</strong><small>{item.packagingName} · x{item.unitsPerPack}</small></td><td>{item.packageQuantity} packs / {item.unitQuantity} u.</td><td>{item.receivedPackageQuantity} packs / {item.receivedUnitQuantity} u.</td><td><input aria-label={`Packs recibidos de ${item.product.name}`} type="number" min="0" step="1" value={entry.quantity} onChange={(event) => change(item.id, { quantity: event.target.value })} />{over && <label><input type="checkbox" checked={entry.allowOver} onChange={(event) => change(item.id, { allowOver: event.target.checked })} /> Autorizar exceso</label>}{over && <input aria-label="Motivo del exceso" value={entry.reason} onChange={(event) => change(item.id, { reason: event.target.value })} placeholder="Motivo (mín. 5 caracteres)" />}</td><td>{Number(entry.quantity || 0) * item.unitsPerPack} u.</td><td>{pendingPackages(item)} packs / {pendingPackages(item) * item.unitsPerPack} u.</td></tr>; })}</tbody></table></div><p className="location-muted">Si una cantidad excede el pendiente, la autorización y el motivo son obligatorios.</p></section><div className="top-actions po-submit"><Link className="button ghost" href={`/compras/${order.id}`}>Cancelar</Link><button className="button primary" disabled={pending}>{pending ? "Registrando…" : "Confirmar recepción"}</button></div></form></section>;
}
