"use client";

import { useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { LocationCodeModal } from "@/app/components/locations/location-panels";
import { LocationIcon } from "@/app/components/location-ui";
import type { WarehouseLocationWithProducts } from "@/app/lib/location-contract";

type LocationStatusFilter = "all" | "active" | "empty" | "occupied" | "blocked";
type SortOption = "picking" | "code" | "aisle" | "rack" | "occupancy";

export function LocationsStats({ locations }: { locations: WarehouseLocationWithProducts[] }) {
  const total = locations.length;
  const occupied = locations.filter((location) => location.stock.productCount > 0).length;
  const empty = total - occupied;
  const units = locations.reduce((sum, location) => sum + location.stock.totalQuantity, 0);
  return <section className="locations-kpis" aria-label="Resumen de ubicaciones">
    <Metric icon="pin" value={total} label={total === 1 ? "ubicación" : "ubicaciones"} note="Total en este depósito" tone="locations" />
    <Metric icon="box" value={occupied} label={occupied === 1 ? "ocupada" : "ocupadas"} note="Con stock asignado" percent={total ? occupied / total * 100 : 0} tone="occupied" />
    <Metric icon="box" value={empty} label={empty === 1 ? "vacía" : "vacías"} note="Sin stock asignado" percent={total ? empty / total * 100 : 0} tone="empty" />
    <Metric icon="barcode" value={units} label="unidades" note="Stock total en ubicaciones" tone="units" />
  </section>;
}

function Metric({ icon, value, label, note, percent, tone }: { icon: "pin" | "box" | "barcode"; value: number; label: string; note: string; percent?: number; tone: string }) {
  return <article className={`locations-kpi locations-kpi-${tone}`}><span className="locations-kpi-icon"><LocationIcon name={icon} /></span><div><strong>{value}</strong><span>{label}</span><small>{note}</small></div>{percent !== undefined && <span className="locations-mini-ring" style={{ "--ring-value": `${percent}%` } as React.CSSProperties} aria-label={`${Math.round(percent)} por ciento`}><i>{Math.round(percent)}%</i></span>}</article>;
}

export function LocationsListView({ warehouseId, locations, manage, onEdit, onStatus }: { warehouseId: string; locations: WarehouseLocationWithProducts[]; manage: boolean; onEdit: (location: WarehouseLocationWithProducts) => void; onStatus: (location: WarehouseLocationWithProducts, status: "BLOCKED" | "INACTIVE") => void }) {
  const [query, setQuery] = useState(""); const [status, setStatus] = useState<LocationStatusFilter>("all"); const [aisle, setAisle] = useState(""); const [rack, setRack] = useState(""); const [layout, setLayout] = useState<"list" | "grid">("list"); const [sort, setSort] = useState<SortOption>("picking");
  const aisles = useMemo(() => [...new Set(locations.map((location) => location.aisle).filter(Boolean))].sort((a, b) => a.localeCompare(b, "es-AR")), [locations]);
  const racks = useMemo(() => [...new Set(locations.map((location) => location.rack).filter(Boolean))].sort((a, b) => a.localeCompare(b, "es-AR")), [locations]);
  const filtered = useMemo(() => locations.filter((location) => {
    const normalized = query.trim().toLocaleLowerCase("es-AR"); const matchesQuery = !normalized || [location.code, location.aisle, location.rack, location.level, location.stock.primaryProduct?.name, location.stock.primaryProduct?.slug].some((value) => value?.toLocaleLowerCase("es-AR").includes(normalized));
    const matchesStatus = status === "all" || status === "active" && location.status === "ACTIVE" || status === "empty" && location.stock.productCount === 0 || status === "occupied" && location.stock.productCount > 0 || status === "blocked" && location.status === "BLOCKED";
    return matchesQuery && matchesStatus && (!aisle || location.aisle === aisle) && (!rack || location.rack === rack);
  }).sort((a, b) => sort === "code" ? a.code.localeCompare(b.code, "es-AR") : sort === "aisle" ? a.aisle.localeCompare(b.aisle, "es-AR") : sort === "rack" ? a.rack.localeCompare(b.rack, "es-AR") : sort === "occupancy" ? (b.stock.occupancyPercentage ?? -1) - (a.stock.occupancyPercentage ?? -1) : a.sortOrder - b.sortOrder), [aisle, locations, query, rack, sort, status]);
  return <><LocationsFilters query={query} onQuery={setQuery} status={status} onStatus={setStatus} aisle={aisle} onAisle={setAisle} rack={rack} onRack={setRack} aisles={aisles} racks={racks} layout={layout} onLayout={setLayout} /><section className="locations-list-panel"><header className="locations-list-heading"><strong>{filtered.length} {filtered.length === 1 ? "ubicación" : "ubicaciones"}</strong><label><LocationIcon name="sort" /><span className="sr-only">Ordenar ubicaciones</span><select value={sort} onChange={(event) => setSort(event.target.value as SortOption)}><option value="picking">Recorrido de picking</option><option value="code">Código</option><option value="aisle">Pasillo</option><option value="rack">Rack</option><option value="occupancy">Ocupación</option></select></label></header>{filtered.length ? <LocationsList warehouseId={warehouseId} locations={filtered} layout={layout} manage={manage} onEdit={onEdit} onStatus={onStatus} /> : <div className="state compact"><strong>No se encontraron ubicaciones con estos filtros.</strong><span>Probá ajustar la búsqueda o los filtros seleccionados.</span></div>}</section></>;
}

function LocationsFilters({ query, onQuery, status, onStatus, aisle, onAisle, rack, onRack, aisles, racks, layout, onLayout }: { query: string; onQuery: (value: string) => void; status: LocationStatusFilter; onStatus: (value: LocationStatusFilter) => void; aisle: string; onAisle: (value: string) => void; rack: string; onRack: (value: string) => void; aisles: string[]; racks: string[]; layout: "list" | "grid"; onLayout: (value: "list" | "grid") => void }) {
  return <section className="locations-filter-bar" aria-label="Filtros de ubicaciones"><label className="locations-search"><LocationIcon name="search" /><span className="sr-only">Buscar ubicación</span><input value={query} onChange={(event) => onQuery(event.target.value)} placeholder="Buscar ubicación..." /></label><div className="locations-filter-controls"><label>Estado<select value={status} onChange={(event) => onStatus(event.target.value as LocationStatusFilter)}><option value="all">Todos</option><option value="active">Activas</option><option value="empty">Vacías</option><option value="occupied">Ocupadas</option><option value="blocked">Bloqueadas</option></select></label><label>Pasillo<select value={aisle} onChange={(event) => onAisle(event.target.value)}><option value="">Todos</option>{aisles.map((value) => <option key={value} value={value}>{value}</option>)}</select></label><label>Rack<select value={rack} onChange={(event) => onRack(event.target.value)}><option value="">Todos</option>{racks.map((value) => <option key={value} value={value}>{value}</option>)}</select></label></div><LocationsViewToggle value={layout} onChange={onLayout} /></section>;
}

function LocationsViewToggle({ value, onChange }: { value: "list" | "grid"; onChange: (value: "list" | "grid") => void }) { return <div className="locations-view-toggle" aria-label="Formato de visualización"><button type="button" className={value === "list" ? "active" : ""} aria-pressed={value === "list"} onClick={() => onChange("list")}><LocationIcon name="list" />Lista</button><button type="button" className={value === "grid" ? "active" : ""} aria-pressed={value === "grid"} onClick={() => onChange("grid")}><LocationIcon name="grid" />Cuadrícula</button></div>; }

function LocationsList({ warehouseId, locations, layout, manage, onEdit, onStatus }: { warehouseId: string; locations: WarehouseLocationWithProducts[]; layout: "list" | "grid"; manage: boolean; onEdit: (location: WarehouseLocationWithProducts) => void; onStatus: (location: WarehouseLocationWithProducts, status: "BLOCKED" | "INACTIVE") => void }) { return <div className={layout === "grid" ? "locations-grid" : "locations-rows"}>{locations.map((location) => layout === "grid" ? <LocationCard key={location.id} warehouseId={warehouseId} location={location} manage={manage} onEdit={onEdit} onStatus={onStatus} /> : <LocationRow key={location.id} warehouseId={warehouseId} location={location} manage={manage} onEdit={onEdit} onStatus={onStatus} />)}</div>; }

function LocationRow(props: LocationItemProps) { return <LocationItem {...props} compact={false} />; }
function LocationCard(props: LocationItemProps) { return <LocationItem {...props} compact />; }
type LocationItemProps = { warehouseId: string; location: WarehouseLocationWithProducts; manage: boolean; onEdit: (location: WarehouseLocationWithProducts) => void; onStatus: (location: WarehouseLocationWithProducts, status: "BLOCKED" | "INACTIVE") => void };

function LocationItem({ warehouseId, location, manage, onEdit, onStatus, compact }: LocationItemProps & { compact: boolean }) {
  const router = useRouter(); const href = `/ubicaciones/${encodeURIComponent(warehouseId)}/${encodeURIComponent(location.id)}`; const open = () => router.push(href); const keyOpen = (event: React.KeyboardEvent<HTMLElement>) => { if (event.key === "Enter" || event.key === " ") { event.preventDefault(); open(); } };
  return <article className={`location-visual-card ${compact ? "location-visual-card-compact" : ""} ${location.stock.productCount === 0 ? "is-empty" : ""}`} role="link" tabIndex={0} onClick={open} onKeyDown={keyOpen} aria-label={`Abrir ubicación ${location.code}`}><header><span className="location-visual-icon"><LocationIcon name="pin" /></span><div className="location-visual-title"><div><strong className="mono">{location.code}</strong><LocationStatusBadge location={location} /></div><span>Pasillo {location.aisle} · Rack {location.rack} · Nivel {location.level}</span></div></header><LocationProductPreview location={location} /><div className="location-visual-metrics"><span><b>{location.stock.productCount}</b>{location.stock.productCount === 1 ? " producto" : " productos"}</span><span><b>{location.stock.totalQuantity}</b> unidades</span></div><LocationOccupancyRing occupancy={location.stock.occupancyPercentage} /><div className="location-picking-order"><b>#{location.sortOrder}</b><span>Orden de picking</span></div><footer onClick={(event) => event.stopPropagation()}><button type="button" className="button secondary" onClick={open}><LocationIcon name="eye" />Ver detalles</button>{manage && <><button type="button" className="button secondary" onClick={() => onEdit(location)}><LocationIcon name="edit" />Editar</button><LocationActionsMenu location={location} onStatus={onStatus} onOpen={open} /></>}</footer></article>;
}

function LocationStatusBadge({ location }: { location: WarehouseLocationWithProducts }) { const label = location.status === "BLOCKED" ? "Bloqueada" : location.status === "INACTIVE" ? "Inactiva" : location.stock.productCount === 0 ? "Vacía" : location.stock.occupancyPercentage !== null && location.stock.occupancyPercentage >= 100 ? "Completa" : "Activa"; const tone = label.toLocaleLowerCase("es-AR").replace("í", "i"); return <span className={`location-visual-status location-visual-status-${tone}`}>{label}</span>; }

function LocationProductPreview({ location }: { location: WarehouseLocationWithProducts }) { const { primaryProduct, productCount } = location.stock; if (!primaryProduct) return <div className="location-product-preview is-empty"><LocationIcon name="box" /><span>Sin productos asignados</span></div>; if (productCount > 1) return <div className="location-product-preview"><span className="location-product-icon"><LocationIcon name="box" /></span><div><strong>{productCount} productos asignados</strong><span>Ver productos en el detalle</span></div></div>; return <div className="location-product-preview"><span className="location-product-icon"><LocationIcon name="box" /></span><div><strong>{primaryProduct.name}</strong><span className="mono">{primaryProduct.slug || "—"}</span></div></div>; }

function LocationOccupancyRing({ occupancy }: { occupancy: number | null }) { const display = occupancy === null ? null : Math.max(0, Math.round(occupancy)); const capped = Math.min(display ?? 0, 100); const tone = display === null ? "undefined" : display === 0 ? "empty" : display >= 90 ? "full" : display >= 70 ? "warning" : "normal"; return <div className={`location-occupancy-ring location-occupancy-${tone}`} style={{ "--ring-value": `${capped}%` } as React.CSSProperties}><strong>{display === null ? "—" : `${display}%`}</strong><span>{display === null ? "Sin capacidad definida" : "Ocupación"}</span></div>; }

function LocationActionsMenu({ location, onStatus, onOpen }: { location: WarehouseLocationWithProducts; onStatus: (location: WarehouseLocationWithProducts, status: "BLOCKED" | "INACTIVE") => void; onOpen: () => void }) { const [open, setOpen] = useState(false); const [showCode, setShowCode] = useState(false); const action = (callback: () => void) => { setOpen(false); callback(); }; return <div className="location-visual-menu"><button type="button" className="icon-button" aria-label={`Más acciones para ${location.code}`} aria-expanded={open} onClick={() => setOpen((value) => !value)}><LocationIcon name="more" /></button>{open && <div><button onClick={() => action(() => setShowCode(true))}>Ver código</button><button onClick={() => action(onOpen)}>Mover stock</button><button onClick={() => action(onOpen)}>Ajustar stock</button><button onClick={() => action(() => onStatus(location, "BLOCKED"))}>Bloquear</button><button onClick={() => action(() => onStatus(location, "INACTIVE"))}>Desactivar</button></div>}{showCode && <LocationCodeModal code={location.code} onClose={() => setShowCode(false)} />}</div>; }
