"use client";
/* eslint-disable @next/next/no-img-element */
import { useEffect, useState } from "react";
import QRCode from "qrcode";
import { LocationIcon, locationDates } from "@/app/components/location-ui";
import type { LocationMovementType, LocationStats, LocationStockItem, LocationStockMovement, WarehouseLocation } from "@/app/lib/location-contract";
import { getLocationOccupancy } from "@/app/lib/location-rules";

export function LocationHeader({ location, warehouse, manage, onAdd, onMove, onEdit, onStatus, onEmpty, onHistory, onCode }: { location: WarehouseLocation; warehouse: string; manage: boolean; onAdd: () => void; onMove: () => void; onEdit: () => void; onStatus: (status: "BLOCKED" | "INACTIVE") => void; onEmpty: () => void; onHistory: () => void; onCode: () => void }) {
  const [open, setOpen] = useState(false); const label = location.status === "ACTIVE" ? "Activa" : location.status === "BLOCKED" ? "Bloqueada" : "Inactiva"; const action = (fn: () => void) => { setOpen(false); fn(); };
  return <header className="location-record-header"><div><p className="eyebrow">OPERACIONES / UBICACIONES / {warehouse}</p><h1><span className="mono">{location.code}</span> <span className={`status location-${location.status.toLowerCase()}`}>{label}</span></h1><p className="subtitle">Pasillo {location.aisle} · Rack {location.rack} · Nivel {location.level} · Orden #{location.sortOrder}</p></div><div className="top-actions">{manage && <><button className="button primary" onClick={onAdd}><LocationIcon name="plus" /> Agregar producto</button><button className="button secondary" onClick={onMove}><LocationIcon name="move" /> Mover stock</button><button className="button secondary" onClick={onEdit}><LocationIcon name="edit" /> Editar ubicación</button><div className="location-menu"><button className="button ghost" aria-label="Más acciones" aria-expanded={open} onClick={() => setOpen(!open)}>•••</button>{open && <div><button onClick={() => action(onCode)}>Ver código</button><button onClick={() => action(() => onStatus("BLOCKED"))}>Bloquear ubicación</button><button onClick={() => action(() => onStatus("INACTIVE"))}>Desactivar ubicación</button><button onClick={() => action(onEmpty)}>Vaciar ubicación</button><button onClick={() => action(onHistory)}>Ver historial completo</button></div>}</div></>}</div></header>;
}
export function LocationPermissionNotice({ role, canManage, onClose }: { role: string; canManage: boolean; onClose: () => void }) { return <div className="permission-note location-permission-note" role="status"><LocationIcon name="alert" /><span>Estás operando como <strong>{role}</strong>. Las operaciones de stock y edición siguen los permisos del rol activo; el backend valida la autorización final.</span>{!canManage && <em>Modo solo lectura.</em>}<button className="icon-button" aria-label="Cerrar aviso de permisos" onClick={onClose}><LocationIcon name="close" /></button></div>; }
export function LocationInfoCard({ location, warehouse }: { location: WarehouseLocation; warehouse: string }) { return <section className="location-card"><p className="eyebrow">DATOS DE UBICACIÓN</p><dl className="location-info"><div><dt>Estado</dt><dd><span className={`status location-${location.status.toLowerCase()}`}>{location.status}</span></dd></div><div><dt>Depósito</dt><dd>{warehouse}</dd></div><div><dt>Pasillo</dt><dd>{location.aisle}</dd></div><div><dt>Rack / nivel</dt><dd>{location.rack} / {location.level}</dd></div><div><dt>Orden</dt><dd>#{location.sortOrder}</dd></div><div><dt>Capacidad</dt><dd>{location.capacity === null ? "Sin configurar" : `${location.capacity} ${location.capacityUnit ?? "unidades"}`}</dd></div><div><dt>Actualizada</dt><dd>{locationDates.format(new Date(location.updatedAt))}</dd></div></dl></section>; }
export function LocationOccupancyCard({ stats, onConfigure }: { stats: LocationStats; onConfigure: () => void }) { const occ = getLocationOccupancy(stats.totalQuantity, stats.capacity); if (!stats.capacity) return <section className="location-card"><p className="eyebrow">OCUPACIÓN</p><strong>Capacidad no configurada</strong><span className="location-muted">Definí una capacidad para medir el uso.</span><button className="link-button" onClick={onConfigure}>Configurar capacidad</button></section>; return <section className="location-card"><p className="eyebrow">OCUPACIÓN</p><strong>{Math.round(occ.ratio * 100)}% ocupada</strong><span className="location-muted">{stats.totalQuantity} / {stats.capacity} {stats.capacityUnit ?? "unidades"}</span><div className="slot-bar"><span className={occ.tone === "full" ? "slot-bar-full" : occ.tone === "warning" ? "slot-bar-warning" : ""} style={{ width: `${occ.ratio * 100}%` }} /></div></section>; }
export function LocationStatsCards({ stats }: { stats: LocationStats }) { const cards: Array<[string, number, "pin" | "barcode" | "check" | "alert"]> = [["Productos", stats.productsCount, "pin"], ["Unidades", stats.totalQuantity, "barcode"], ["Disponibles", stats.availableQuantity, "check"], ["Reservadas", stats.reservedQuantity, "alert"]]; return <section className="location-stats">{cards.map(([label, value, icon]) => <div key={label}><LocationIcon name={icon} /><span>{label}</span><strong>{value}</strong></div>)}</section>; }
export function LocationInventoryTable({ stock, query, onQuery, page, onPage, manage, onMove, onAdjust, onRemove, onHistory, onAdd }: { stock: { items: LocationStockItem[]; total: number; page: number; pageSize: number }; query: string; onQuery: (q: string) => void; page: number; onPage: (n: number) => void; manage: boolean; onMove: (x: LocationStockItem) => void; onAdjust: (x: LocationStockItem) => void; onRemove: (x: LocationStockItem) => void; onHistory: (x?: LocationStockItem) => void; onAdd: () => void }) { const [value, setValue] = useState(query); useEffect(() => { const timer = setTimeout(() => onQuery(value), 350); return () => clearTimeout(timer); }, [value, onQuery]); return <section className="location-table-panel"><header><div><p className="eyebrow">INVENTARIO</p><h2>Stock almacenado</h2><span className="location-muted">{stock.total} {stock.total === 1 ? "producto en esta ubicación" : "productos en esta ubicación"}</span></div><label className="search"><LocationIcon name="search" /><span className="sr-only">Buscar producto</span><input value={value} onChange={(event) => setValue(event.target.value)} placeholder="Nombre, SKU, slug o código de barras..." /></label></header>{stock.items.length ? <><div className="location-table-wrap"><table className="location-stock-table"><thead><tr><th>Producto</th><th>SKU / slug</th><th>Total</th><th>Reservado</th><th>Disponible</th><th>Acciones</th></tr></thead><tbody>{stock.items.map((item) => <tr key={item.product.id}><td data-label="Producto"><strong>{item.product.name}</strong></td><td data-label="SKU / slug" className="mono">{item.product.sku ?? item.product.slug ?? "—"}</td><td data-label="Total">{item.quantity}</td><td data-label="Reservado">{item.reservedQuantity}</td><td data-label="Disponible"><strong>{item.availableQuantity}</strong></td><td><div className="row-actions">{manage && <><button onClick={() => onMove(item)}><LocationIcon name="move" />Mover</button><button onClick={() => onAdjust(item)}><LocationIcon name="adjust" />Ajustar</button><button className="location-danger" onClick={() => onRemove(item)}><LocationIcon name="trash" />Quitar</button></>}<button onClick={() => onHistory(item)}><LocationIcon name="history" />Movimientos</button></div></td></tr>)}</tbody></table></div><footer className="location-pagination"><span>{stock.total} productos</span><div><button className="button ghost" disabled={page <= 1} onClick={() => onPage(page - 1)}>Anterior</button><button className="button ghost" disabled={page * stock.pageSize >= stock.total} onClick={() => onPage(page + 1)}>Siguiente</button></div></footer></> : <div className="state"><strong>No hay productos almacenados en esta ubicación.</strong>{manage && <button className="button primary" onClick={onAdd}>Agregar producto</button>}</div>}</section>; }
const labels: Record<LocationMovementType, string> = { IN: "Ingreso", OUT: "Salida", TRANSFER: "Transferencia", ADJUSTMENT: "Ajuste" };
export function MovementTypeBadge({ type }: { type: LocationMovementType }) { return <span className={`status movement-${type.toLowerCase()}`}>{labels[type]}</span>; }
export function LocationMovementsCard({ items, onAll }: { items: LocationStockMovement[]; onAll: () => void }) { return <section className="location-table-panel movement-history"><header><div><p className="eyebrow">TRAZABILIDAD</p><h2>Movimientos recientes</h2><span className="location-muted">Últimos movimientos de stock en esta ubicación</span></div><button className="link-button" onClick={onAll}>Ver todos los movimientos →</button></header>{items.length ? <div className="location-table-wrap"><table className="location-stock-table"><thead><tr><th>Fecha</th><th>Tipo</th><th>Cantidad</th><th>Referencia</th><th>Usuario</th></tr></thead><tbody>{items.map((item) => <tr key={item.id}><td>{locationDates.format(new Date(item.createdAt))}</td><td><MovementTypeBadge type={item.type} /></td><td>{item.quantity}</td><td>{item.reference ?? "—"}</td><td>{item.actorUserId ?? "Sistema"}</td></tr>)}</tbody></table></div> : <div className="state compact"><strong>No hay movimientos registrados.</strong></div>}</section>; }
export function LocationCodeModal({ code, onClose }: { code: string; onClose: () => void }) { const [src, setSrc] = useState(""), [copied, setCopied] = useState(false); useEffect(() => { void QRCode.toDataURL(code, { margin: 1, width: 280 }).then(setSrc); }, [code]); return <div className="modal-backdrop"><section className="modal qr-modal" role="dialog" aria-modal="true" aria-labelledby="qr-title"><header><div><p className="eyebrow">UBICACIÓN / IDENTIFICACIÓN</p><h2 id="qr-title">Código de ubicación</h2></div><button className="icon-button" aria-label="Cerrar código" onClick={onClose}><LocationIcon name="close" /></button></header>{src && <img src={src} alt={`Código QR de ${code}`} />}<strong className="mono">{code}</strong><div className="location-code-actions"><button className="button secondary" onClick={() => void navigator.clipboard?.writeText(code).then(() => setCopied(true))}>{copied ? "Código copiado" : "Copiar código"}</button><button className="button primary" onClick={() => window.print()}>Imprimir etiqueta</button></div></section></div>; }
